### ISSUE TITLE
Unable to select some .msc files within C:\windows\system32 directory

### ISSUE THREAD

**Issue by MaRRiK74** [mRemoteNG/mRemoteNG#190] opened 2016-10-21 07:11 UTC
When I try to add dnsmgmt.msc as an external tool, this is not possible when this file is located in C:\windows\system32. Adding dsa.msc as an external tool is possible from within C:\windows\system32.
I have checked file permissions etc and they are exactly the same for both example .msf files.

When I copy the dnsmgmt.msc to another file location, like d:\test, it is possible to select the file in mRemoteNG.

Even when I create a batch file somewhere containing "C:\Windows\System32\dnsmgmt.msc" it won't work when called from mRemoteNG but when executed outside mRemoteNG it works fine. It seems that mRemoteNG can't find the file.

|  |  |
| --: | --- |
| Operating system | Windows Server 2008R2 x64, Windows Server 2012R2 x64, Windows Server 2016 |
| mRemoteNG version | 1.75 aplha 3 |

**Comment by mbulandra** [comment] 2016-10-21 19:20
Please try specifying the path as c:\windows\sysnative\dnsmgmt.msc, Windows has a mechanism of redirecting system paths for programs compiled for different architectures.

64-bit processes can access c:\windows\system32 directly, but 32-bit processes when trying to access c:\windows\system32 are redirected to c:\windows\syswow64. Mremoteng.exe is a 32-bit program. To avoid the redirection, specify the path as c:\windows\sysnative\dnsmgmt.msc. There is no sysnative folder in Windows directory, but specifying the path should work.

Unfortunately I did not have an occasion to try it out for you, but I'm using this technique to start 64-bit cmd.exe from a 32-bit application.

One more thing: Sysnative trick is available since Windows Server 2008. In Windows Server 2003 x64 you have to create a hardlink to c:\windows\system32 using for example junction.exe from SysInternals toolset.

**Comment by buzzyxtra** [comment] 2016-10-23 18:23
Unfortunately this also gives me an error. It tries to open the file but then the following error shows.

![image](https://cloud.githubusercontent.com/assets/19833001/19628469/95f166c8-995e-11e6-9de0-b58c19d1973a.png)

**Comment by mbulandra** [comment] 2016-10-25 18:53
Please try specifying the path as c:\windows\sysnative\dnsmgmt.msc, Windows
has a mechanism of redirecting system paths for programs compiled for
different architectures.

64-bit processes can access c:\windows\system32 directly, but 32-bit
processes when trying to access c:\windows\system32 are redirected to
c:\windows\syswow64. Mremoteng.exe is a 32-bit program. To avoid the
redirection, specify the path as c:\windows\sysnative\dnsmgmt.msc. There is
no sysnative folder in Windows directory, but specifying the path should
work.

Unfortunately I did not have an occasion to try it out for you, but I'm
using this technique to start 64-bit cmd.exe from a 32-bit application.

One more thing: Sysnative trick is available since Windows Server 2008. In
Windows Server 2003 x64 you have to create a hardlink to
c:\windows\system32 using for example junction.exe from SysInternals
toolset.


Regards,
MBu

**Comment by mbulandra** [comment] 2016-10-27 19:52
Today I had a few minutes to touch a live system and I was able to reproduce your problem.  It does not even work when I try to launch mmc.exe (either from system32 or sysnative) and pass the path dnsmgmt.msc in the argument. But finally I managed to find a workaround. Configure the external application in the following way:

filename: c:\windows\sysnative\cmd.exe
arguments: /c start c:\windows\system32\dnsmgmt.msc

The downside is cmd.exe window appearing for a fraction of second before the console starts.

**Comment by buzzyxtra** [comment] 2016-10-28 10:53
Ok that is an possibility. I have also tried the following, I have copied the target msc to another directory, let's say "C:\test\dnsmgmt.msc", when I use that path as an external tool it also works like your option. I have checked permissions on several msc files with system32 and they are equal to dnsmgmt.msc

**Comment by sparerd** [comment] 2017-04-20 17:22
Not able to reproduce the issue in recent versions. It appears a workaround was available. Closing this ticket

**Closed by sparerd** 2017-04-20 17:22 UTC
