### ISSUE TITLE
Can't enter host address in Quick Connect Toolbar during active putty session

### ISSUE THREAD

**Issue by damiankaczkowski** [mRemoteNG/mRemoteNG#535] opened 2017-05-02 17:04 UTC
Hello.

I would like to report another 100% reproducible and annoying bug.

One simply can't enter host address in Quick Connect Toolbar during active putty session.

Steps to reproduce:
When one have an open SSH session in putty window integrated and focused in mRemoteNG then one can't simply mouse click on Quick Connect Toolbar and enter the new host to connect. One have to click on mRemoteNG 'Title Bar' first, and only then the Quick Connect Toolbar will get 'unlocked' and will accept our input.

This bug hits me a hundred times a day. Really annoying one when working with SSH and putty which is  common case I think.

When working with RDP sessions integrated in mRemoteNG all is fine.

Greets.

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 Hotfix 5 |

**Comment by sparerd** [comment] 2017-05-02 17:07
Closing as duplicate of #176. Please follow that issue for updates

**Closed by sparerd** 2017-05-02 17:07 UTC
