### ISSUE TITLE
VNC Performance

### ISSUE THREAD

**Issue by jasonhpchu** [mRemoteNG/mRemoteNG#598] opened 2017-06-16 13:25 UTC
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008.17935  |

First off, great job on the program.  My #1 remote connection manager program.
I have several Ubuntu VPS setup with tightvncserver running in them.
I found using mRemoteNG's vnc, the performance is laggy compared to using UltraVNCViewer.
The response time between a click and a visual change is too long.  Sometimes a click would even be missed.
So much so, that I've setup UltraVNCViewer as external tool to use instead of the builtin vnc.
I didn't tweak any settings in the UltraVNCViewer, just default.
I would love to not need to use external tool if possible.
Thanks

**Comment by igor2x** [comment] 2017-06-28 05:41
I have **exactly** the same problem and I have also configured UltraVNCViewer as mRemoteNG external tool and left default UltraVNCViewer default setting and now mRemoteNG displays VNC like a charm.

I use the following arguments in mRemoteNG external tool:
![vnc-arguments](https://user-images.githubusercontent.com/10895030/27622067-1e2e1606-5bd5-11e7-9f8f-5d59eb39f1e9.png)

I made a print-screen. It looks at least VNC is doing some compression and other optimizations:

![vnc-window](https://user-images.githubusercontent.com/10895030/27621631-734ff83c-5bd2-11e7-840a-a1862ae2b424.png)

There is UltraVNCViewer source code available at https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/

**Comment by jasonhpchu** [comment] 2017-06-28 14:37
Good!  The lack of response was starting to make me look like a whiner.
Good to know I'm not the only one.

**Comment by sparerd** [comment] 2017-06-28 16:32
Thanks for sharing that @igor2x 

@jasonhpchu Sorry for the delay, I haven't been able to keep up with everything lately. We can certainly look into performance tuning for the built in vnc. Or at least expose some more options that allow for tuning. It might take us a bit to get to it though.

**Comment by jasonhpchu** [comment] 2017-06-28 16:40
Thanks @sparerd 
Just having the vnc improvement on your todo list is comforting.

**Comment by kmscode** [comment] 2017-06-28 18:29
@sparerd We'll have to discuss this further, but I think we might be better off trying to replace VncSharp with some sort of integrated UltraVNC build. That would be a large undertaking, but would gain other features as well...

**Comment by kmscode** [comment] 2017-10-30 14:11
Closing as duplicate of #573. 

We should plan on replacing VncSharp with a bundled version of UVNC.

**Closed by kmscode** 2017-10-30 14:11 UTC
Labels: Duplicate

**Comment by Neustradamus** [comment] 2025-06-26 13:05
To follow this ticket.
