### ISSUE TITLE
Position of quickconnect toolbar lost after minimizing

### ISSUE THREAD

**Issue by theovds** [mRemoteNG/mRemoteNG#264] opened 2016-11-22 07:46 UTC
I've set the quickconnect toolbar on top, very right, but after I minimized mRemoteNG and maximized it again, the toolbar is back to its old position.
![before](https://cloud.githubusercontent.com/assets/23518492/20515068/0b91d38e-b090-11e6-854b-43f268f0636f.png)
![after](https://cloud.githubusercontent.com/assets/23518492/20515067/0b7756c6-b090-11e6-8116-ab94ece614a8.png)

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 beta 1  |

**Comment by jcefoli** [comment] 2016-11-22 14:58
Valid issue. Reproduced it on Win 10 x64

**Comment by sparerd** [comment] 2016-11-22 14:59
Yep, can replicate as well. Might be a side effect of a small visual bug fix we tried to implement last week.

**Comment by sparerd** [comment] 2016-11-22 17:50
Looks like this bug has been around for a while - at least since v1.74. Since this isn't a regression bug and it seems like a pretty in depth fix will be necessary, we will likely not fix this for v1.75

**Comment by kmscode** [comment] 2019-03-10 01:16
no longer able to reproduce. There were fixes in 1.76 - likely related to #1068. Closing

**Closed by kmscode** 2019-03-10 01:16 UTC
Labels: Bug
