### ISSUE TITLE
Select a panel from the list - unhandled exception

### ISSUE THREAD

**Issue by systemsNinja** [mRemoteNG/mRemoteNG#843] opened 2017-12-13 22:12 UTC
Launched the app, and when I click on almost anything it sks me for a new panel. WHen I click new I get an error unhandled exception.
![2017-12-13 17_00_24-mremoteng - confcons xml](https://user-images.githubusercontent.com/22673899/33965110-c70ac62a-e028-11e7-9a1d-43016dc582c9.jpg)

|Detail|Value|
|--:|---|
OS: WIndows 7 pro
Ver: mRemoteNG-Installer-1.76.0.25712.msi

**Comment by sparerd** [comment] 2017-12-14 18:35
Thanks for reporting @systemsNinja. Could you provide the mRemoteNG.log file?
https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by tommybuck** [comment] 2017-12-19 12:24
Got the same error.

mRemoteNG.log:
2017-12-19 12:20:04,716 [13] ERROR - Couldn't close tab
Cannot access a disposed object.
Object name: 'TabControl'.

JIT:
System.NullReferenceException: Object reference not set to an instance of an object.
   at mRemoteNG.UI.Forms.Input.input.InputBox(String title, String promptText, String& value)
   at mRemoteNG.UI.Forms.frmChoosePanel.btnNew_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by sparerd** [comment] 2018-02-04 15:01
@tommybuck @systemsNinja Are you still seeing the same error with v1.76 alpha 2?
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76Alpha2

**Comment by tommybuck** [comment] 2018-02-15 16:59
Not getting the crash now. However still get the Select Panel box come up.

**Comment by sparerd** [comment] 2018-02-20 15:15
@tommybuck Is the following setting turned on for you? `Tools -> Options -> Tabs & Panels -> Always show panel selection dialog when opening connections`

**Comment by tommybuck** [comment] 2018-02-22 16:24
No its not turned on. It doesn't appear to make any difference whether its on or off?

**Comment by sparerd** [comment] 2018-02-22 18:36
Hmm interesting, that should control whether the popup is always shown. What version of mRemoteNG are you running?

**Comment by tommybuck** [comment] 2018-02-24 08:33
The latest development build.

**Comment by sparerd** [comment] 2018-02-24 21:10
Made a slight change in commit 946679f to ensure we dont try to close disposed tabs. I'm still curious as to why the panel selection dialog is popping up for you though.

**Comment by tommybuck** [comment] 2018-02-28 16:14
I've drilled this down to the below items that cause the pop up.

1. Help > Website
2. Help > Donate
3. Help > Support Forum
4. Help > Report a Bug

So you must be opening those options differently to the rest.

**Comment by sparerd** [comment] 2018-03-01 13:36
Ahhh yea I'm able to replicate it now. Thanks for providing that. I should be able to track down the root cause now

**Comment by sparerd** [comment] 2018-03-10 21:47
@tommybuck Is your default connection info Panel property empty? That is what was making the panel selection always appear for me. This will likely also happen if you use the quick-connect toolbar. They both create a new connection info from the default connection info and then set a few extra properties.

I'm not sure how best to resolve this. We could just always send the Help menu items to the app default panel 'General', but this may not always be desired. Another option would be to use the Panel defined in the default connection info if it is set, otherwise use 'General'.

**Comment by sparerd** [comment] 2018-07-25 19:46
@tommybuck I've committed a fix for the Help menu items as a part of #802. This should be available in the v1.76.5 release

**Closed** 2018-07-31 12:50 UTC
Labels: Bug
