### ISSUE TITLE
VNC, Username section

### ISSUE THREAD

**Issue by Numufar** [mRemoteNG/mRemoteNG#465] opened 2017-03-22 07:19 UTC
Hi to all.
Please add in VNC field "Username" section.
If VNC server set up for domain auth, there no way to connect throught mRemoteNG.
Thanks.

**Comment by tjgng** [comment] 2017-03-23 05:55
More or less this: https://github.com/mRemoteNG/mRemoteNG/issues/444

**Comment by farosch** [comment] 2021-08-15 19:33
Closing as duplicate of #444. Please follow this issue for updates.

**Closed by farosch** 2021-08-15 19:33 UTC
Labels: Enhancement, VNC
