### ISSUE TITLE
RestrictedAdmin mode?

### ISSUE THREAD

**Issue by utsecnet** [mRemoteNG/mRemoteNG#849] opened 2017-12-18 17:53 UTC
Looking for how to use mrNG in Restricted Admin mode.  If it's not possible, consider this a feature request.

**Comment by sparerd** [comment] 2017-12-18 19:24
We will have to implement this.

*Dev note for later:*
Here is the best info out there on how to enable this: https://social.msdn.microsoft.com/Forums/windows/en-US/93cb63d8-b4ff-40dd-8d11-66867db6258f/rdp-activex-and-restrictedadminmode?forum=winforms

**Comment by simonai1254** [comment] 2021-12-30 00:31
This seems to be a duplicate of #1125

**Comment by Kvarkas** [comment] 2022-04-15 15:47
https://github.com/mRemoteNG/mRemoteNG/pull/2203

**Closed by Kvarkas** 2022-04-15 15:47 UTC
Labels: Enhancement
