### ISSUE TITLE
Winkey + Up Button doesn't enlarge the window

### ISSUE THREAD

**Issue by tamirble** [mRemoteNG/mRemoteNG#245] opened 2016-11-13 15:22 UTC
On all windows applications, when you press Winkey + Up arrow the window the being enlarged. 
Moreover, when you press Winkey + Down the window is being minimized.
**On mremoteNG putty sessions you cannot do it! Can anyone fix that?**
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment] 2016-11-14 20:26
@tamirble I cannot reproduce this in the main window or with an RDP session open *without* redirect keys enabled. However, I _can_ reproduce with a PuTTY session open. 

This is likely because PuTTY is a separate app which we then integrate into the main Window.

I haven't tested RDP with key redirection. But I would expect that if the RDP session was focused, the keys would be sent to the target session...

This most likely isn't going to be fixable with PuTTY in use. The solution would be to replace PuTTY: #181

**Comment by kmscode** [comment] 2016-11-23 18:42
@tamirble Did you have a chance to look at my previous comment? Could you please confirm if you're experiencing the same results that I described?

**Comment by tamirble** [comment] 2017-01-28 14:07
@kmscode if that so, how come I can use alt+F4 to close mremote when in putty session.

**Comment by sparerd** [comment] 2017-04-20 17:29
We will keep this ticket open as an acceptance-criteria for future ssh solutions. For now, I'm tagging this as a bug

**Comment by tamirble** [comment] 2017-04-20 17:56
@sparerd Thank you! Fixing this will improve my life so much :)

**Comment by farosch** [comment] 2021-12-14 20:52
Closing as unfixable. This will automatically be fixed with either #181  or #290

**Closed by farosch** 2021-12-14 20:52 UTC
Labels: Bug
