### ISSUE TITLE
Fips Compliance

### ISSUE THREAD

**Issue by mremotegod** [mRemoteNG/mRemoteNG#992] opened 2018-06-15 15:53 UTC
## Expected Behavior
Id love to see this application use fips compliant algorithms. as a system admin this tool has proved very useful for everyday task to include ssh and remote desktop.

## Current Behavior
Currently i receive an error that this application cannot run because it is not fips compliance and therefore will close

## Possible Solution
Enable Fips compliance to the application

**Comment by sparerd** [comment] 2018-06-22 01:45
Closing as duplicate of #222. Please follow that issue for further updates

**Closed by sparerd** 2018-06-22 01:45 UTC
Labels: Duplicate
