### ISSUE TITLE
Requested value 'donotplay' was not found.

### ISSUE THREAD

**Issue by KsenZ** [mRemoteNG/mRemoteNG#904] opened 2018-03-02 02:28 UTC
Errors at startup for all connections
![2018-03-02_09-21-05](https://user-images.githubusercontent.com/643267/36880557-ec6e5a10-1dfb-11e8-91ce-6010029b38c3.png)
. 

> An error occured while loading the connection entry for "WORK" from "". Requested value 'donotplay' was not found.

|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.76.1.21655  |

**Comment by onewithname** [comment] 2018-03-02 10:40
Same error after updating today to new version. Rip all icons :(


|Operating system | Windows 10 Enterprise 16299.15 |
|mRemoteNG version| 1.76.1.21624 |

**Comment by johnwc** [comment] 2018-03-02 16:31
Yep, same here.

----------
ErrorMsg
3/2/2018 10:22:57 AM
An error occured while loading the connection entry for "<servername>" from "". Requested value 'donotplay' was not found.
----------

**Comment by sparerd** [comment] 2018-03-03 15:24
Duplicate of #899, though I didn't have time to get a fixed build out until now. This is resolved in v1.76 Alpha 4.

https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76Alpha4

**Closed** 2018-03-03 15:57 UTC
Labels: Bug, Duplicate
