### ISSUE TITLE
Cant ssh Ubuntu 22

### ISSUE THREAD

**Issue by dresc** [mRemoteNG/mRemoteNG#2353] opened 2023-02-15 14:37 UTC
Hi

Im big fan of mRemoteNG :D

I discovered problem. I cant connect to ubuntu 22 servers with mRemoteNG 1.76.20, it says "server refused our key".
I checked mRemoteNG uses putty 0.71...

However i installed putty 0.78 and it had no problems.

When I use custom putty path it dont fill my key password, its annoyng.

Can you please add putty 0.78 as default mRemoteNG putty

Thank you advance,
All best :)

**Comment by Kvarkas** [comment] 2023-02-15 18:51
please do manual update for puttyNG, copy from [where](https://github.com/mRemoteNG/PuTTYNG/releases/download/v0.78.0.10/PuTTYNG.exe) and replace older, version 1.77.3 already have it, we planing soon nb release as well

**Comment by simonai1254** [comment] 2023-02-16 09:28
I presume this is a duplicate of #2220 and therefore may be closed as a duplicate

**Comment by Kvarkas** [comment] 2023-02-16 09:51
will add into documentation so we could close similar with RTFM tag :)

**Closed as completed by Kvarkas** 2023-02-16 09:51 UTC
Labels: Ready, SSH, Putty, 1.77.3

**Comment by simonai1254** [comment] 2023-02-16 10:02
> will add into documentation so we could close similar with RTFM tag :)

Or create a new release so users just need to update 😉

**Comment by Kvarkas** [comment] 2023-02-16 10:03
you see this is sorted already in 1.77.3 but users keep using older version, we work hard at the moment to release nb and preview soon as well and move to stable one asap

**Comment by Kvarkas** [comment] 2023-02-16 13:45
https://mremoteng.readthedocs.io/en/v1.77.3-dev/known_issues.html
