### ISSUE TITLE
Retire old mRemoteNG forum

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1382] opened 2019-03-30 16:38 UTC
I think the old mRemoteNG forum (http://forum.mremoteng.org/index.php) isn't being properly maintained and should be removed like it was already announced (http://forum.mremoteng.org/viewtopic.php?f=2&t=3309)

**Comment by kmscode** [comment] 2019-04-02 23:56
duplicate of #606

**Closed by kmscode** 2019-04-02 23:56 UTC
Labels: Project Infrastructure, Request For Comment
