### ISSUE TITLE
Direct connect field isn't clickable when in SSH2 session

### ISSUE THREAD

**Issue by ethancedrik** [mRemoteNG/mRemoteNG#374] opened 2017-01-27 23:33 UTC
Go into direct connect, switch version type to SSH2, add a server IP, direct connect, copy and paste a few times while clicked into the SSH2 session, alt tab out and back in and continue the SSH2 session typing commands, etc. Then go back and try and click the direct connect field to type in a new IP, it'll take like 20 tries of clicking around to be able to get into that field. 

https://i.gyazo.com/dc31a03794efc15469b0f32b9fd82608.mp4

When the window title bar is white that's when it's hard to click, when I manage to get it to turn orange again I can then click and be able to copy and paste and edit the IP.

|||
|--:|---|
|Operating system | Windows 8.1 x64 and Windows 10 Anniversary Update |
|mRemoteNG version| 1.75 RC1  |

**Comment by sparerd** [comment] 2017-01-28 03:41
duplicate of #176

**Comment by sparerd** [comment] 2017-04-20 17:55
Not sure why I didn't close this when I last posted. Please follow #176 for further updates

**Closed by sparerd** 2017-04-20 17:55 UTC
