### ISSUE TITLE
SQL connections bugs, cannot add or modify connections

### ISSUE THREAD

**Issue by peanek** [mRemoteNG/mRemoteNG#612] opened 2017-06-27 09:59 UTC
Hello, 

From beginning of using SQL DB from saving connections I have big, very big problem with all the Connection list..

a) The main problem is that it is "Expanding" all the time(by itself), and this is completely random. 
b) second problem - I cannot modify or create new connection without problem because when I will try - list is exapanding and I loose actual connection in "Config" window ( I mean - I can make additional changes for connection - but it will be not saved. When I will open connection once again - changes are gone) 
I can manage to do it - but I need to be very fast :) like 5 seconds. 
This is very werid.

Operating system used by mRemotNg (few and on every the same behavior) :
- Windows 10 x64 ENG
- Windows 7 x64 ENG
- Windows Server 2008 R2 ENG

Versions on mRemoteNG that had this problem : 
- v1.75.7008 (Hotifx 8) (newest)
- v1.75.7007 (Hotifx 7)
- v1.75.7006 (Hotifx 6)
- v1.75.7005 (Hotifx 5)
- v1.75.7003 (Hotfix 4)

Unfortunately there is nothing in LOGS that could tell us why it is happening, all looks ok : 
```
2017-06-27 10:34:00,680 [129] INFO - Connection to ENEL-RADIAL.produkcja.poland.bitron.loc via IntApp closed by user ced6.
2017-06-27 10:35:47,746 [1] INFO - Attempting to start: Dame Ware
2017-06-27 10:35:47,756 [1] INFO - Assuming no other errors/exceptions occurred immediately before this message regarding Dame Ware, the next "closed by user" message can be ignored
2017-06-27 10:35:47,764 [122] INFO - Connection Event Closed
2017-06-27 10:35:47,765 [122] INFO - Connection to SPEA23.PRODUKCJA.POLAND.BITRON.LOC via IntApp closed by user ced6.
2017-06-27 10:44:48,662 [1] INFO - Attempting to start: Dame Ware
2017-06-27 10:44:48,669 [1] INFO - Assuming no other errors/exceptions occurred immediately before this message regarding Dame Ware, the next "closed by user" message can be ignored
2017-06-27 10:44:48,681 [91] INFO - Connection Event Closed
2017-06-27 10:44:48,681 [91] INFO - Connection to SPEA23.PRODUKCJA.POLAND.BITRON.LOC via IntApp closed by user ced6.
2017-06-27 10:45:12,910 [1] INFO - Attempting to start: Dame Ware
2017-06-27 10:45:12,918 [1] INFO - Assuming no other errors/exceptions occurred immediately before this message regarding Dame Ware, the next "closed by user" message can be ignored
2017-06-27 10:45:12,928 [80] INFO - Connection Event Closed
2017-06-27 10:45:12,928 [80] INFO - Connection to SPEA27.PRODUKCJA.POLAND.BITRON.LOC via IntApp closed by user ced6.
2017-06-27 10:51:35,703 [1] INFO - Attempting to start: Dame Ware
2017-06-27 10:51:35,712 [1] INFO - Assuming no other errors/exceptions occurred immediately before this message regarding Dame Ware, the next "closed by user" message can be ignored
2017-06-27 10:51:35,721 [93] INFO - Connection Event Closed
2017-06-27 10:51:35,722 [93] INFO - Connection to SPEA27.produkcja.poland.bitron.loc via IntApp closed by user ced6.
2017-06-27 11:07:57,336 [1] INFO - Attempting to start: Dame Ware
2017-06-27 11:07:57,346 [1] INFO - Assuming no other errors/exceptions occurred immediately before this message regarding Dame Ware, the next "closed by user" message can be ignored
2017-06-27 11:07:57,353 [203] INFO - Connection Event Closed
2017-06-27 11:07:57,354 [203] INFO - Connection to BITRON-PRD5.produkcja.poland.bitron.loc via IntApp closed by user ced6.
2017-06-27 11:32:54,171 [1] INFO - mRemoteNG 1.75.7008.17907 starting.
2017-06-27 11:32:54,180 [1] INFO - Command Line: System.String[]
2017-06-27 11:32:54,456 [1] INFO - Microsoft Windows 10 Pro  64-bit
2017-06-27 11:32:54,456 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2017-06-27 11:32:54,456 [1] INFO - System Culture: en-GB/English (United Kingdom)
2017-06-27 11:32:54,457 [1] INFO - Checking FIPS Policy...
2017-06-27 11:32:54,457 [1] INFO - Checking Lenovo AutoScroll Utility...
2017-06-27 11:32:55,503 [1] INFO - Loading External Apps from: C:\Users\ced6\AppData\Roaming\mRemoteNG\extApps.xml
2017-06-27 11:32:55,504 [1] INFO - Adding External App: Dame Ware C:\Program Files\SolarWinds\DameWare Mini Remote Control x64\DWRCC.exe -c: -h: -m:%hostname% -a:0 -u:etcrdc -p:tcm$2011#
2017-06-27 11:32:56,134 [1] WARN - XmingPortablePuttySessions.Watcher.StartWatching() failed.
The directory name sessions is invalid.
2017-06-27 11:32:58,250 [1] ERROR- GetUpdateInfoCompleted() failed.
Unable to connect to the remote server
No connection could be made because the target machine actively refused it 104.28.9.231:443
```

Eventually here is my user.config : 
[user.config.txt](https://github.com/mRemoteNG/mRemoteNG/files/1104903/user.config.txt)

EDIT: 
I can eventually make a video with this behavior, because it is hard to explain in text :)

**Comment by sparerd** [comment] 2017-06-27 14:49
Thanks for the detailed report! Although I think this is a duplicate of #529 - please subscribe to that issue for further updates.

**Closed** 2017-06-27 15:21 UTC
