### ISSUE TITLE
View > Jump to not working as expected

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1270] opened 2019-01-11 11:27 UTC
## Expected Behavior
 - Clicking one of the items under View > Jump docks the element and brings it to the front/sets focus despite the current state

## Current Behavior
 - Only one single button for Connections and Configuration
 - Doesn't bring DPS content to the front when clicked
 - ![image](https://user-images.githubusercontent.com/22905106/51030892-13ee2880-159b-11e9-97d8-60b2ce48af3d.png)
Jumps between Connections and Config panes when both are pinned

## Possible Solution
 - Provide a third button:
   - Connections
   - Config
   - Notifications
 - Check on every click:
   - If already docked to DPS, just expand/show/focus
   - When not docked yet, dock and expand/show/focus

## Your Environment

* Version used: Current develop branch
* Operating System and version: Windows 10 1809 x64

**Comment by farosch** [comment] 2019-01-11 11:35
@sparerd @kmscode Can implement this if you want me to

**Comment by kmscode** [comment] 2019-01-11 15:13
Assigned to @farosch - Thanks for the assistance!

@sparerd What are your thoughts on this:

>When not docked yet, dock and expand/show/focus

Should it be docked/expand/show/focus or just expand/show/focus. Since docking would potentially save the users layout which may be undesired.

**Comment by sparerd** [comment] 2019-01-13 00:05
Here are 2 user cases for how I would expect it to function:
- If someone drags the connections window to a different screen (floating) and clicks the "go to" button, it should not redock the window to the main mremoteng window.
- If the connections window is closed (not just hidden) and the user clicks the "go to" button, the connections window should be shown and brought into view. If possible, in the last location the connections windows was placed before being closed. If that proves too problematic, then the default left-dock is fine.

*Side note:* we should probably be documenting these cases somehow. Eventually I want to create some automated ui acceptance tests, but for now the [Acceptance Testing](https://github.com/mRemoteNG/mRemoteNG/wiki/Acceptance-Testing) page is the best we have for collecting these sorts of expected behaviors.

**Comment by farosch** [comment] 2019-01-13 00:54
If I did not misunderstand you this  be already the case: Looks like this is the default behavior of DPS:
![2019-01-13_01-49-28](https://user-images.githubusercontent.com/22905106/51080113-fc678a80-16d5-11e9-913a-c3429aa9ec4b.gif)

**Comment by kmscode** [comment] 2019-02-11 22:00
#1275 has been merged. Closing.

**Closed by kmscode** 2019-02-11 22:00 UTC
Labels: Enhancement
