### ISSUE TITLE
Windows 11 - Double click connection before it will connect

### ISSUE THREAD

**Issue by TDMPro2K** [mRemoteNG/mRemoteNG#2107] opened 2022-01-01 09:01 UTC
Ever since i have gone to Windows 11, I have to double hit the connection. The first time i will get an error
----------
WarningMsg
01/01/2022 09:00:06
RDP disconnected!
264 This computer can't connect to the remote computer.

The two computers couldn't connect in the amount of time allotted. Try connecting again. If the problem continues, contact your network administrator or technical support.
----------

However it i hit it again it will then connect. Seems to happen on multiple hosts

**Comment by farosch** [comment] 2022-01-02 17:52
Duplicate of #540.

**Closed as completed by farosch** 2022-01-02 17:52 UTC
Labels: Need 2 check
