### ISSUE TITLE
Auto Hide Connections/Config panel

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#541] opened 2017-05-05 06:04 UTC
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7000.19221  |

I want to auto hide the connections and config panel to have more space.
Is there a way to combine both panels? So that they show up together.
At the moment they are separated and I can only see one at a time when auto hide is enabled.

**Comment by kmscode** [comment] 2017-05-06 02:04
That's a feature request. I think there is another issue opened for the same thing.

**Comment by farosch** [comment] 2019-09-01 15:35
Closed as a duplicate of #1406

**Closed by farosch** 2019-09-01 15:35 UTC
