### ISSUE TITLE
Centralize credentials

### ISSUE THREAD

**Issue by jbruns2015** [mRemoteNG/mRemoteNG#844] opened 2017-12-14 08:22 UTC
Would be ideal to centralize credentials in this tool.  When a person has multiple folders for various reasons and those folders are using same creds, it becomes tedious when passwords change.  For me, it's every 10 hours or daily that I must update in multiple mremoteng folders.

**Comment by sparerd** [comment] 2017-12-14 13:31
Duplicate of #208

**Closed by sparerd** 2017-12-14 13:31 UTC
Labels: Duplicate
