### ISSUE TITLE
No username setting for VNC

### ISSUE THREAD

**Issue by Jefronty** [mRemoteNG/mRemoteNG#1913] opened 2020-12-11 21:52 UTC
When setting up a new connection as VNC there is no way to set a username for the connection.  
![VNC config](https://i.ibb.co/qpsqq5C/m-Remote-NG-vnc.png)  
When attempting to connect I get the error "Opening connection failed! Unable to read next byte(s)."

**Comment by LIyoai** [comment] 2020-12-30 09:07
Never noticed that I need a username for vnc.
Is a connection with another vnc client working? And there you need to enter an username?

**Comment by LIyoai** [comment] 2020-12-30 09:21
#465

**Comment by farosch** [comment] 2021-08-15 19:34
Closing as duplicate of #444. Please follow this issue for updates.

**Closed by farosch** 2021-08-15 19:34 UTC
Labels: TechnicalDebt, VNC
