### ISSUE TITLE
Credential containing "£" character does not authenticate using SSH

### ISSUE THREAD

**Issue by hunnymonster** [mRemoteNG/mRemoteNG#1509] opened 2019-07-08 13:33 UTC
If I take a user - "username" with a password of "password" and change it so the password contains the "£" character (say "password£", then future automated authentications fail, yet manually typing the password as "password£" when prompted works fine

## Expected Behavior
That any password containing any character should work in automated login

## Current Behavior
If I take a user - "username" with a password of "password" and change it so the password contains the "£" character (say "password£", then future automated authentications fail, yet manually typing the password as "password£" when prompted works fine

## Possible Solution
A complete speculative guess on my part that either the "£" character is being used as some form of escape or that the hashing function isn't coping well with any ASCII > 127.

## Steps to Reproduce (for bugs)

1. Create a connection to an ssh device
2. Take an ssh device with credentials "username" & "password"
3. Save the credentials in mRemoteNG
4. Using automated login, sign in to the device.
5. Change the password of the user to contain "£" (example: "password£")
6. Update the saved credentials in mRemoteNG to the new password (ie. "password£")
7. Using automated login, sign in to the device (doesn't work)
8. At the prompt type in the password saved in 6 above (works)
9. change the password to remove the "£"
10. Update the saved credentials in mRemoteNG to the new password from 9
11. Using automated login, sign in to the device (works)

## Context
Saving a secure password :)

## Your Environment
mRemoteNG v1.76.20.24615
Windows 10 v1903 Build 18932.1000

**Comment by kmscode** [comment] 2019-07-09 17:34
Does this only happen with SSH/PuTTY connections, or does it also happen with RDP?

**Comment by hunnymonster** [comment] 2019-07-09 17:45
Good question, I rarely use RDP, so I shall try that next time I'm able.

**Comment by hunnymonster** [comment] 2019-07-10 06:59
RDP appears to work fine with a "£" character in the password

Test protocol
created user with password "Q!w2e3r4t5" connected successfully to ssh & RDP hosts
changed password to "Q!w2e£r4t5" - connected successfully to RDP, prompted for password on ssh, entered "Q!w2e£r4t5" and successfully logged in.

I guess that makes this a PuTTYNG module issue?

**Comment by farosch** [comment] 2019-10-03 15:47
@hunnymonster Does this also happen when using PuTTY?

**Comment by farosch** [comment] 2019-10-06 16:14
Just tested this with the latest PuTTY release (0.73) and also with the latest development snapshot (2019-10-02.283bd54).
This is problem occurs within PuTTY itself, and thus has nothing to do with any mRemoteNG code.

Running `putty test@sso.domain.de -pw password£` leaves me with this:
![image](https://user-images.githubusercontent.com/22905106/66272034-f2d61200-e864-11e9-9c54-fcc77ed6973b.png)

Pasting the exact same password into the session window then authenticates just fine.

**Comment by hunnymonster** [comment] 2019-10-06 16:39
Sorry for the delay in replying - been in hospital... Do I need to report this as a bug to the PuTTY project or have you already done so?

**Comment by farosch** [comment] 2019-10-06 18:34
@hunnymonster No worries, I'll submit the bug report to the PuTTY project. 😉 
Take extra good care!

**Comment by kmscode** [comment] 2021-07-04 00:13
Latest pre-release of puttyng is available here:
https://github.com/mRemoteNG/PuTTYNG/releases/tag/0.75.0.1

As it's been confirmed to be an upstream bug, if the problem is not resolved in this build (and confirmed that it's still a bug in official PuTTY builds) please submit a bug report directly to PuTTY dev per their instructions:
https://www.chiark.greenend.org.uk/~sgtatham/putty/feedback.html#feedback-bugs

**Closed by kmscode** 2021-07-04 00:13 UTC
Labels: Bug, Vendor/Upstream Issue
