### ISSUE TITLE
Importing RDG files from RDCP 2.7 to mRemote 1.75

### ISSUE THREAD

**Issue by SAMIT2016** [mRemoteNG/mRemoteNG#603] opened 2017-06-20 13:25 UTC
I need to import .rdg file and i have tried importing it and also opening it and it fails both times. With import the error is - cannot import the file. With opening it the error is - you are trying to load a connection file that was created using an very early version of mRemote, this could result in a runtime error. if you run into such an error, please create a new connection file!

can someone help?

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment] 2017-06-20 15:53
@SAMIT2016 Do you mean Remote Desktop Connection Manager?

This is likely a duplicate of #225

**Closed** 2017-11-10 01:21 UTC
Labels: Duplicate, Enhancement
