### ISSUE TITLE
Panel name is not saved

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#605] opened 2017-06-21 13:49 UTC
I rename the default Panel from "Allgemein" to "General" in the default properties of the root connections.
When I restart it is "Allgemein" again.

Btw. language is set to English US. But the Panel still have the German name.

|||
|--:|---|
|Operating system | Windows 2012 R2 |
|mRemoteNG version| v1.75.7008 (Hotifx 8)  |

**Comment by kmscode** [comment] 2017-06-21 14:24
Duplicate of #468 . Please upvote that issue to receive any further updates.

**Closed by kmscode** 2017-06-21 14:24 UTC
Labels: Duplicate
