### ISSUE TITLE
Exeption occurred on closing panel

### ISSUE THREAD

**Issue by MinerBigWhale** [mRemoteNG/mRemoteNG#1613] opened 2019-10-07 13:28 UTC
An exception occurred closing panel 

Exception Message
```
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."
```

Stack trace
```
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 802
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 154
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Environment
OS: Microsoft Windows NT 10.0.17763.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args:

**Comment by farosch** [comment] 2019-10-07 14:45
@MinerBigWhale Can you provide steps to reproduce this issue?

**Comment by farosch** [comment] 2019-10-09 21:58
Duplicate of #1495

**Closed by farosch** 2019-10-09 21:58 UTC
