### ISSUE TITLE
Add hotkey to hide menu bar

### ISSUE THREAD

**Issue by evan10171508** [mRemoteNG/mRemoteNG#1074] opened 2018-08-15 06:09 UTC
## Expected Behavior

add a Shortcut key，for example（F12），when press F12，the nRemoteNG Window hidden menu bar、title bar。

## Your Environment

* Version used: 1.76.6.14631
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment] 2019-03-19 22:22
#1332

**Comment by farosch** [comment] 2019-11-23 11:58
Duplicate of #666

**Closed by farosch** 2019-11-23 11:58 UTC
Labels: Enhancement
