### ISSUE TITLE
connection tree filter

### ISSUE THREAD

**Issue by ramiralez** [mRemoteNG/mRemoteNG#505] opened 2017-04-12 17:11 UTC
connection pane, have searchbox, but current search implementation is not convenient.
it would be better, if searchbox filter connection tree, and display only items containing enterd text.

**Comment by sparerd** [comment] 2017-04-12 17:14
Closing as duplicate of #338. Please follow that ticket for updates

**Closed by sparerd** 2017-04-12 17:14 UTC
