### ISSUE TITLE
UltraVNC as default and integrated

### ISSUE THREAD

**Issue by cianoz** [mRemoteNG/mRemoteNG#752] opened 2017-10-24 14:17 UTC
Hello
I'm new to mRemoteNG and I'm using it for a few days. I have several Windows machines I manage with UltraVNC. mRemoteNG uses its own VNC client but I'm not satisfied with it, because very often sessions disconnect and has other issues. 
I see that I can use UltraVNC as external tool, but it's not integrated, returns an external window and I can't run it with a single click as the default VNC viewer.

Is there a way to replace the mRemoteNG default VNC viewer with UltraVNC?
I searched here and around but found nothing.

**Comment by kmscode** [comment] 2017-10-30 14:09
Duplicate of #573 - please upvote that issue for tracking.

Also reference #598 as this is similar.

**Closed by kmscode** 2017-10-30 14:09 UTC
Labels: Duplicate
