### ISSUE TITLE
Allow double click on tab to be assigned to a different operation

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#161] opened 2016-10-10 16:19 UTC
Would like for the ability to use a different operation than closing the tab when double clicking on a tab. 

One suggestion: duplicate session

Depends on #154

**Comment by jcefoli** [comment] 2016-10-10 17:15
A duplicate session action doesn't really make sense for RDP. Wouldn't that essentially just reconnect, since you can only be connected to the same server over RDP once? I guess this could be useful for SSH or external apps.

**Comment by kmscode** [comment] 2016-10-10 19:35
@jcefoli agreed. Might make it user configurable or default to something reasonable for each session type.

**Comment by benwa** [comment] 2016-10-14 17:23
I'd suggest by default double clicking the tab be a jump to fullscreen.

**Comment by jotatsu** [comment] 2019-02-07 16:49
Proposed for 2.0, this could require a better command style interface internally.

**Comment by farosch** [comment] 2021-12-14 21:01
We should just keep things simple. I'm sure implementing all these ideas may be nice for some users, but the majority won't need them. It needs to be implemented, tested and maintained and honestly, I don't see anybody doing it with all these major issues in the project that haven't been addressed for years. Also, all these functions are an/or could be available in the context menu, which is just one more click away.
I guess how old the issue is and the fact that no one has ever done anything to push this forward just proves my point :P
Closing this.

**Closed by farosch** 2021-12-14 21:01 UTC
Labels: Enhancement
