### ISSUE TITLE
RDP Disconnects When Resizing MRemoteNG Panels #2

### ISSUE THREAD

**Issue by wingmaker101** [mRemoteNG/mRemoteNG#1860] opened 2020-09-10 19:00 UTC
RDP Disconnects When Resizing MRemoteNG Panels

## Expected Behavior
should not disconnect

## Current Behavior
disconnects

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

win 10 ver 1909

**Comment by farosch** [comment] 2020-09-15 20:39
Duplicate of #1859

**Closed by farosch** 2020-09-15 20:39 UTC
