### ISSUE TITLE
Vertical Scrollbar of SSH sessions gone since last mRemote update

### ISSUE THREAD

**Issue by reibuehl** [mRemoteNG/mRemoteNG#1391] opened 2019-04-04 20:08 UTC
Up until the last two mRemote updates I used to have a vertical scrollbar in my SSH sessions that I could use to scroll back in the ssh buffer. Now the scrollbar is gone. I can still scroll back with SHIFT+PageUp/PageDown keys, so it can't be a change in the scroll buffer settings of putty.

## Expected Behavior
Show a vertical scroll bar again to navigate up/down in the buffer of a ssh session.

## Current Behavior
Scrolling in the ssh session buffer is only available via keys.

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
1. Open a SSH2 session with putty set to have a scroll buffer

## Your Environment
* Version used: 1.76.18.26260
* Operating System and version: Windows 10 Pro 1809 x64):

**Comment by kmscode** [comment] 2019-04-04 23:59
Duplicate of #1374 

Fixed in 1.76.19: https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.19

**Closed by kmscode** 2019-04-04 23:59 UTC
Labels: Duplicate, Fixed
