### ISSUE TITLE
mouse disappears when moving in to devices

### ISSUE THREAD

**Issue by pererap01** [mRemoteNG/mRemoteNG#1578] opened 2019-09-12 22:25 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment] 2019-09-24 06:42
Duplicate of #1579, closed for voidness.

**Closed by farosch** 2019-09-24 06:42 UTC
