### ISSUE TITLE
Feature Request: greyed window on disconnected Session

### ISSUE THREAD

**Issue by Pendora2017** [mRemoteNG/mRemoteNG#1616] opened 2019-10-08 10:35 UTC
I would like to have a better eye catcher for disconnected Sessions. 

## Current Behavior
Disconnected Session window tab has the same color scheme as connected one's

## Expected Behavior / Possible Solution
- maybe greyed Window or mouse cursor with reconnect symbol in it 
- the tab could change background color to red or something / maybe a disconnect symbol in front

## Your Environment
* Version used: 1.76.20.24669
* OS: Win10 Standard Theme

**Comment by farosch** [comment] 2019-10-09 21:54
Duplicate of #1444

**Closed by farosch** 2019-10-09 21:54 UTC
