### ISSUE TITLE
Random crashing with no error - Caused by Audio Drivers

### ISSUE THREAD

**Issue by LaurenceMillward** [mRemoteNG/mRemoteNG#1517] opened 2019-07-16 10:30 UTC
Heya,

I have mremoteng installed on multiple computers, however on one of them it randomly crashes with no error dialog box. Appears the app is calling C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\SS2OSD.dll which is causing it to crash. SS2 is Sonic Studio 2 and installed by default on certain machines. 

Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: SS2OSD.dll, version: 0.0.0.0, time stamp: 0x58ef9f08
Exception code: 0xc0000005
Fault offset: 0x00004562
Faulting process ID: 0x4064
Faulting application start time: 0x01d53bb5c7b114ad
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
**Faulting module path: C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\SS2OSD.dll**
Report ID: 3f649e92-b536-42e3-8bf7-75add4f72477
Faulting package full name: 
Faulting package-relative application ID: 

Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 6D844562

Looking at the report.wer it's calling 2 files from:
LoadedModule[31]=C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\SS2OSD.dll
LoadedModule[32]=C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\SS2DevProps.dll

**Comment by farosch** [comment] 2019-09-01 12:36
This is likely caused by `SS2Svc32.exe`. See: https://www.file.net/process/ss2svc32.exe.html
Does the problem disappear after killing the service?

**Comment by LaurenceMillward** [comment] 2019-09-01 12:40
Heya @farosch - Thanks for getting back. Yeah; I disabled "SVLoadSense" and "SS2UILauncher.exe" on startup (thus removing SS2Svc32.exe from ever starting) and the issue hasn't occurred since.

**Comment by farosch** [comment] 2019-09-01 12:51
Good to here. Thanks for answering this quickly. :)
I guess this is related to RDP making some calls to your sound card which in your case triggers some method in `SS2OSD.dll` and `SS2DevProps.dll` that fails.
Closing this as it is an upstream issue we unfortunately cannot do anything about.

**Closed by farosch** 2019-09-01 12:51 UTC
Labels: Vendor/Upstream Issue
