### ISSUE TITLE
the SQL configuration script is not suitable for the new software version

### ISSUE THREAD

**Issue by debug2000** [mRemoteNG/mRemoteNG#446] opened 2017-03-10 03:19 UTC
when I use the sql script in the help menu （F1） ， I found it is not suitable for the new software version.   

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 hf1  |

**Comment by sparerd** [comment] 2017-03-10 03:54
Closing as duplicate of #408. Subscribe to that issue for updates

**Closed by sparerd** 2017-03-10 03:54 UTC
