### ISSUE TITLE
Side panel text translating after move mouse on it

### ISSUE THREAD

**Issue by TheTitanrain** [mRemoteNG/mRemoteNG#981] opened 2018-05-23 23:56 UTC
After starting side panel in English language:
![image](https://user-images.githubusercontent.com/1952721/40457034-acb523e0-5f37-11e8-99d7-117ac6293a0b.png)
When i move the mouse on it Russian text appears:
![image](https://user-images.githubusercontent.com/1952721/40457076-d89cb7d4-5f37-11e8-9b26-7a300f504fe6.png)
In preferences Russian language selected:
![image](https://user-images.githubusercontent.com/1952721/40457164-549cafa6-5f38-11e8-85a4-4b10bd2a4dd5.png)

mremoteng 1.76.3.32942
Windows 10 last and previos versions. Russian.

**Comment by sparerd** [comment] 2018-12-26 21:47
I think #1238 is a duplicate of this issue, but I couldn't find this one initially. I've fixed part of this in #1238 and the other part will be fixed shortly. This should be available in v1.77.0

**Closed** 2018-12-26 22:01 UTC
Labels: Bug, UI/UX
