### ISSUE TITLE
SSH session does not scale up to fullscreen when TeamViewer QuickConnect is enabled

### ISSUE THREAD

**Issue by MichalLabuda** [mRemoteNG/mRemoteNG#623] opened 2017-06-28 21:56 UTC
When TeamViewer QuickConnect button is enabled, ssh sessions do not scale up to fullscreen and are stuck with default putty resolution (80 columns and 24 rows in my case).
mRemoteNG is run in portable mode.
TeamViewer is not installed, running in "Run only" mode.
|--:|---|
|Operating system | Windows 10 Enterprise x64 version 1703 |
|mRemoteNG version| 1.75.7008.17935 |
|PuTTy version| 0.69 64-bit |
|TeamViewer version| 12.0.78313 |

**Comment by stuartjmcgrath** [comment] 2017-06-30 00:02
I have the same issue and I have noticed if you toggle between full screen and windows. The next full screen is working.

**Comment by kmscode** [comment] 2017-07-05 16:56
duplicate of #297 

Please follow that issue report for further details...

Workaround seems to be to disable the quick connection feature of Team Viewer...

**Closed by kmscode** 2017-07-05 16:56 UTC
