### ISSUE TITLE
Can not import RDCMan v2.7 build 1406.0 rdg file

### ISSUE THREAD

**Issue by deathrush** [mRemoteNG/mRemoteNG#225] opened 2016-11-07 09:48 UTC
|||

2016-11-07 18:00:51,144 [1] ERROR- App.Import.ImportFromFile() failed:1
Unsupported schema version (3).
2016-11-07 18:00:51,150 [1] ERROR- App.Import.ImportFromFile() failed:2
Unable to cast object of type 'mRemoteNG.Tree.Root.RootNodeInfo' to type 'mRemoteNG.Container.ContainerInfo'.

|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74  |

**Comment by sbgillett** [comment] 2016-12-13 09:58
Is this not a bug?

**Comment by sparerd** [comment] 2016-12-13 15:00
mRemoteNG only ever had support for importing RDCMan v2.2 files. Supporting v2.7 imports would be a new feature.

**Comment by MoeSaidi** [comment] 2017-09-06 14:21
+1 for this; would be nice to be able to easily migrate from RDC Manager to mRemoteNG

**Comment by ThoHah** [comment] 2017-09-26 14:25
What is the status here?
This was a request in 2016...

**Comment by sparerd** [comment] 2017-11-10 01:22
This will be included in the next major release, v1.76

**Closed by sparerd** 2017-11-10 01:22 UTC
Labels: Enhancement
