### ISSUE TITLE
Allow embed Firefox to access SSL w/invalid certs in Remote Connection HTTPS

### ISSUE THREAD

**Issue by codedeep** [mRemoteNG/mRemoteNG#259] opened 2016-11-18 09:45 UTC
Hi

add new feature to mRemoteNG
Allow embed Firefox(GeckoFx) to access SSL w/invalid certs in Remote Connection HTTPS

Manual fix  to use your firefox exception SSL w/invalid certs:
Copy:
c:\users\%USERNAME%\AppData\Roaming\Mozilla\Firefox\Profiles\{RANDOM}\cert_override.txt
and place it here
c:\users\%USERNAME%\AppData\Local\Geckofx\DefaultProfile\cert_override.txt

Note: [https://developer.mozilla.org/en-US/docs/Cert_override.txt](https://developer.mozilla.org/en-US/docs/Cert_override.txt)

use |mRemoteNG version| 1.75 beta 1  |

**Comment by kmscode** [comment] 2017-03-09 03:35
@codedeep - closing this as a duplicate of #195 

Thanks so much for the workaround info. We're going to attempt to resolve this in 1.76 (but it may be pushed back to 1.77).

**Closed by kmscode** 2017-03-09 03:35 UTC
Labels: Feature Request, Help Wanted, High Priority, ready, Verified

**Comment by mircsicz** [comment] 2020-10-14 15:14
3 years later and this is still the only solution?

Here's how I did it in CMD.exe:

cd C:\Users\mirco\AppData\Local\Geckofx\DefaultProfile
mklink /H cert_override.txt C:\Users\%USERNAME%\AppData\Roaming\Mozilla\Firefox\Profile/RANDOM.default-esr\cert_override.txt
