### ISSUE TITLE
Collapse Settings not Saved

### ISSUE THREAD

**Issue by TehDuffman** [mRemoteNG/mRemoteNG#436] opened 2017-03-06 15:52 UTC
Previously I would collapse all folders prior to saving the connections file and upon reopening the folders would all be collapsed. If I left some expanded before saving those would still be expanded. Now no matter what when I open the connections file all of my folders are expanded. 

It may be better to put an option to open with all folders collapsed or expanded into the settings.

|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75   |

**Comment by kmscode** [comment] 2017-03-06 17:17
@TehDuffman - "previously" - could you narrow that down a bit? 1.74? 1.72? The huge change from 1.72 -> 1.74 was a C# conversion. From 1.74 ->1.75 the Connect Tree object type was changed. These are the 2 possibilities that I can see causing this type of a problem.

Thanks...

**Comment by TehDuffman** [comment] 2017-03-06 17:18
Running on 1.75 currently. I was running on 1.72 prior to new team taking over.

**Comment by TehDuffman** [comment] 2017-03-06 17:26
It looks like the Expanded="True"/Expanded="False" settings are not being saved currently.  If i change this setting manually it will start collapsed but I also noticed it moved that folder to the top of the current folder in MRemote but it is still in the same order in the actual connections file.

**Comment by kmscode** [comment] 2017-03-09 04:02
Tentatively scheduled for 1.76

**Comment by Totorman** [comment] 2017-03-13 15:49
I can confirm this behaviour is new in 1.75 and was working ok in 1.72.

I dont know if it is "this : expanded/not expanded" related or not but i've got hundred of servers in mRemoteNG in hundred of folders and subfolders.

The autorefresh is killing me :)
Every refresh time, all folders are redrawn and are open (expanded) :) and the screen part scrolls back to first part, so i need to reclose all folders very fast and scroll down to my customer folder ^^

**Comment by kmscode** [comment] 2017-03-14 23:44
I'm not able to reproduce this in the latest devlop branch.

I was also unable to reproduce it with [1.75.7001](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix1)

Could you please confirm that you are on the latest (non-pre) release?

**Comment by Totorman** [comment] 2017-03-15 10:02
Currently using Prerelease v1.75 Hotfix 3 Fri, Mar 10, 2017 which is only version since 1.72 who seems working with SQL Server.

**Comment by kmscode** [comment] 2017-03-15 13:32
@TehDuffman Are you using the SQL feature also?

**Comment by kmscode** [comment] 2017-03-15 15:06
I believe that I've found the problems with the SQL code and submitted a change to @sparerd who is working on other SQL related changed.

**Comment by TehDuffman** [comment] 2017-03-15 15:30
@kmscode I do not use SQL for my connections file. I can try to sanitize my file and send it over to you. Might not be till next week though

**Comment by kmscode** [comment] 2017-03-15 15:42
Thanks @TehDuffman. 
Please attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) as well.

**Comment by sparerd** [comment] 2018-02-04 23:29
I am not able to replicate the issues described here in either xml or sql based connections in the latest 1.76 alpha release. @TehDuffman @Totorman Would either of you be willing to verify this? https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76Alpha2

**Comment by Totorman** [comment] 2018-02-08 21:39
Seems ok for me

**Comment by sparerd** [comment] 2018-02-12 14:27
Thanks @Totorman. I'm closing out this issue, but if anyone has issues with this in the v1.76 builds please reopen

**Closed by sparerd** 2018-02-12 14:27 UTC
Labels: in progress
