### ISSUE TITLE
Single clicking on SSH in Connections Panel launches connection

### ISSUE THREAD

**Issue by Eldaw** [mRemoteNG/mRemoteNG#378] opened 2017-01-28 20:26 UTC
If I double-click on an SSH connection in the Connections panel to initiate a connection, and then immediately single click on a different SSH connection (with the intention of simply selecting it), a connection to that one is also initiated.

1.75 RC 1 on Windows 10

**Comment by kmscode** [comment] 2017-01-29 22:40
Reproduced.

**Comment by sparerd** [comment] 2017-01-30 17:21
Also able to confirm. The first click after activating an SSH connection seems to be viewed as a double click, but only within the tree. Double clicking an RDP connection then single clicking something does not have the same effect (treated correctly as a single click).

**Comment by sparerd** [comment] 2017-01-30 17:53
Uh... odd. Here's what i'm seeing:

1. Double click an ssh connection (single click executes, double click executes - this is expected)
2. Single click another ssh connection (double click executes)
3. Mouse over a treelist item (single click claims that it executes)

Step 2 is obviously wrong, but I also didn't expect step 3 to occur.

**Comment by sparerd** [comment] 2017-01-30 17:57
This feels like a bug in ObjectListView, since we're hooking into their CellClicked event. Will have to test with their source to confirm.

**Comment by sparerd** [comment] 2017-01-30 18:09
Re-implementing the same functionality using standard events does not produce the bug. This strongly points to ObjectListView as the cause.

**Comment by sparerd** [comment] 2017-01-30 18:39
Pushed the fix to the 1.75 RC branch. A fix will be included in the next release.

Thanks for the report!

**Closed by sparerd** 2017-01-30 18:39 UTC
Labels: Bug, High Priority, in progress, Verified
