### ISSUE TITLE
Connection Pane "whites out" on Connection Folder Minimization

### ISSUE THREAD

**Issue by jdix531** [mRemoteNG/mRemoteNG#779] opened 2017-11-07 15:51 UTC
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |
|Issue Description|Connections pane mostly whites out occasionally on collapsing a folder. This is reproducible with multiple different folders collapsing, or at least when using collapse all (connections pane -> view -> collapse all) menu the error occurs some times. |
|More Details|I think I found the key to triggering the issue, you must have enough connections in the folder you are expanding to fill the entire pane so that it resets the top of the pane to the top of the folder. You will see what I mean if: 1) You have several folders 2) The offending folder which will cause the visual glitch is not in the top of the list (not sure if this matters, but my test cases had it in the middle) 3) you start scrolled all the way to the top and/or with all folders collapsed 4) you expand the offending folder 5) the pane re-positions (and the offending folder is now at the top) upon expansion since (mentioned before steps listed as a prerequisite) there is enough connections to extend past the bottom of the pane 6) without doing anything else, immediately trying to minimize this offending folder results in the connections pane being whited out. 7) Beyond triggering the issue I have also noted that you can prevent or fix the issue by 7a) prevent by scrolling with mouse wheel or scroll bar before collapsing the folder a second time, it seems to trigger only if the first action is to minimize the folder which was just expanded and forced a reposition 7b) recover by selecting view -> expand all folders and scrolling down. This causes the mostly whited out pane which you can then scroll back up and collapse and expand the root connections node which then restores visibility to the whole pane. 9) see screenshots for a visual walk through of the issue being reproduced.|
|Screen Shots|https://imgur.com/a/fANeg|

**Comment by sparerd** [comment] 2017-11-07 16:15
Duplicate of #763, should be fixed with the next release which is coming shortly

**Closed** 2017-11-07 16:15 UTC
Labels: Bug, Duplicate

**Comment by jdix531** [comment] 2017-11-07 16:17
Thanks! Sorry I missed that this was a duplicate. I did a quick search but didn't see it :(

**Comment by sparerd** [comment] 2017-11-07 16:19
No problem! Better to have duplicates than no reports :)
