### ISSUE TITLE
What about a WPF UI

### ISSUE THREAD

**Issue by nazarenomanco** [mRemoteNG/mRemoteNG#1288] opened 2019-01-26 13:22 UTC
I'm a user of mRemote NG, and with the new display with wider resolution sometimes the UI do not "scale" very well. 
Do you think should be a good idea?

**Comment by kmscode** [comment] 2019-02-07 14:10
Scaling fixes are included included in the devlop branch and scheduled for 1.77 - WPF would be a re-write of all of our UIs and it not planned at the moment.

closing as duplicate of #321

**Closed by kmscode** 2019-02-07 14:10 UTC
