### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by cinquestl** [mRemoteNG/mRemoteNG#1445] opened 2019-05-09 16:07 UTC
## Current Behavior

<!--- ```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 802
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 802
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 802
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 152
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 152
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 152
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.17763.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args: 

```
 -->

## Possible Solution
<!--- Review code with trace -->

## Steps to Reproduce (for bugs)
<!--- Provide an unambiguous set of steps to reproduce -->
<!--- this bug. Include code to reproduce, if relevant -->
1. Open 2 or three connections. Mine were 1 RDP and 2 Web
2. Close each connection leaving empty tab
3. Close empty tab. Exception will trigger.

## Context
<!--- Once triggered, my only option was to click on Exit button which closed app. -->
<!--- This forced me to start app fresh. -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Windows 10 x64 10.0.17763, Dell OptiPlex 7040 1 processor, 8 Gigs memory, MRemoteNG version 1.77.0.41252

**Comment by cinquestl** [comment] 2019-05-09 17:00
Correction to the event. If you open up one, two, three connections then close the tab when connections are active, the bug will occur. Happens every time.

**Comment by sparerd** [comment] 2019-05-09 19:02
Couldn't replicate with RDP tabs - happens with web connections though.

**Comment by sparerd** [comment] 2019-05-09 19:03
```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ConnectionWindow.cs:line 802
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\ProtocolBase.cs:line 152
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.14393.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args: 

```

**Comment by sparerd** [comment] 2019-05-09 19:12
I'm thinking this is a timing issue. I can't replicate very often (really just once now out of a few dozen tries).

**Comment by sparerd** [comment] 2019-05-09 19:15
Now I'm thinking this is fixed in the develop branch. I have been able to replicate twice using the released version (1.77.0.41252) but haven't been able to replicate at all in the dev build. I'll look into this a bit more to make sure though.

**Comment by cinquestl** [comment] 2019-05-09 20:55
Do you have a date when you will push out another alpha? I am very willing
to test it out once released. For now, I know how to work around the issues
in alpha. Nothing earth shattering as far as I can tell. Just minor
function differences. You have a great product here. I definitely prefer it
over the MS RDCM.

**Comment by LeonvanHeerden** [comment] 2019-09-26 05:09
Using Version v1.77.1
I can simulate this issue by:
Open connection that has a Panel
Then closing the Panel while the Connection is still active. 
I use SSH connections most of the time.

Work Around:
Currently i try to make sure that I close each connection first before closing the Panel. 
Currently I am making sure that i close each

**Comment by farosch** [comment] 2019-10-03 21:17
I have been able to replicate this on the latest `develop` branch with the steps provided by @LeonvanHeerden 

```
Exception Message
"Cannot access a disposed object.
Object name: 'ConnectionWindow'."

Stack trace
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.UI.Window.ConnectionWindow.Prot_Event_Closed(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.ClosedEventHandler.Invoke(Object sender)
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Environment
OS: Microsoft Windows NT 10.0.18362.0
mRemoteNG Version: 1.77.1.27713
Edition: Portable
Cmd line args: 

```

**Comment by farosch** [comment] 2019-10-03 21:35
Duplicate of #1286

**Closed by farosch** 2019-10-03 21:35 UTC
Labels: Bug, Duplicate, Verified
