### ISSUE TITLE
The play icon in the Connections panel is small

### ISSUE THREAD

**Issue by oldhobbyist** [mRemoteNG/mRemoteNG#1155] opened 2018-10-26 10:14 UTC
The play icon in the Connections panel is small.

## Expected Behavior
Is there a way to use the old behavior that will completely change the icon to play icon when you are connected to that server?

## Current Behavior
At the moment when you connect to a server, the small play icon will overlay on the lower right part of the connection icon and can be hard to see.

## Possible Solution 
I don't have the solution :(

## Steps to Reproduce (for bugs)
1. Expand connection folder
2. Connection with the icon will show
3. Connect to the server
4. Small play icon will overlay on the connection icon

## Context
Some people including me can hardly see the icon. If there are a lot of opened connection the level of hardness will add up.

## Your Environment
* Version used: 1.76.11.40527
* Operating System and version: Windows 8.1

**Comment by sparerd** [comment] 2018-11-01 14:39
Duplicate of #1096, please follow that issue for more details

We are going to add a setting to switch between an overlay and a standalone icon for connection status

**Closed by sparerd** 2018-11-01 14:39 UTC
