### ISSUE TITLE
Passwords saved with special/international characters will not work

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#186] opened 2016-10-20 13:44 UTC
|  |  |
| --: | --- |
| Operating system | Windows 7 x64 |
| mRemoteNG version | 1.74 |

From @amoscatelli on gitter

I am having an issue when using password containing special characters like '£'
if I input them directly it works
if I insert them in the session configuration it won't work and it will say access denied
If I try to login on the same server with a different user with a password without that character it works

**Comment by kmscode** [comment] 2016-10-20 13:47
From [MR-704](https://mremoteng.atlassian.net/browse/MR-704):
I had some SSH passwords with the symbol ° but they are not passed correctly to the SSH session and I had to type the password manually. 

From [MR-621](https://mremoteng.atlassian.net/browse/MR-621):
saved SSH password containing umlaut will not work
When storing an SSH account's password that contains an umlaut, the automatic login would not work.

It is possible to successfully use it on the interactive login shell that appears after "Access denied".

**Comment by sparerd** [comment] 2016-10-25 17:43
I can confirm that it is not an issue with serialization or internal storage of the passwords in memory. My guess is the issue comes when attempting to pass the characters to PuTTY.

I wonder if this only occurs when attempting to SSH, or if other protocols have issues.

**Comment by sparerd** [comment] 2016-10-25 18:02
Live test shows that RDP is also affected

**Comment by sparerd** [comment] 2016-10-25 18:04
Verified the issue is still present in the current develop branch

**Comment by sparerd** [comment] 2016-10-25 18:44
RDP is actually not affected. I was using a character that was not supported by windows auth (┬).

SSH is still affected for standard international characters in the current build.

**Comment by sparerd** [comment] 2016-10-25 18:52
The cmdline args being passed to PuTTY are correct. I'm starting to think this is on PuTTY's side.

**Comment by sparerd** [comment] 2016-10-25 19:28
Based on packet captures performed during interactive login with putty v.067, I'm not confident that PuTTY is accepting the following characters:  £°úä

What is interesting, is that other users are saying interactive login is working for them, even with these special characters. More research is needed.

**Comment by sparerd** [comment] 2016-10-25 21:26
Finally got the PuTTYNG project to build. Slogging through the authentication code to figure out of there's some evidence to support my theory

**Comment by sparerd** [comment] 2016-10-27 19:55
Still not sure why this happens for higher order ascii characters, though I've traced it all the way through to where PuTTY sends the auth data to the remote server. The password was never corrupted at any point along the chain of custody (entry into mRemoteNG -> passing to PuTTY via cmdline -> PuTTY parsing it to send to server).

When capturing packets during session initiation, the following interesting thing happened:

The first authentication attempt using the -pw switch with PuTTY failed, though the data packet appears to have the correct ascii code (0xFA) for the higher order character i was testing (ú).

The second auth attempt (made with interactive keyboard) succeeded. However, this packet did not seem to send the expected ascii code for ú. It sent 0xC3 (Ã). Wat.

Attempting to substitute 0xFA with 0xC3 during -pw authentication also did not work. This was somewhat expected, but still very Wat.

**Comment by sparerd** [comment] 2016-10-27 20:04
The only difference I can find between the two situations (parameterized vs. interactive) is this:

*Interactive*
- password is prefixed with padding data value 0x10
- password is suffixed with padding value 0xba

*Parameterized*
- password is prefixed with data value 0x0f
- password has no suffix value

**Comment by sparerd** [comment] 2016-10-27 21:27
As much as I'd like to figure this out, it seems to be out of scope for mRemoteNG itself. There is no indication that mRemoteNG is doing anything to prevent proper handling of the password by PuTTY. In fact, this is looking like a bug in PuTTY itself (or maybe a character encoding issue between cmd.exe and PuTTY).

The best thing we can do to attempt to alleviate this issue is to provide a PuTTY replacement (such as SSH.NET, which is a planned feature).

I want to do a bit more research into this as a PuTTY bug and add a corresponding known-issue page on our Wiki so we don't have to re-explain the problem.

**Comment by koumdros** [comment] 2016-10-28 21:56
not sure if this is relative or whether I should open a separate issue, but i;m having a smilar issue while using WinSCP as an external application. appears with either password or passphrase if it contains special characters.... but not all of them. i can investigate more

**Comment by sparerd** [comment] 2016-10-30 13:30
@koumdros Would you be willing to provide the string of args you are passing to WinSCP? It may be related, or at least worth looking into.

**Comment by sparerd** [comment] 2016-11-04 17:59
Closing this issue as we will likely not be able to resolve the character encoding (besides providing a putty replacement). If more information is uncovered, we can reopen this ticket.

I've created a known-error record to document that this is a known issue. https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#ssh-login-fails-when-password-contains-extended-ascii-characters

**Closed** 2016-11-04 17:59 UTC
Labels: Bug, in progress, Medium Priority

**Comment by franzbar** [comment] 2016-11-14 08:19
the problem exists with RDP sessions. I have some pwd with the character "!" the PWD is stored as "^!"

**Comment by tsew2674** [comment] 2016-11-15 15:11
@franzbar I would guess that must be a regional setting in Windows.  We store exclamation points in RDP passwords frequently with no issue.

**Comment by sparerd** [comment] 2016-11-15 15:16
@franzbar if you are viewing the password with an external tool (such as %COMSPEC% /k %PASSWORD%) then cmdline metacharacters such as ! are escaped with ^. To not perform any escaping, use %!PASSWORD% as mentioned in https://github.com/mRemoteNG/mRemoteNG/wiki/External%20Tools

**Comment by trotack** [comment] 2019-07-11 03:59
> @franzbar if you are viewing the password with an external tool (such as %COMSPEC% /k %PASSWORD%) then cmdline metacharacters such as ! are escaped with ^. To not perform any escaping, use %!PASSWORD% as mentioned in https://github.com/mRemoteNG/mRemoteNG/wiki/External%20Tools

mark.thanks very much.

**Comment by L0g0ff** [comment] 2020-12-08 11:12
I have created a workaround for a password with a "!" character. Maybe it help somebody else (you need the WinSCP Beta for this ):

Filename: %COMSPEC%
Arguments: /c "C:\Program Files (x86)\WinSCP\WinSCP.exe" %Hostname% -username=%Username% -password=%password%

It's not the best workaround but it works for me :)
