### ISSUE TITLE
Post-login commands for SSH

### ISSUE THREAD

**Issue by dkirrane** [mRemoteNG/mRemoteNG#684] opened 2017-08-21 12:12 UTC
I'm moving from Multi Putty Session Manager which has an option to run up to 5 commands post login
Could this feature be added to mRemoteNG.

**Comment by sparerd** [comment] 2017-08-23 13:14
Yep! We do plan to add this at some point (pull requests welcome if you or someone you know can work on this).

Closing as duplicate of #503 - subscribe to that issue for further updates on this enhancement request

**Closed by sparerd** 2017-08-23 13:14 UTC
Labels: Duplicate
