### ISSUE TITLE
Cannot detect local printer

### ISSUE THREAD

**Issue by Guaje7** [mRemoteNG/mRemoteNG#1043] opened 2018-07-26 12:19 UTC
Cannot detect local printer

## Expected Behavior
Print some document from mRemoteNG to local printer.

## Current Behavior
When i launch my application throw mRemoteNG, i cannot use the functionnality "PRINT" because the local printer set by default on my Surface 4 Pro is not detected.

## Possible Solution
I've tried to use the functionnalities to redirect printer (see below) but it is not working.
![redirecting](https://user-images.githubusercontent.com/41740377/43261742-18bd8eec-90de-11e8-902e-e201195b157f.PNG)

## Your Environment
* Operating System and version - Windows 10 1709 x64 

Many Thanks 
Jonathan

**Comment by vb-03** [comment] 2019-06-20 01:37
I'm having this issue in 1.77.0, but in my case there's a twist: 
Only Microsoft PDF Printer redirect, non of others (actual) printers does. 
Using Windows 10 native client or RDO doesn't cause this issue.

Client:
Windows 10 Pro - 1803
Server:
Windows 10 Pro - 1903

**Comment by vb-03** [comment] 2019-06-20 13:19
It's #303, so we still have to wait to the RDP lib version switch to be implemented?

**Comment by sparerd** [comment] 2019-06-20 20:20
@vb-03 Yes, very likely. The good news is that most of the work is done to allow users to select the version of RDP to use.

**Comment by vb-03** [comment] 2019-09-08 17:55
So I tested the new version... it seems that the issue still persists. Now client is also on 1903.

**Comment by farosch** [comment] 2019-10-02 21:43
Duplicate of #303

**Closed by farosch** 2019-10-02 21:43 UTC
Labels: Bug, Duplicate, Verified
