### ISSUE TITLE
mouse resizes to host resolution on remote desktop (was MR-785 on JIRA)

### ISSUE THREAD

**Issue by jemiller226** [mRemoteNG/mRemoteNG#185] opened 2016-10-20 11:50 UTC
When using a large-resolution high DPI Windows 10 client (such as a Surface Pro) connecting to a Windows 7 host in full-screen mode, the mouse cursor is incredibly small while the rest of the display scales as expected.

See below for the [original bug's text](https://mremoteng.atlassian.net/browse/MR-785). That bug report was not mine, but the issue is similar enough that I'm copying it here for reference.

---

My laptop is 3200x1800 resolution, running windows 10, connecting to remote PC with openVPN and the remote PC is running windows 7 at 1080p. 

All works great except my mouse goes small on the remote server, the size if the resolution was 3200x1800 not 1080p. Everything is 1080p except the mouse. It makes it hard to see and work. 

Just wanted to know if you had any suggestions on what setting in your app or in windows to keep the mouse pointer the correct 1080p size?

|  |  |
| --: | --- |
| Operating system | Windows 10 x64 |
| mRemoteNG version | 1.74 |

**Comment by sparerd** [comment] 2016-12-01 21:14
Tried looking through the currently available RDP library options and couldn't find anything specific to DPI scaling. We will need to investigate further to see if anything can be done.

**Comment by milika** [comment] 2017-04-26 12:32
Still the same @1.75.7002.26467

**Comment by dhayner** [comment] 2017-06-01 21:16
I can confirm the same issue on 1.75.7000.19194.  Laptop is UHD, host is set to 1600x1200, and the pointer is tiny inside the session.

**Comment by idanmashaal** [comment] 2017-07-02 08:53
I'm writing this here and on https://github.com/mRemoteNG/mRemoteNG/issues/447
My laptop has a 1920x1080 display at 100% DPI (no scaling) - but Windows suggests 150% which is too big for my eyes.
I noticed the issue also in the menu options of mRemoteNG even when no connections are made.
This makes me think that the problem is not with the RDP library but with the widgets of mRemoteNG.
Inside an RDP session, I played with all options: "Smart Resize", "Auto Resize", "Fixed Resolution of all kinds" - all show the same result.
What fixed this for me was to change the scaling inside Windows 10 settings to the recommended 150%, sign off, then sign on, and then change it back to 100% which is my preferred.
Hope this helps.

**Comment by bhsmither** [comment] 2017-09-27 06:33
Slightly different: mouse cursor size is tiny in only that area of the mRemoteNG window where there is, or would be, the list of files and folders in an Explorer window - in that pane, and to the right of it, and below it. The mouse gets regular size outside this area and does not communicate with the remote desktop. (Connected at 1280x1024.)

Connect at Fullscreen seems to work.

**Comment by bhsmither** [comment] 2017-09-27 06:39
Actually, dropping out of fullscreen and trying to get back to fullscreen messes up everything.

**Comment by sparerd** [comment] 2018-10-30 12:33
I think this issue will be resolved with #321

**Comment by kmscode** [comment] 2019-03-09 21:26
Closing this issue since HiDPI was implemented via #321 

Feel free to reopen or open a new issue to report any other problems after 1.77 is released.

**Closed by kmscode** 2019-03-09 21:26 UTC
Labels: Bug, Help Wanted
