### ISSUE TITLE
The startup connection file could not be loaded

### ISSUE THREAD

**Issue by InViN** [mRemoteNG/mRemoteNG#421] opened 2017-03-01 17:40 UTC
Unable to actually launch the App. It worked the first time. I created a bunch of Connections in Folders. Closed the App, on a restart, I keep getting the following message:

The startup connection file could not be loaded.
C:\...\confCons.xml
Object reference not set to an instance of an object.

In order to prevent data loss, mRemoteNG will not exit.

I've tried re-installing as well as doing a clean install (uninstall-restart-install) - no luck. Same message every time. If I delete the confCons.xml file, the App will start up - display a notifications about not being able to create a backup of the connections file as well as not being able to create a new connections file with the same Object reference error as above. It then starts with a new connections file. If I quit & restart, or if I make any new connections & restart, I run into the same error again & am unable to start the App until I delete the XML file.

![image](https://cloud.githubusercontent.com/assets/3885804/23472809/ad987b98-fe73-11e6-9eae-7f110ba19ec4.png)

![image](https://cloud.githubusercontent.com/assets/3885804/23472826/bdcf4816-fe73-11e6-96f4-cdc75ea5c1b4.png)

![image](https://cloud.githubusercontent.com/assets/3885804/23472846/cbf80838-fe73-11e6-91d6-5052f9a64784.png)

|Operating system | Windows 7 Enterprise x64 - Service Pack 1 |
|mRemoteNG version| 1.74 -> Latest Stable from Download Site  |

**Comment by InViN** [comment] 2017-03-01 18:17
I got past the issue by uninstalling & then running a Registry Cleaner (CCleaner) to remove all traces of mRemoteNG. I've then re-installed the latest stable & am facing no issues as yet. (Though I do feel I shouldn't have to run a third-party registry cleaning software to completely uninstall mRemoteNG)

**Comment by ramiralez** [comment] 2017-04-10 09:55
same problem. try to delete "Sessions" folder. It is putty default config. Worked for me.

**Comment by ciptok** [comment] 2017-04-24 13:55
I encountered same problem but managed to solve it by using one of confCons.xml*backup files that existed in mRemoteNG folder. I can see multiple of those, I picked and renamed backup file with actual sessions data and it seems to work fine.

**Comment by kescha** [comment] 2017-05-18 16:22
Found the settings in C:\Users\USERNAME\AppData\Local\mRemoteNG\mRemoteNG.exe....\VERSION\user.config, change the setting there :)

**Comment by matt-richardson** [comment] 2017-08-08 01:36
I hit this, and after digging through the code, I found that [the code](https://github.com/mRemoteNG/mRemoteNG/blob/1c7592c70711f576ac237e985ac6e18d9d4ff261/mRemoteV1/App/Info/SettingsFileInfo.cs#L12) reads it (in most cases) from a file called `user.config` in either the `ExePath` if its the portable edition, or from `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\" + Application.ProductName`.

For me, this equated to `C:\Users\<username>\AppData\Local\mRemoteNG\mRemoteNG.exe_Url_goxdehxphl11a34i3a2thmpjprquaave\1.75.7008.17907\user.config`.

I edited that file to modify the `CustomConsPath` value, and I could launch again.

**Comment by luisfermoi** [comment] 2017-10-09 14:41
In my case, the file was missing the </Node> and </Connetions> tags. After I fixed it I noticed that I lose information and it was the reason for missing the TAGS.

**Comment by jackpoz** [comment] 2017-10-16 07:38
I would prefer mRemoteNG to let me select the correct file path instead of just closing and leaving me to google for the error (and luckily find this issue which allowed me to fix the error)

**Comment by sparerd** [comment] 2017-10-16 19:53
I agree, it isn't very user friendly

**Comment by Xhanti** [comment] 2017-10-30 15:05
This hit me as well. Its quite odd that not being able to find a config file makes the app unable to load.

**Comment by vkanimea** [comment] 2017-10-30 23:03
I didn't have this issue until a recent upgrade to 1.75.7010.21169 and followed matt-richardson suggestion.
Searched for file user.config in C drive, and choose the latest as there other older versions.
C:\Users\<username>\AppData\Local\mRemoteNG\mRemoteNG.exe_Url_pjpxdehxpaaorqg2thmuhl11a34i3ave\1.75.7010.21169
 
Edited CustomConsPath to the path of my lastest backup C:\Users\<username>\OneDrive\dat\mRemoteNG\conRemote.xml

<setting name="CustomConsPath" serializeAs="String">
                <value>C:\Users\<username>\OneDrive\dat\mRemoteNG\conRemote.xml</value>
          </setting

**Comment by sparerd** [comment] 2017-10-31 18:14
I'm going to tentatively schedule this for v1.76.

The goal will be to replace any "could not load startup file" dialogs with a "what would you like to do" dialog. Options would be:
- Create a new connection file
- Load a different connection file
- Exit

**Comment by sparerd** [comment] 2017-11-13 20:26
Some improvements were provided by @brucetp that should alleviate this issue. You will be able to choose what to do when a connection file cannot be loaded, rather than the app forcibly exiting.

**Closed by sparerd** 2017-11-13 20:26 UTC

**Comment by cnsgithub** [comment] 2018-01-16 07:01
Even when using the latest version 1.76 alpha the error still exists and can't open mRemoteNG even after deinstalling and reinstalling. The only solution is to re-create the missing folders and file

![image](https://user-images.githubusercontent.com/13161711/34975715-65d4f8f0-fa93-11e7-947a-23a228843afd.png)

**Comment by BlackbeardDaPirat** [comment] 2018-07-23 16:49
I got around this by replacing:

<setting name="LoadConsFromCustomLocation" serializeAs="String">
                <value>**True**</value>
            </setting>

with 

<setting name="LoadConsFromCustomLocation" serializeAs="String">
                <value>**False**</value>
            </setting>

**Comment by purpleSB** [comment] 2019-05-29 09:15
I am still having an issue with this. 
![image](https://user-images.githubusercontent.com/25940533/58545089-779b8a00-81fa-11e9-9526-ed362db4f787.png)

Same issue with the latest stable build and latest prerelease build. 1.76.20 and 1.77.0. I have tried uninstalling, using CCleaner, removing the mRemoteNG folder in AppData. Still no luck.

Any ideas how I can get this working? 

Thank you.

**Comment by steenstra** [comment] 2019-10-25 06:34
The issue is not resolved yet, I'm having the same problem.

**Comment by KleberMuniz** [comment] 2019-11-29 13:20
Follow matt-richardson or vkanimea suggestion sugestions above first. 
If did not help, rename file user.config to let's say user.config.old. Next time you open NG it will create a new one.

**Comment by prasanna-sk** [comment] 2020-01-22 18:48
I got the same error. 

I just renamed the `confCons.xml` to `confCons.xml_old` and renamed one of the backups `confCons.xml.20200122-1001569424.backup` to `confCons.xml`. This worked for me.

**Comment by gacpac** [comment] 2020-04-02 04:22
I was using MySQL for synchronization. I disabled it to load a local configuration, but after that it won't load the startup configuration.

![image](https://user-images.githubusercontent.com/47924627/78210312-c992e900-7477-11ea-8a8c-061d37f86ef3.png)

I'm using the latest version v1.77.1 pre-release, and have tried everything from uninstalling and cleaning registry. The error won't go away, I'm willing to fix it, if someone tells me where the settings file is. I deleted everything to have a fresh install

**Comment by thefactor82** [comment] 2020-05-04 11:05
Same issue here. And I cannot find a way to let it start normally...
Some advice please?

**Comment by christophmue2** [comment] 2020-06-10 05:24
as described above, look for: "%localappdata%\mRemoteNG\mRemoteNG.exe_Url_pjpxdehxpaaorqg2thmuhl11a34i3ave\1.76.20.24615\user.config"
Edit file, search for "LoadConsFromCustomLocation", set from "True" to "False", then you'll get the dialog to set a new conffile. worked for me (I'm also using sql).
but in fact a really annoying issue!

**Comment by iamsyl** [comment] 2022-01-12 18:30
> as described above, look for: "%localappdata%\mRemoteNG\mRemoteNG.exe_Url_pjpxdehxpaaorqg2thmuhl11a34i3ave\1.76.20.24615\user.config" Edit file, search for "LoadConsFromCustomLocation", set from "True" to "False", then you'll get the dialog to set a new conffile. worked for me (I'm also using sql). but in fact a really annoying issue!

This resolved the issue for me

**Comment by rebormio** [comment] 2024-08-15 05:11
1 create new xml conf file from program menu. 
2 look to your confCons.xml file, witch you wanna to transfer
![image](https://github.com/user-attachments/assets/abd467e9-a4e7-4e99-836e-5e1908c8d6bc)
3 Setup mRemoteng in options/security the same
![image](https://github.com/user-attachments/assets/fb3fed8e-356f-42f4-8af2-b4c1d2f67b2c)

**Comment by rebormio** [comment] 2024-08-15 05:13
also this may help when :
reopening the application results in a blank connections page and an empty confCons.xml file (not 0 bytes but empty of user config)
