### ISSUE TITLE
Random crash on opening new connection

### ISSUE THREAD

**Issue by g3m1n1-usa** [mRemoteNG/mRemoteNG#1103] opened 2018-09-14 22:06 UTC
I cannot reproduce this at will but it happens at least once per day. I'll have 1, 2, maybe 4 or more RDP sessions active and if I double-click a connection entry to open it I will randomly get a full crash of mremoteng.exe.

## Expected Behavior
Double-click a connection entry and it opens without crashing the application.

## Current Behavior
Random application crash when trying to open a new RDP connection.

## Steps to Reproduce (for bugs)
Unable to reproduce at will, the crash happens randomly but always when I have at least one active RDP session open. The event log error is always the same.

Faulting application name: mRemoteNG.exe, version: 1.76.8.17254, time stamp: 0x5b81772e
Faulting module name: Windows.UI.XamlHost.dll, version: 10.0.17134.191, time stamp: 0x5451dff6
Exception code: 0xc0000409
Fault offset: 0x000058cf
Faulting process id: 0x2148
Faulting application start time: 0x01d44bb5b9df6974
Faulting application path: C:\Users\<user>\Work\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\Windows\System32\Windows.UI.XamlHost.dll
Report Id: 868ffd42-4181-4bd0-8b61-3bbcfc856bee
Faulting package full name: 
Faulting package-relative application ID: 

## Your Environment
Windows 10 v1803 x64
Intel HD Graphics 4000 video

**Comment by sparerd** [comment] 2018-09-20 19:19
I think this is a duplicate of #853

**Closed** 2018-09-30 14:54 UTC
Labels: Bug, Duplicate
