### ISSUE TITLE
Can't control confCons.xml backups

### ISSUE THREAD

**Issue by msmigiel** [mRemoteNG/mRemoteNG#892] opened 2018-02-21 18:28 UTC
After using this program for a while, I noticed in the program directory, there were lots of backups for the confCons.xml file. I don't see a way to turn this off or control how many backup files to create. 

These backups seem to happen every time I start the program and they can quickly get overwhelming in numbers. I would have thought a backup would only happen if there was a configuration change, not simply just starting the program.

Please add the option to not only control the number of backup files to keep but to disable the backing up entirely. Please also consider making the backup only happen (if desired) when the configuration changes and not just during startup when nothing has changed.

**Comment by sparerd** [comment] 2018-07-23 17:48
This is partly due to bug #1020. We were not correctly honoring the `BackupFileKeepCount` setting (default is 10). That should be fixed in the next v1.76 release.

The request for configuring backup options is a duplicate of #474. Please follow that issue for further updates.

**Closed by sparerd** 2018-07-23 17:48 UTC
Labels: Duplicate, Enhancement
