### ISSUE TITLE
Mouse pointer disappeared in SQL Server management studio

### ISSUE THREAD

**Issue by ajaychary** [mRemoteNG/mRemoteNG#1350] opened 2019-03-14 15:37 UTC
i am unable to se the mouse pointer when connecting to SSMS. but i can see if i do RDP locallyt. by using remoteNG i cant.

**Comment by sparerd** [comment] 2019-03-14 19:35
This is likely the same issue as #532. This will likely be solved by the HiDPI fixes we implemented in v1.77

**Comment by farosch** [comment] 2019-10-02 22:02
Duplicate of #532

**Closed by farosch** 2019-10-02 22:02 UTC
Labels: Bug, Duplicate, Verified
