### ISSUE TITLE
putty window not maximized after update to v1.76.10

### ISSUE THREAD

**Issue by Brandhor** [mRemoteNG/mRemoteNG#1136] opened 2018-10-10 15:13 UTC
## Expected Behavior
with v1.75.7012 the putty window was maximized like this
![](https://i.imgur.com/GaMwq5I.png)

## Current Behavior
with v1.76.10 instead I can see the borders
![](https://i.imgur.com/u91yYRV.png)
and I can even drag it out to see the full window
![](https://i.imgur.com/sb0FjRR.png)

## Steps to Reproduce (for bugs)
1. just open any ssh connection

## Your Environment
* Version used: 1.76.10
* Operating System and version Windows 10 1809 x64, Windows 10 1803 x64

**Comment by cybrwshl** [comment] 2018-10-11 13:03
same thing here with Windows 7

**Comment by mjmooney** [comment] 2018-10-12 01:55
Same here. Note that due to this issue, and the spacing at edges, it's quite difficult to resize panels properly, as the edge seems to line up with the internal putty window most of the time, and it becomes very tedious to ensure that the right resize anchor is selected. 

Large impact on usability and feel, and this is regarding a system (panel UI) that I've always had issues/difficulty with, but this is too much of a regression and obstacle to put up with.  If you need more info, happy to help.

Thank you for your efforts! It's great to see so many other issues and features introduced or cleaned up. 

v1.76.10  - Windows 10 1803 x64

**Comment by olfolfolf** [comment] 2018-10-12 06:55
I have the same issue.

v1.76.10 - Windows 10 1709 x64

**Comment by sparerd** [comment] 2018-10-17 22:49
Looks like this was due to the switch from targeting .NET 4.0 to 4.6.

For some reason we now need to account for `SystemInformation.HorizontalResizeBorderThickness` and `SystemInformation.VerticalResizeBorderThickness` when resizing the putty window. They must have split the `SystemInformation.FrameBorderSize.Width` and `SystemInformation.FrameBorderSize.Height` properties to add these new measurements.

I've committed a fix for this

**Closed** 2018-10-18 22:05 UTC
Labels: Bug
