### ISSUE TITLE
Feature Request - Shortcuts for switching between tabs and panels

### ISSUE THREAD

**Issue by Shev84** [mRemoteNG/mRemoteNG#817] opened 2017-11-23 20:20 UTC
I can't believe that such app as mRemoteNG doesn't have shorcuts for switching between tabs and panels. It should be corrected in some future versions.
I.e.:
CTRL + TAB - switch to the next tab (to the right from current or to the first)
CTRL + SHIFT + TAB - switch to the previous tab (to the left from current or to the last)

ALT + PGUP - switch to the next panel (to the right from current or to the first)
ALT + PGDOWN - switch to the previous panel (to the left from current or to the last)

It would be even nicer if we could specify our own keys for such shortcuts. 

There could be also some shortcut for focusing cursor in current tab.

**Comment by sgordiienko** [comment] 2017-12-05 13:05
+1 from my side. This is really good idea.  Let me suggest ad-don to this feature - switching between tabs using [ALT] + [Number of tab in the panel] or [CRL]+[Number of tab in the panel].  It would be good to have this option.

**Comment by sparerd** [comment] 2017-12-05 13:49
Duplicate of #196 
Follow that issue for future updates

**Closed by sparerd** 2017-12-05 13:49 UTC
Labels: Duplicate
