### ISSUE TITLE
 terminal services with tslicense do not connect to SAP APP

### ISSUE THREAD

**Issue by TelesAlexandre** [mRemoteNG/mRemoteNG#1788] opened 2020-06-11 21:06 UTC
Terminal Service with Tslicense does not connect the SAP application

## Expected behavior
RDP is used for connection to the Desktop.
TS is also used for a specific application.
The TS should connect to the Application where it would present the application access in a tab.

## Current behavior
! [image] (https://user-images.githubusercontent.com/66802759/84438668-504d0a80-ac0d-11ea-832b-1864cd16fe44.png)
! [13] (https://user-images.githubusercontent.com/66802759/84439022-dcf7c880-ac0d-11ea-8ebc-4d04b822fa6f.png)
! [12] (https://user-images.githubusercontent.com/66802759/84439050-e5e89a00-ac0d-11ea-85dc-ec8b6f45b6c4.png)

* Version used: 1.76.20.24615
* Windows 10 x64 operating system and version

**Comment by farosch** [comment] 2020-06-11 22:37
Duplicate of #327

**Closed by farosch** 2020-06-11 22:37 UTC
