### ISSUE TITLE
Mouse cursor (text select) disappearing in text boxes

### ISSUE THREAD

**Issue by jupsoleil** [mRemoteNG/mRemoteNG#532] opened 2017-05-02 09:12 UTC
Hello, since a short while, (maybe creators update?), when using RDP in mRemoteNG, my mouse cursor disappears in text boxes, eg:
* the edit box of Notepad++
* the search box of Firefox, or the URL box of Firefox
* the search box of the Windows start menu...
Any clue what might be wrong?  When using windows' built-in RDP, the problem is not there :( .  I must say I have been happily using your mRemoteNG daily for many years already, and this problem is rather annoying as you surely understand :) .  Thanks for your effort!!

|||
|--:|---|
|Operating system | Windows 10 x64 Creators update |
|mRemoteNG version| 1.75.7005.28249 (hotfix 5)  |

**Comment by jupsoleil** [comment] 2017-05-02 11:27
((I cannot label this as a bug as requested in this project's guideline; is it a permission issue?))

**Comment by sparerd** [comment] 2017-05-02 13:52
Thanks for the report @jupsoleil 

Hmm - yes it might be a permissions issue. If so, we should remove the line about tagging your own issue tickets with bug/request. Thanks for bringing that up as well

**Comment by jupsoleil** [comment] 2017-05-04 07:28
Interesting: the bug is only visible on an external monitor.  I have an HDMI display (connector on motherboard of my laptop) and a DVI via my USB3 dock.  On both external displays the mouse cursor disappears as described.  Only when using mRemoteNG.  I had the problem with the normal release; I installed two alphas thinking it might be fixed but till now not fixed.

**Comment by MaikvanderGaag** [comment] 2017-06-12 12:57
I have the exact same problem:

Windows 10 Pro, mRemoteNG version: 1.75.7000.19194

I have this issue when working on my laptop screen and not on a external monitor. This makes it really hard when connecting to developing machines with Visual Studio on it.

**Comment by difa1012** [comment] 2017-06-21 08:22
Same thing here (1.75.7008.17907).
It is really hard to work when your cursor(Text Select) is gone.
Btw. the Text Select is not completely gone its is just 3 or 4 pixels big, so it is really hard to see on a high resolution.

**Comment by sunnyjayjay** [comment] 2017-07-10 09:43
I have the same problem. Anyone found a fix?

**Comment by Spankachu** [comment] 2017-07-27 20:51
Exactly the same issue, is there a fix or workaround?

**Comment by Spankachu** [comment] 2017-07-27 22:14
I may have found a workaround (works for me).  I'm connecting to windows server 2012 machines, but I expect this is the same as on Windows 10.

Go to Ease of Access -> Mouse, and set Pointer Color option to Black (the middle of the three options).  After doing so the I-Beam appears as it should.

@jupsoleil @MaikvanderGaag @sunnyjayjay @difa1012 @sparerd

**Comment by sparerd** [comment] 2017-07-27 23:07
Thanks for sharing your workaround @Spankachu!

**Comment by jupsoleil** [comment] 2017-08-07 12:22
@Spankachu thanks, indeed, it works, but this doesn't fix the bug causing this, and many of the rdp sessions I use are on systems where I shouldn't change mouse cursors permanently or the users will not be happy...  
@sparerd you have no idea on what the root cause is of this problem?

**Comment by maikvandergaag** [comment] 2017-10-31 10:56
Work around is not working for me. I experience the same problem when using the Microsoft Remote Desktop Connection Manager. Is there any solution for this?

**Comment by GMartinez-Sisti** [comment] 2017-10-31 11:03
I believe this is not an mRemoteNG issue, but instead (another) Windows scaling issue. This only happens when I'm using an external monitor attached to a higher resolution laptop. If you try RDP outside of mRemoteNG the issue is also there.

Examples:
- XPS 13 4k Screen with HD external monitor
- Surface Pro 3 with HD external monitor

**Comment by maikvandergaag** [comment] 2017-10-31 11:06
I do not have the issue when using the build-in RDP tooling. Besides that I have the problem on external monitor en laptop monitor.

**Comment by vtintillier** [comment] 2018-06-19 08:34
I have the same issue with Remote Desktop Connection Manager (works on 4K laptop monitor but not standard external monitor). I also confirm this works fine when connecting directly using Remote Desktop Connection instead.

**Comment by carmamir** [comment] 2018-09-02 14:27
Exactly the same issue. Worked fine and now after ~ 2 months of using NGRemote mouse cursor is disappearing in text boxes.

Changing colour of a pointer is not a solution as RDP is working fine, so clearly mRemoteNG needs a fix ASAP

**Comment by chloverdose** [comment] 2018-09-22 15:42
Still happening here, Surface Pro (200% scaling) on an external monitor (100% scaling)

**Comment by phattch** [comment] 2019-01-13 09:30
Hello,
I am using Mremote 1.76 and since I have a new Dell with DPI my Mremote does not work well.
My laptop is windows 10, I RDP a windows 2012 SR as jumpbox and from there the mouse is tiny.
Also if  from the RDP I SSH a linux with Putty, the mouse inside the putty disappear so  I cant use anymore MremoteNg ...
I sed the trck to change the color of the mouse in black but then I need to change all my putty session as the background is black and the mouse is black so useless.

Do we know when we gonna release and fix that in Mremote ?
I heard 1.77 ?

Thanks
Paul

**Comment by sparerd** [comment] 2019-01-14 13:10
Unfortunately no, we don't know when the next version will be released.

**Comment by castnightlybuild** [comment] 2019-10-15 09:54
I had the same problem. Perhaps you are using the same connection using mremoteNG and Windows Remote Connection ?
or you have used windows remote connection after that mremoteNG ? in this case, you should restart you computer and use only mremoteNG 
It's like that that I resolved the problem _in my case._

**Comment by farosch** [comment] 2020-06-13 09:31
Is this still happening with the latest Windows update and the latest mRemoteNG prerelease?

**Comment by farosch** [comment] 2020-06-13 09:47
Also, this just might be something we will have to live with:
https://support.microsoft.com/en-us/help/3025083/windows-scaling-issues-for-high-dpi-devices

**Comment by farosch** [comment] 2021-12-14 19:09
Closing this as this conversation seems stale and OP is not responding.
This issue was reported for v1.75 anyway and is most likely already solved.

If this issue still exists for anyone, please file a new issue.

**Closed by farosch** 2021-12-14 19:09 UTC
Labels: Bug, HighDPI
