### ISSUE TITLE
Alternative COLLATE SQL Server

### ISSUE THREAD

**Issue by jtsagara** [mRemoteNG/mRemoteNG#795] opened 2017-11-10 12:14 UTC
It will be good to remove the COLLATE SQL_Latin1_General_CP1_CI_AS  from the creation scripts of the tables regarding the SQL Server

This will create the tables with the default collate of the SQL Server and then the software is able to store also other languages than English in the connections tree (group or host)

In order to set descriptions in Greek we removed the COLLATE SQL_Latin1_General_CP1_CI_AS from the creation scripts.

![untitled](https://user-images.githubusercontent.com/33546769/32658196-817857c4-c621-11e7-94c3-665a53e089fe.png)

**Comment by sparerd** [comment] 2017-11-10 13:29
Duplicate of #419, but thank you for reminding me to get this changed. I'll update the documentation shortly

**Comment by sparerd** [comment] 2017-11-10 14:14
Script has been updated. All `COLLATE SQL_Latin1_General_CP1_CI_AS` have been removed

**Closed by sparerd** 2017-11-10 14:14 UTC
Labels: Duplicate
