### ISSUE TITLE
Critical Bug: Passwords are saved in plain text in SQL Database

### ISSUE THREAD

**Issue by pthoelken** [mRemoteNG/mRemoteNG#1140] opened 2018-10-11 08:52 UTC
Hey All, 

I'm absolutely shocked about the fact, that your software are saved the connection passwords in plain text in the database. 

![image](https://user-images.githubusercontent.com/12643853/46792455-b0f2b880-cd43-11e8-922e-0acf7133dc6c.png)

So you can do it! The passwords for connections in confCons.xml are also encrypted. Do it in SQL Database too, please! 

Best rgds
Patrick

**Comment by Phiph** [comment] 2018-10-11 15:39
1. You need to be connected to the SQL database directly
2. Its experimental so I don't think the current form is considered final. 
3. If you know what you're doing in SQL you can hide the columns from SSMS.

**Comment by pthoelken** [comment] 2018-10-11 15:43
wow. nvm #closed

**Comment by aglasson** [comment] 2018-10-22 23:39
Why would passwords be stored in the database? In any environment that users would connect to a central database under no circumstances should users be connecting with shared credentials. Credentials should be local to the user connecting so even with SQL should still be a local connection store file or preferably the Windows Credential Manager.

**Comment by pthoelken** [comment] 2018-10-23 06:15
mRemoteNG saves their saved connection passwords (for ssh, rdp or other) in plain text, when you use the MSSQL connection for configuration saving. If you want to save the connection bookmarks locally, the passwords are encrypted. 

So I ask me, why mRemote encrypt the local saved configuration files, but not the stored passwords in the database. This is fucking basic programming stuff. 

For Repo: 

1. Setup your mRemoteNG for saving your bookmarks in MSSQL (Create Table, setup connection settings, etc)
2. Go into your MSSQL Database (via MSSMS or other) and navigate to your password. 
3. You can see, that the connection password is stored in plaintext in the database.

**Comment by sparerd** [comment] 2018-11-04 22:18
Closing as duplicate of #449

**Closed by sparerd** 2018-11-04 22:18 UTC
