### ISSUE TITLE
Quick connection bar freeze

### ISSUE THREAD

**Issue by drocca69** [mRemoteNG/mRemoteNG#393] opened 2017-02-07 14:13 UTC
To reproduce this issue:
- Connect to any server (SSH2) using quick connection top bar
- Enter some commands (or just focus) on the server
- Click again on quick connection bar: the bar is now frozen, no text can be entered.

Workaround: to unlock the bar, just click into the left panel (servers list), then into the bar.
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 RC1  |

**Comment by sparerd** [comment] 2017-02-07 14:27
Duplicate of #268 

@drocca69 Feel free to subscribe to notifications for that ticket to receive updates for this issue.

**Closed by sparerd** 2017-02-07 14:27 UTC
