### ISSUE TITLE
Status indicator

### ISSUE THREAD

**Issue by rerun01** [mRemoteNG/mRemoteNG#1545] opened 2019-08-23 18:14 UTC
I would like a way to see the status of all my workstations before clicking on them. 
## Expected Behavior

a status light next to the work station on the connections window
## Current Behavior

Can only see status light after clicking each workstation
## Possible Solution

Maybe have a status light by each work station that is red or green if its online or offline
## Steps to Reproduce (for bugs)

1.see current status light 
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Windows 10 1903

**Comment by farosch** [comment] 2019-08-30 10:40
Duplicate of #1109

**Closed by farosch** 2019-08-30 10:40 UTC
Labels: Duplicate
