### ISSUE TITLE
Mouse Pointer is too tiny in my remote desktops

### ISSUE THREAD

**Issue by kumsi** [mRemoteNG/mRemoteNG#447] opened 2017-03-10 14:41 UTC
For some reason when i connect to the remote desktops using mRemoteNG, the mouse pointer is too tiny. I tried to look at the settings but nothing is helpful. Any body has the same issue? How to resolve it?

**Comment by kmscode** [comment] 2017-03-17 19:08
Are you using RDP or VNC connections? 

Are you using the smartsize option?

Taking a screen shot wouldn't necessarily help at all since the cursor is generally hidden when using prtscn, however if you're able to some how record the screen, that might be helpful to show the problem.

**Comment by idanmashaal** [comment] 2017-07-02 08:53
I'm writing this here and on https://github.com/mRemoteNG/mRemoteNG/issues/185
My laptop has a 1920x1080 display at 100% DPI (no scaling) - but Windows suggests 150% which is too big for my eyes.
I noticed the issue also in the menu options of mRemoteNG even when no connections are made.
This makes me think that the problem is not with the RDP library but with the widgets of mRemoteNG.
Inside an RDP session, I played with all options: "Smart Resize", "Auto Resize", "Fixed Resolution of all kinds" - all show the same result.
What fixed this for me was to change the scaling inside Windows 10 settings to the recommended 150%, sign off, then sign on, and then change it back to 100% which is my preferred.
Hope this helps.

**Comment by angeljharrison1** [comment] 2017-07-16 11:51
Same problem as @idanmashaal mentioned, thank you changing scaling settings solved my problem.

Please find attached screenshots.

![mremoteng_2017-07-16_14-06-39](https://user-images.githubusercontent.com/25013837/28247276-f21b6e8c-6a35-11e7-852a-7b94a443b51d.png)
![mstsc_2017-07-16_14-08-47](https://user-images.githubusercontent.com/25013837/28247278-f57996a8-6a35-11e7-99b3-3d9573e95d92.png)

**Comment by idanmashaal** [comment] 2017-07-16 16:49
I'm glad it works for you @angeljharrison1 :)

**Comment by ameymulay** [comment] 2017-12-07 05:25
Thank you idanmashaal !
Worked like a charm.

Regards,
AMEY

**Comment by kmscode** [comment] 2019-03-10 02:00
This is expected to be fixed in 1.77 which has HiDPI support. Currently in the develop branch, Alpha release expected soon. Closing.

**Closed by kmscode** 2019-03-10 02:00 UTC

**Comment by filmor** [comment] 2019-09-18 22:28
This is not fixed in 1.77.

**Comment by jdkang** [comment] 2021-06-06 19:30
Seconding @filmor that this is still an issue.

**Comment by kumsik** [comment] 2021-06-07 19:11
@filmor Yes. I am still experiencing the same issue.

**Comment by PerryCodes** [comment] 2024-01-09 04:43
Why are these mouse size issues all being closed?  This is still a problem.
