### ISSUE TITLE
SSH connections only display top half of full screen

### ISSUE THREAD

**Issue by kiweegie** [mRemoteNG/mRemoteNG#297] opened 2016-12-06 14:04 UTC
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74.6023.15437  |

On previous version and this latest version opening SSH connections to Linux servers only shows text in top half of a regular mremoteng window. i.e. text shows half way down the screen then the bottom half is completely blank. 

A workaround exists by going into full screen then back again (view > fullscreen or F11) however this does not "stick" and needs to applied for each tab or session. 

Only affects SSH (version 2, not tried with v1) connections, VNC, http and RDP all show correctly. Also happens with only one tab (SSH) open at a time so not being impacted by other connections.

I've also tried connecting to another panel but the problem persists. Another user has logged this on the mremoteng forum here: http://forum.mremoteng.org/viewtopic.php?f=3&t=3299 which includes screenshots. 

regards Kiweegie.

**Comment by sparerd** [comment] 2016-12-06 15:55
I think we found a sort-of-fix for this relating to PuTTY settings. I'll try to dig up that conversation...

**Comment by jumoog** [comment] 2016-12-07 10:07
the main problem is that we launch PuTTY as own process and show it in the TAB.. but as long we using PuTTY we can't do much

**Comment by archongtv** [comment] 2017-02-08 12:33
I'm having the same issue. When I was using 1.73 version it scaled good. If I attach normal putty.exe it upscales font size.

**Comment by JoeFenlon** [comment] 2017-02-10 11:23
I fixed this by downloading PuTTY separately and moving that putty.exe from C:\Program Files (x86)\PuTTY (Or wherever you decide to install it) and then put it in the mRemoteNG directory and replace the PuTTYNG.exe there. (C:\Program Files (x86)\mRemoteNG)

**Comment by archongtv** [comment] 2017-02-11 11:00
Hmm it works, but font is upscaled as I use display scalling. Any ideas on that?

**Comment by kmscode** [comment] 2017-03-17 18:14
Details and Screenshots from https://mremoteng.atlassian.net/browse/MR-987
>When I open an SSH session, the screen is only 25% of what it should be. I need to minimize/maximize mremote to correct that. 
>
>I've found out it's the putty windows size (lines, cols). It starts to small. I've changed the setting in putty to a larger default which helped for now. After resizing putty automatically changes the lines/cols

![after_minimize](https://cloud.githubusercontent.com/assets/16654335/24056928/de5ba3f4-0b1b-11e7-902a-433ce42a899a.PNG)
![before_minimize](https://cloud.githubusercontent.com/assets/16654335/24056927/de5b690c-0b1b-11e7-9ad4-1e585d32df90.PNG)

**Comment by daftu** [comment] 2017-06-30 11:28
Same issue here. Any new SSH connection shows in about 25% of "black" window. Resizing mRemoteNG main window (or exiting Full Screen and entering it again) fixes problem in current session, but any new session opens in 25% console window.
Windows 10, mRemoteNG 1.75.7008.17907 (but also in any previous releases).

**Comment by archongtv** [comment] 2017-06-30 11:36
I found what was the problem in my case - Team Viewer in background.

**Comment by daftu** [comment] 2017-06-30 11:38
You're totally right! Thanks!
Disabling TeamViewer window sharing on mRemoteNG solved the problem!

**Comment by kmscode** [comment] 2017-07-05 17:00
@archongtv great catch... If you you notice in [my comment here](https://github.com/mRemoteNG/mRemoteNG/issues/297#issuecomment-287431706) the screenshots show the Team Viewer quick connection/share option in the title bar... This was also reported in #623.

It seems unlikely that we'll be able to do too much about this bug since MR is integrating the separate PuTTYNG process into its tab/window. I would assume that TV is attempting to stick it's icon on the PuTTYNG title bar as well (which is effectively hidden when opened via MR).

**Comment by epigns** [comment] 2018-10-26 07:47
Teamviewer in my case too. Thanks !

**Comment by kmscode** [comment] 2019-03-10 01:33
Being as this is not reproduceble (even when testing with TV) and some other PuTTYNG related windowing and overall tabbing changes included in 1.77, I'll be closing this one out...

**Closed by kmscode** 2019-03-10 01:33 UTC
Labels: Cannot Reproduce, UI/UX
