### ISSUE TITLE
"Send to All" for ssh/telnet

### ISSUE THREAD

**Issue by msmigiel** [mRemoteNG/mRemoteNG#881] opened 2018-02-05 23:42 UTC
It would be very handy to have the option to send the same command to all open ssh/telnet sessions. In my opinion, the best way to implement this would be as follows.

1.) Have a customizable hotkey to bring open a one line text box at the bottom of the program (for example, ALT+S).
2.) Hitting this hotkey would then focus on the text box, to which a user could type a command to run on all open ssh and telnet sessions.
3.) Clicking on the tabs (or ideally, from my other feature request, ALT+# to open a tab) would bring the focus to that ssh/telnet window to type commands.
4.) The customizable hotkey would open the one line text box and bring focus to it and would also be able to close it once done.

**Comment by sparerd** [comment] 2018-02-06 13:38
Duplicate of #611. This feature is available in the current v1.76 alpha release.

**Closed by sparerd** 2018-02-06 13:38 UTC
Labels: Duplicate
