### ISSUE TITLE
UI: Wrong connection information shown in "Config" after switching between "Properties" and "Inheritance"

### ISSUE THREAD

**Issue by bluikko** [mRemoteNG/mRemoteNG#1080] opened 2018-08-22 09:44 UTC
Wrong host is displayed in "Config" sidebar after switching from "Properties" to "Inheritance" and then back to Properties.

## Expected Behavior
* Switching back to "Properties" from "Inheritance" shows the information of the selected connection. Not some other connection.

## Current Behavior
* Switching back to "Properties" from "Inheritance" shows the information of another connection. Sometimes the connection "Properties" shown is one above the currently selected one, on another instance it was three connections above the selected one.

## Steps to Reproduce (for bugs)
* Create a folder under "Connections".
* Create some SSH and RDP connections under the folder.
* "Duplicate" the connections several times over time, changing "Display"->"Name" and "Connection"->"Hostname" in "Config".
* Select a host.
* Switch "Config" to "Inheritance"
* Switch "Config" back to "Properties"
* "Name" and "Hostname" now show details of a different connection, while the correct connection is still highlighted in "Connections"

## Your Environment
* Version used: 1.76.5.31190
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 x64

**Comment by sparerd** [comment] 2018-08-22 10:54
Duplicate of #1076 - this one is fixed and will be in v1.76.7. I'll try to get it out today

**Closed by sparerd** 2018-08-22 10:54 UTC
Labels: Bug, Duplicate

**Comment by bluikko** [comment] 2018-08-22 11:01
Sorry, I did search for "inheritance" and "inherit" before opening this one, no relevant results.

And thanks.

**Comment by sparerd** [comment] 2018-08-22 11:03
No problem! Some issues aren't named very well / don't have good keywords. Thanks for the detailed bug report though :)
