### ISSUE TITLE
Feature request: Keep-alive simulated mouse movements to prevent locking

### ISSUE THREAD

**Issue by nmg196** [mRemoteNG/mRemoteNG#1462] opened 2019-05-24 10:19 UTC
**Feature request: Keep-alive (simulated mouse movements to prevent locking)**

Some of our customer's servers lock the screen after 5 minutes. Their password policy also makes the passwords very difficult to type.    Can we please get some way to alleviate this common problem?  I have seen a client which has a "type password" button, which sends the password as keystrokes.  

Alternatively, could the app send "pretend" mouse movements when there haven't been any real ones, to make the remote system think I'm not idle?

Thanks,
Nick

**Comment by sparerd** [comment] 2019-05-24 12:48
Closing as duplicate of #405. Please read that thread for more details

**Closed by sparerd** 2019-05-24 12:48 UTC
Labels: Duplicate
