### ISSUE TITLE
After upgrade from 1.74 to 1.75b1 components check spawn upon connection window and can't be closed

### ISSUE THREAD

**Issue by theWoodman** [mRemoteNG/mRemoteNG#254] opened 2016-11-17 10:04 UTC
After i have upgraded from 1.74 to 1.75b1 the components check spawns inside the connection view'ish.

Problem is that it can't be closed or resized. which is kinda annoying...
![image](https://cloud.githubusercontent.com/assets/834968/20384857/92e0236a-acb5-11e6-896a-1a8f2bdd0023.png)

|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment] 2016-11-17 12:45
That's really weird... 

Help - > about should show a tab with a close button for both the components check and the about window. That should allow you to close it. Or you can then drag the components check tab to re-place it accordingly. 

You can also try view - > reset layout. But I don't think that impacts the components window. 

This type of oddness will ultimately be fixed by #155

**Comment by theWoodman** [comment] 2016-11-17 13:04
More observations:

If Tools -> components check -> help -> about ; press close button for both components:  
unhandled exption
![image](https://cloud.githubusercontent.com/assets/834968/20390273/6d7b4a50-acce-11e6-9071-5155c88e8554.png)

If Tools -> components check -> View -> Reset layout:
unhandled exeption
![image](https://cloud.githubusercontent.com/assets/834968/20390296/89111e84-acce-11e6-9365-a4fc9f454389.png)

Lets keep this bug open until #155 is fixed to verify functionality is ok by then. As this is a beta release we can live with the functionality that you should close mRemoteNG to get those messages away.

**Comment by sparerd** [comment] 2016-11-17 15:38
That is a very odd bug.

The last exception screenie you posted is something we usually see when there are missing RDP KBs. Can you confirm if you are able to connect via RDP successfully? Relevant article: https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#mremoteng-crashes-with-the-error-class-not-registered-when-trying-to-connect-using-rdp

If it's not RDP causing it, then I think we are discovering a new prereq we may need to package with the installer.

**Comment by theWoodman** [comment] 2016-11-17 16:30
I have just tried to connect via RDP to a test VM in azure without any problems. 

Is there any log files i can provide?

**Comment by sparerd** [comment] 2016-11-17 16:32
Yea, log files would be great.

Here's an article on how to collect them: https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by sparerd** [comment] 2016-11-17 16:36
Someone else in my office was able to replicate the CLASSNOTREG exception when trying to close the components window.

**Comment by kmscode** [comment] 2016-11-17 19:42
I'm not able to reproduce any of this... 😕

**Comment by sparerd** [comment] 2016-11-17 19:46
I haven't been able to reproduce on my machine either. I'm guessing there's something about our dev environment that is not being distributed with the binaries as required. Might even been an installer bug, tbh

**Comment by kmscode** [comment] 2016-11-17 20:02
@theWoodman Could you please provide the full text of the exception within the window?

**Comment by theWoodman** [comment] 2016-11-17 20:53
Full text from exception window:
[full_error_175b1.zip](https://github.com/mRemoteNG/mRemoteNG/files/598444/full_error_175b1.zip)

logs for reference:
[mRemoteNG.log.zip](https://github.com/mRemoteNG/mRemoteNG/files/598433/mRemoteNG.log.zip)

**Comment by sparerd** [comment] 2016-11-17 21:20
This seems to be happening due to the client not having Citrix Receiver installed. This is not a mandatory prerequisite to have installed. It seems that the component check window is not handling the errors as gracefully as it should be.

Investigating possible fixes now.

**Comment by theWoodman** [comment] 2016-11-17 21:25
Would it be a possibility from the components check to "download and deploy" the prereqs that you might need now?
Sure the app should pop up and ask if you need a specific prereq...

**Comment by sparerd** [comment] 2016-11-17 21:32
We could add that in i suppose, but it's mostly just there to tell you if optional components are installed or not. The Citrix Receiver component is only needed if you want to use ICA connection types - the rest of the app should work just fine even if that component isn't installed.

It's odd that the app is having troubles with this now. I didn't think we made any changes to this part of the codebase.

**Comment by jumoog** [comment] 2016-11-17 21:53
maybe it's possible to copy the dll thats needed for ICA connection's into the app dir?

**Comment by kmscode** [comment] 2016-11-17 22:04
@sparerd see of you can just build a new release based on my last commits. Just grab the mRemoteNG.exe's and attach them to this bug for validation... I moved the ica (and rdp) into a using. Thus may help. However... Now that I'm thinking about it more... Make sure the using is within the try block. I would think this would take care of it. 

If you attach the eye's, one release portable and one release - not sure if anyone in this is reporting in a specific build... Anyone willing to test can rename the existing and replace with the updated one. Then we can issue a beta 2. Which will be a good test of the update checks.

**Comment by sparerd** [comment] 2016-11-17 22:17
wafflebot autoclosed the issue... didn't want that quite yet

**Comment by sparerd** [comment] 2016-11-17 22:18
The resolution was to move the `using` directive which instantiates the AxIca control into the `try` block.

**Comment by sparerd** [comment] 2016-11-17 22:23
@jumoog unfortunately not - it's all done through COM classes, so we only have interop DLLs for ICA.

**Comment by sparerd** [comment] 2016-11-17 22:31
@theWoodman Here is an updated mRemoteNG.exe **(portable edition)**. Just overwrite the current .exe in your mRemoteNG folder. If you are using the installed version, let me know and I can compile that one instead. If this fixes it, we'll do an official beta2 release.

[mRemoteNG exe _ #254 fix 1.zip](https://github.com/mRemoteNG/mRemoteNG/files/598625/mRemoteNG.exe._.254.fix.1.zip)

**Comment by nqnguyen2** [comment] 2016-11-18 00:57
Hi sparerd,

Sorry for the late notes. Screenshot of the error, error log and a text file from the error window are zipped and attached. Issue was experienced earlier today around 9:30am MT. I'll check out the newer update now.

Opened a new connection using the "Connect:" from the tool bar at the top in the attempt to remove the 'component check' window. Logged into server and finally saw tabs at the top. Tried to switch to 'component check' window and error window popped up.

![2016-11-17_1129](https://cloud.githubusercontent.com/assets/23535412/20414129/28be8718-acee-11e6-9e7e-f88c7f57e5c6.png)

Operating system: Windows 7 Pro x64
mRemoteNG Version: 1.75.6164.27563
[issue254.zip](https://github.com/mRemoteNG/mRemoteNG/files/598815/issue254.zip)

**Comment by nqnguyen2** [comment] 2016-11-18 01:16
Hi sparerd,

I've tested the latest update you made and still experiencing an issue. Using portable version. I'll outline two encounters below.

**1st encounter** (9:30am MT today; using work laptop)
Opened a new connection using "Connect:" toolbar at top in the attempt to remove the 'component check' window. Logged into server and finally saw tabs at the top. Tried to switch to 'component check' window and error window popped up. 
[issue254.zip](https://github.com/mRemoteNG/mRemoteNG/files/598838/issue254.zip)

Also, if possible, please include a handlebar or close window button for the 'component check'.

**2nd encounter** (1800 MT today; using home desktop)
Encountered similar error after updating my exe from your last post. Performed same actions as 1st encounter except when i select SSH2 protocol and click the button, I get the error.
[254error2.zip](https://github.com/mRemoteNG/mRemoteNG/files/598839/254error2.zip)

**Comment by sparerd** [comment] 2016-11-18 01:44
You can choose to have panels always display their tabs by going to Tools -> Options -> Tabs & Panels -> Always display tabs

Ok, ill have to check it again tomorrow. Their may be more things to fix.

**Comment by sparerd** [comment] 2016-11-18 15:49
This is still an issue... I can still replicate if the test machine does not have Citrix Receiver installed. Still investigating.

**Comment by kmscode** [comment] 2016-11-18 18:08
Don't you wish we removed ica now? :smile:

**Comment by sparerd** [comment] 2016-11-18 20:01
After significant hunting, I found the commit that introduced the error: `6d1fa47`

Still need to figure out what exact change created the issue, but at least the field is narrowing.

**Comment by sparerd** [comment] 2016-11-21 15:19
The bug occurs due to the `Parent` property of the AxICAClient being set during object initialization using the format:
```csharp
var ica = new AxICAClient {Parent = this};
```

Splitting this up into 2 statements resolves the bug:

```csharp
var ica = new AxICAClient();
ica.Parent = this;
```

(The current production code is slightly different, but you get the idea.)

**Comment by sparerd** [comment] 2016-11-21 15:35
Everyone that has been experiencing the issue, please test this new exe (it's portable edition). Replace the exe in your portable edition folder with the one provided below.

[mRemoteNG exe_#254 fix 2.zip](https://github.com/mRemoteNG/mRemoteNG/files/604007/mRemoteNG.exe_.254.fix.2.zip)

**Comment by nqnguyen2** [comment] 2016-11-21 17:17
Nice work! Unable to replicate the issue. Tabs show up properly and able to switch between them with no issues.

**Comment by sparerd** [comment] 2016-11-21 17:19
Thanks for confirming @nqnguyen2 
@theWoodman let me know when you are able to test as well. Once this issue is closed we will release a beta2 version with the few bug fixes that have been completed.

**Comment by theWoodman** [comment] 2016-11-22 08:09
It seem to work.

**Comment by sparerd** [comment] 2016-11-22 14:56
Great - closing issue as resolved. Thanks everyone

**Closed by sparerd** 2016-11-22 14:56 UTC
Labels: Bug, in progress
