### ISSUE TITLE
Option to see some/all of my open connection screen at once(like dashboard)

### ISSUE THREAD

**Issue by ndinev** [mRemoteNG/mRemoteNG#1627] opened 2019-10-22 07:48 UTC
## Expected Behavior
Add option to see many connection (in view mode only) on one tab/screen. For example if I have 4 VNC connection I want to see them them scaled 1/4 on one screen 2x 2

## Current Behavior
On each tab user can see only one VNC/RDC screen

## Possible Solution
We can have one special tab called dashboard. Then user can add connections to this dashboard. 
All added connections can be in read only mode - it is not expected user to work actively on this screen
Maybe user can specify thumbnails size for the screen or to choose auto scale(seems more appropriate). Alto scale should fit all selected connections screen to the available space on the dash. 
If connection is not connected leave thumbnails for it blank.

## Context
I want just to monitor multiple screens without switching between tabs

**Comment by farosch** [comment] 2019-10-31 18:06
This is already possible in the alpha builds:
![image](https://user-images.githubusercontent.com/22905106/67973794-7c34f600-fc11-11e9-8ea1-dc081d18eb08.png)

Also, duplicate of #574

**Closed by farosch** 2019-10-31 18:06 UTC
