### ISSUE TITLE
Error when connecting to VNC server w/o a password

### ISSUE THREAD

**Issue by vargasjj** [mRemoteNG/mRemoteNG#396] opened 2017-02-09 14:41 UTC
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 RC1  |

Whenever I tried to VNC to a TightVNC server that does not have a password set, I get:

> ErrorMsg Opening connection failed! Parameter is not valid.

This defect is being around on mRemoteNG for a while and I cannot find a resolution. I can reproduce it.

Here are the logs:

> 2017-02-09 09:34:06,649 [1] ERROR- frmMain WndProc failed
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at VncSharp.VncClient.OnConnectionLost()
   at VncSharp.VncClient.WriteClientCutText(String text)
   at VncSharp.RemoteDesktop.FillServerClipboard()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.VNCEvent_ClipboardChanged()
   at mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)
2017-02-09 09:34:20,399 [1] ERROR- Opening connection failed!
Parameter is not valid.
2017-02-09 09:34:20,419 [258] INFO - Connection Event Closed
2017-02-09 09:34:20,420 [258] INFO - Connection to x.x.x.x via VNC closed by user ******.
2017-02-09 09:34:20,571 [258] ERROR- Couldn't dispose control, probably form is already closed (Connection.Protocol.Base)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.Connection.Protocol.ProtocolBase.DisposeControl()
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
2017-02-09 09:34:20,574 [258] ERROR- Couldn't set InterfaceControl.Parent.Tag or Dispose Interface, probably form is already closed (Connection.Protocol.Base)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at mRemoteNG.Connection.Protocol.ProtocolBase.DisposeInterface()
   at mRemoteNG.Connection.Protocol.ProtocolBase.CloseBG()
2017-02-09 09:38:39,990 [1] ERROR- frmMain WndProc failed
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at VncSharp.VncClient.OnConnectionLost()
   at VncSharp.VncClient.WriteClientCutText(String text)
   at VncSharp.RemoteDesktop.FillServerClipboard()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.VNCEvent_ClipboardChanged()
   at mRemoteNG.UI.Forms.frmMain.clipboardchangeEventHandler.Invoke()
   at mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)
2017-02-09 09:38:39,992 [1] ERROR- frmMain WndProc failed
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at VncSharp.VncClient.OnConnectionLost()
   at VncSharp.VncClient.WriteClientCutText(String text)
   at VncSharp.RemoteDesktop.FillServerClipboard()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.VNCEvent_ClipboardChanged()
   at mRemoteNG.UI.Forms.frmMain.clipboardchangeEventHandler.Invoke()
   at mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)
2017-02-09 09:39:00,541 [1] ERROR- frmMain WndProc failed
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at VncSharp.VncClient.OnConnectionLost()
   at VncSharp.VncClient.WriteClientCutText(String text)
   at VncSharp.RemoteDesktop.FillServerClipboard()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.VNCEvent_ClipboardChanged()
   at mRemoteNG.UI.Forms.frmMain.clipboardchangeEventHandler.Invoke()
   at mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)
2017-02-09 09:49:02,050 [1] ERROR- frmMain WndProc failed
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at VncSharp.VncClient.OnConnectionLost()
   at VncSharp.VncClient.WriteClientCutText(String text)
   at VncSharp.RemoteDesktop.FillServerClipboard()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.VNCEvent_ClipboardChanged()
   at mRemoteNG.UI.Forms.frmMain.clipboardchangeEventHandler.Invoke()
   at mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)
2017-02-09 09:49:02,444 [1] ERROR- frmMain WndProc failed
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at VncSharp.VncClient.OnConnectionLost()
   at VncSharp.VncClient.WriteClientCutText(String text)
   at VncSharp.RemoteDesktop.FillServerClipboard()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.VNCEvent_ClipboardChanged()
   at mRemoteNG.UI.Forms.frmMain.clipboardchangeEventHandler.Invoke()
   at mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)
2017-02-09 09:50:45,428 [1] ERROR- frmMain WndProc failed
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at VncSharp.VncClient.OnConnectionLost()
   at VncSharp.VncClient.WriteClientCutText(String text)
   at VncSharp.RemoteDesktop.FillServerClipboard()
   at mRemoteNG.Connection.Protocol.VNC.ProtocolVNC.VNCEvent_ClipboardChanged()
   at mRemoteNG.UI.Forms.frmMain.clipboardchangeEventHandler.Invoke()
   at mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)

Since you guys took the project now to Github I was wondering if you have any fix soon, or a workaround.

I searched here on github and on your reddit page. I think the referred links are related but I am not sure.

Any workaround for this?
Thank you.

~ JJ

Reference:
#274 
[https://mremoteng.atlassian.net/browse/MR-208](url)
[http://forum.mremoteng.org/viewtopic.php?f=3&t=1707](url)

**Comment by kmscode** [comment] 2017-02-09 15:23
Closing as duplicate of #274

Please follow #274 for future update.

**Closed by kmscode** 2017-02-09 15:23 UTC
Labels: Duplicate
