### ISSUE TITLE
Update check failure - Nightly 1.77.2

### ISSUE THREAD

**Issue by pauldurham** [mRemoteNG/mRemoteNG#2149] opened 2022-01-31 20:50 UTC
Built-in check for updates results in "Check failed!"

## Expected Behavior
The update check should return the current version number and/or indicate that an update is available..

## Current Behavior
Built-in check for updates results in "Check failed!"

## Steps to Reproduce (for bugs)
Select Update Check from the menu.

## Context
I can't find out, using the built-in version checker, if an update is available.

## Your Environment
Windows 10 Enterprise 64-bit Build 2004.

**Comment by farosch** [comment] 2022-02-02 23:11
Duplicate of #1853

**Closed as completed by farosch** 2022-02-02 23:11 UTC
