### ISSUE TITLE
Folders do not pass through credentials to connections

### ISSUE THREAD

**Issue by JangoBritt** [mRemoteNG/mRemoteNG#482] opened 2017-04-03 08:43 UTC
So folders in the Connections list have the option to configure credentials, but when you create a connection under that folder, it doesn't pass through the credential from the folder... is this a bug?

**Comment by sparerd** [comment] 2017-04-03 23:48
Just to confirm, is user/password/domain inheritance set on the connection? Also, which version of mRemoteNG are you running?

**Comment by TechGuy419** [comment] 2017-04-05 13:44
I am seeing this as well but only on the General Root config.  The subfolders pass the credentials just fine with inheritance enabled.  It appears that after I exit mRemote and launch it again that there are extra characters added to the password.

Windows 8.1 
mRemoteNG Portable 1.75.7003.25226

**Comment by sparerd** [comment] 2017-04-05 14:17
I am seeing a bug with the display of inheritance options for folders/connections that are direct children of the root node. These should not have inheritance as an option.

Example:
- Connections (the root node)
   - Connection1
   - Folder1
       - Connection2

We should not be able to set inheritance on `Connection1` and `Folder1` - the button should be greyed out and the inheritance should be completely off. Currently, we can set inheritance. I'd consider this a bug.

> It appears that after I exit mRemote and launch it again that there are extra characters added to the password.

@TechGuy419  Not able to replicate this at the moment. Are you using the SQL feature, or saving to an xml file?

**Comment by TechGuy419** [comment] 2017-04-05 14:23
I am saving to an xml file.  Below is a portion of the user.config located in AppData.  I see that the value is encrypted but I feel that this is what is causing the issue.

<setting name="ConDefaultPassword" serializeAs="String">
                <value>723mA4QCB9Xofk7O9v+Zy2mxfu2kAq0MZ02ubsVX6P4=</value>
            </setting>

Your thoughts?

**Comment by TechGuy419** [comment] 2017-04-05 14:50
I was setting this on Connections (root).  This was so when I type a system name in the quick connect it would us the default credentials instead of prompting me.  I do not add every system I connect to daily to a connection folder.

- Connections (root) - (setting specific UN,PW,DN for quick connections)
     - SomeFolder (setting specific UN, PW, DN)
          - Connections (inheriting all from SomeFolder) 

The issue as only with the password being set on the the Connections (root).  The other password entry on SomeFolder was retained in the portable connection file and has been working as expected.

**Comment by sparerd** [comment] 2017-04-05 14:56
Ahh I think I see now. You set the user/pass/domain settings on the default connection info (highlighted in orange):
![2017-04-05_0854](https://cloud.githubusercontent.com/assets/6999446/24711554/89cd1fa4-19dd-11e7-8bbf-41deec1b0867.png)

**Comment by JangoBritt** [comment] 2017-04-05 15:03
how do you configure inheritance? In my Options/Connections, I only have the options None, Current credentials, and specify.

Windows 10, mRemoteNG 1.72.5065.32737

**Comment by sparerd** [comment] 2017-04-05 15:06
@JangoBritt Here is a quick guide that will walk you through the process: https://github.com/mRemoteNG/mRemoteNG/wiki/Folders-and-Inheritance

**Comment by sparerd** [comment] 2017-04-05 15:08
@TechGuy419 I've found the bug that is causing the incorrect default connection info password. I'll try to get something worked up for our next round of bug fixes.

**Comment by TechGuy419** [comment] 2017-04-05 18:30
@sparerd You are correct Sir.  I really appreciate your assistance with the bug.

**Comment by kmscode** [comment] 2017-09-09 20:54
@sparerd 

> I've found the bug that is causing the incorrect default connection info password. I'll try to get something worked up for our next round of bug fixes.

Post or send me the details and I'll see if I can look into this if you can't get to it.

**Comment by sparerd** [comment] 2017-09-14 20:23
@kmscode The issue happens when loading the ConDefaultPassword string from the user settings file. We read the encrypted string up and store it in the DefaultConnectionInfo object without decrypting it.

DefaultConnectionInfo.cs, somewhere around line 31/33

**Comment by kmscode** [comment] 2017-09-15 17:49
@sparerd I've looked at this quickly...

I would think that we should be looking at \mRemoteV1\Connection\DefaultConnectionInheritance.cs (not DefaultConnectionInfo.cs)?

While not the correct way - based on how everything else is currently done - we should be decrypting the password on load and encrypting it before save. So I guess that in theory would be the fix for this one?

A better (read: more secure) implementation would be use the [SecureString Class](https://msdn.microsoft.com/en-us/library/system.security.securestring(v=vs.110).aspx) - or decrypt on USE (before needing the password for a connection or ext tool for example). This would keep the password encrypted in memory at all times.

I didn't fully step through the code, but just did a semi-quick review and had these thoughts... Do you have any other ideas?

**Comment by sparerd** [comment] 2017-09-15 18:21
Since the default connectioninfo object is saved to the user settings file, the framework is handling the load/save of the string for us. The DefaultConnectionInfo then loads (just copies) data from the settings class to populate the singleton connectioninfo object. That's why I suggest that the root of the issue is in the DefaultConnectionInfo.cs file - though I guess it isn't quite the simple now that I type all that out...

I agree with your points around how to fix the issue. Either decrypt at load-time or decrypt it on each use. I created a class `mRemoteNG.Security.EncryptedSecureString` for making these sorts of things a little easier but ended up not using it. Maybe this would be a decent way to go?

We would probably want to modify the class a bit since it originally didn't support loading ciphertext strings. Maybe rename `SetValue(string value)` to `SetValueFromPlainText(string plainText)` and add a method `SetValueFromCipherText(string cipherText)` that just doesn't do the call to `Encrypt`.

**Comment by pedro2555** [comment] 2017-09-17 13:53
I've been looking at this for a bit, and couldn't quite figure what the issue, is. Is there a test case one could setup quickly?

Anyway, just my 2 cents about the encrypt, decrypt thing on the `ConDefaultPassword`; where is this a miss? It kinda seems a simple check, am I missing something?

[/Config/Settings/SettingsLoader.cs#L68](https://github.com/mRemoteNG/mRemoteNG/blob/Patch9/mRemoteV1/Config/Settings/SettingsLoader.cs#L68) Decrypts

[/Config/Settings/SettingsSaver.cs#L65](https://github.com/mRemoteNG/mRemoteNG/blob/Patch9/mRemoteV1/Config/Settings/SettingsSaver.cs#L65) Encrypts

We could do this at runtime admittedly, best way is just to implement a type for it (I guess `mRemoteNG.Security.EncryptedSecureString`) and use that type on settings configuration directly, and let the SettingsProvider handle the saving and what not.

But, again, I could not see what the reported problem is exactly.

**Comment by sparerd** [comment] 2017-09-17 16:20
Rearranging some initialize code seems to take care of the problem as well. Created #724 to show the fix. I'm in favor of swapping out the string for an EncryptedSecureString (or something similar) that takes care of the encrypt/decrypt for us, but this is the simplest code sample that resolves the problem.

Steps to reproduce the issue:
1. Click on the Connections root node, and select the Default Properties button
1. Set the Password field (`asdf123`)
1. Close and reopen mRemoteNG
1. Create a new connection
1. The password of the new connection will be a long Base64 encoded string. We expect to have the plain-text string (obfuscated with dot characters).

**Comment by kmscode** [comment] 2017-09-18 13:24
@sparerd I say merge #724 for now and we can work on the "full" fix for the next major release via #726

**Comment by sparerd** [comment] 2017-10-28 14:52
I'm going to close this issue as the problem should be resolved with #724 (released with patch 9)

**Closed by sparerd** 2017-10-28 14:52 UTC
Labels: in progress
