### ISSUE TITLE
[Request] - Split panel option

### ISSUE THREAD

**Issue by Silent-Joker** [mRemoteNG/mRemoteNG#257] opened 2016-11-17 22:58 UTC
Would it be possible to add an option to split panel connections?  Usually when debugging some issues i am in 2 devices at once and i use 1 large monitor.  Instead of running 2 sessions of Mremote it would be nice to be able to split panel sessions.  Either RDP or Putty.  I use panels a lot to keep sessions organized.

So or example if you add a 2nd panel option call Split Panel.  if i create a label here it would share the space with any open sessions in it.  if i do 2 sessions its split 50/50 left to right.  If i do 3 or 4 its quad.... etc etc.. 

If this can be done now i must be overlooking it and I am sorry.

thanks for listening...

**Comment by Silent-Joker** [comment] 2016-11-17 23:10
sorry i think this is the same kind of request just different.  if so u can merge it.

https://github.com/mRemoteNG/mRemoteNG/issues/223

**Comment by sparerd** [comment] 2016-11-17 23:39
This can already be done by creating 2 panels and dragging one to split the screen. 
It's easier to show than explain, so here's an [example video](http://www.screencast.com/t/ROqIB5Lef1PL)

Will close this as a duplicate of #223. We will be changing some inner workings of panels/tabs in an up coming update which should make this feature a little more intuitive.

**Closed by sparerd** 2016-11-17 23:39 UTC

**Comment by sparerd** [comment] 2016-11-17 23:43
Forgot to mention - you have to choose the proper panel to show the connection when the connection starts. (right click connection -> Connect (with options) -> Choose panel before connecting). Connections cant be moved between panels while active.

Definitely not intuitive.
