### ISSUE TITLE
Search Connections - Feature Request

### ISSUE THREAD

**Issue by DerGue** [mRemoteNG/mRemoteNG#565] opened 2017-05-23 12:10 UTC
I have now more than 30 RDP connections, even when I close groups it takes a while to find the cerver I need.
**My feature request is a simple search-bar for description, servername or folder.** 
Then I could find my "SQL" servers within seconds.

Thanks!
Gü

**Comment by kmscode** [comment] 2017-05-23 13:59
Duplicate of #184 / #338

**Closed by kmscode** 2017-05-23 13:59 UTC
Labels: Duplicate
