### ISSUE TITLE
Putty config parsing problem

### ISSUE THREAD

**Issue by ramiralez** [mRemoteNG/mRemoteNG#496] opened 2017-04-10 09:58 UTC
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| v1.75.7003 (Hotfix 4)  |
|Microsoft .NET CLR | 4.0.30319.42000|

mremoteng cant load startup file with error:

```
The startup connection file could not be loaded.
Object reference not set to an instance of an object.
In order to prevent data loss, mRemoteNG will now exit.
```

Looks like problem with parsing putty "Default Settings" file.

Workaround: delete folder "Sessions" with putty's "Default Settings" file.

**Comment by farosch** [comment] 2019-10-07 08:02
Closing this as I cannot reproduce it and it has been reported for an old version of mRemoteNG

**Closed by farosch** 2019-10-07 08:02 UTC
Labels: Cannot Reproduce
