### ISSUE TITLE
redirection

### ISSUE THREAD

**Issue by cantremeber** [mRemoteNG/mRemoteNG#1630] opened 2019-10-24 14:33 UTC
Redirection is not working as expected, 

## Expected Behavior
whenever i log on a system i don't see all printers, only a the main as Fax or the Microsoft XPS Printer are getting redirected, the real printer drivers as a konika-minolta won't get redirected. 
 Port redirection don't work at all and Harddisk too.

## Current Behavior
when i open the rdp session via mstsc, than printers, ports  and drives are redirected.

## Steps to Reproduce (for bugs)
no special steps are needed

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
my version 1.76.20 on win10 1903, and server 2012 and 2016

**Comment by farosch** [comment] 2019-11-10 11:18
Duplicate of #1182

**Closed by farosch** 2019-11-10 11:18 UTC
