### ISSUE TITLE
With last update 1.75.7010.21198 External Tools no longer start

### ISSUE THREAD

**Issue by Alessio71** [mRemoteNG/mRemoteNG#761] opened 2017-10-31 08:15 UTC
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010  |

After the last update, 1.75.7010.21198, External Tools
![mremoteng1](https://user-images.githubusercontent.com/24569704/32213499-cca37750-be1b-11e7-9808-42448aff1418.JPG)
no longer start when launched (no cmd launched at all)
![mremoteng2](https://user-images.githubusercontent.com/24569704/32213541-f14ad120-be1b-11e7-84c0-e04eb1f390ec.JPG)

Same problem with 1.75.7009, works with 1.75.7008.
Thank you

**Comment by peanek** [comment] 2017-10-31 08:56
Same problem here, 
```
OS ver : Windows Server 2008R2 x64
mRemoteNG ver : 1.75.7010.21169
```

External tools with external protocol Dame Ware - does not start at all. on 7008 worked like a charm. 

![2017-10-31 09_50_39-mremoteng - sql server](https://user-images.githubusercontent.com/28780396/32215186-871032a4-be21-11e7-80c3-5a1802c66668.png)

What's funny - if I try to open external tool by option Launch in menu TOOLS --> EXTERNAL TOOLS it will open - but of course with bad parameter. 

![2017-10-31 09_52_04-mremoteng - sql server](https://user-images.githubusercontent.com/28780396/32215229-afec230e-be21-11e7-9d3f-209c272fd7e5.png)

So, getting back right now to 7008.

**Comment by sparerd** [comment] 2017-10-31 13:56
Was able to find the cause. A fix will be released shortly.

**Comment by sparerd** [comment] 2017-11-02 12:54
I think I have a fix for this in place.

@Alessio71  @peanek Would you be able to test the following version and confirm?
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011.r1

**Comment by Alessio71** [comment] 2017-11-02 12:56
I've tested it this morning and looks just perfect.
thank you

**Comment by sparerd** [comment] 2017-11-02 12:57
Good to hear, sorry for the trouble it caused you

**Comment by sparerd** [comment] 2017-11-08 02:36
v1.75.7011 has been released
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011

**Closed by sparerd** 2017-11-08 02:36 UTC
Labels: Bug, High Priority
