### ISSUE TITLE
Erratic Tree Selection when using SQL Database

### ISSUE THREAD

**Issue by Totorman** [mRemoteNG/mRemoteNG#529] opened 2017-04-28 11:48 UTC
When using the configuration connected to SQL Server, the Tree selection on the left is changing very often, even if i dont click on another tree item.

It seems there is an autorefresh which does not occurs when using the xml file mode.
This screen refresh is a problem because when editing a server or a connection info, after the refresh, nothing is selected in the tree, so the configuration window is not in sync with the tree, so it makes the save item to fail (no error, but nothing saved, or in a place i do not know).

|||
|--:|---|
|Operating system | Windows 10 pro x64 |
|mRemoteNG version| Prerelease v1.75.7005 (Hotifx 5)  |

**Comment by kmscode** [comment] 2017-04-28 12:21
Hmmm... I thought we had this one fixed with HF5... We'll have to look into it further.

**Comment by Totorman** [comment] 2017-05-02 09:00
for now, i use local file, and when updated, change config to sql, then save, then go back to local file.

**Comment by Totorman** [comment] 2017-05-17 06:14
any bug found for this ?

**Comment by Toffaa** [comment] 2017-05-29 12:42
Hello,

My team and I use mRemoteNG with a shared database, and when someone makes a change, when the change is saved, the tree "shape" of the user who makes the change is also saved. And then when everyone else receive the change, our tree is moved to match with the one saved.

Also, could you clarify the use of "save connection file" function with database ? Should we use it when we make a change or ?

Thank you for your help and your work :)

**Comment by bash3569** [comment] 2017-06-06 10:11
Hello,
I have the same problem.
Is there a solution?

Can we deactivate auto refresh with an option?

**Comment by peanek** [comment] 2017-06-27 15:20
Hello,

Like **sparerd** wrote above - I've made a copy of this issue #612 . I cannot add or modify in normal way connections. Tree selection is expanding in chaotic way, without any reason. 

When this happens by changing or adding new connection - I am loosing all the changes I've made. 
It is - like author wrote - erratic :)

**Comment by Totorman** [comment] 2017-07-19 16:16
If the bug/behaviour is not correctable, a checkbox or pushed button on interface weather or not to sync realtime the Tree could be cool, becuase modifications are very difficult to do. Or maybe add this parameter : AutoSyncTime : integer with a number of seconds for the autorefresh to occur. Then we can put to what we want :)

**Comment by peanek** [comment] 2017-07-19 16:20
I can confirm what Totorman wrote above - modifications are impossible to do..... It is almost useless in case of SQL configuration :(

**Comment by Toffaa** [comment] 2017-07-24 09:12
I think there is a problem related to the field "Expanded" in the database. It makes the tree chaotic when several people are working on the same database.

I think the tree expansion should be local to each client, it would solve the problem.

Also, isn't the refresh frequency too high? I checked with Wireshark and i saw tons of packets related to SQL, but I don't know if it's normal or not...

**Comment by sgates3414** [comment] 2017-07-26 14:50
I seem to be having a similar issue.  However I see my issue when trying to edit/add new folders or connections.  I can have to reapply changes I made to existing/new folders or connections several times before the changes stick.  I've tried several approaches and cannot find any consistency or pattern that makes these operations when using a SQL DB usable.  For instance, I can reconfigure the same server 5x before selecting it from the connections pane shows my configured values.

**Comment by tomerMP** [comment] 2017-08-31 14:18
I have been having the exact same issue. I am busy attempting a POC of mRemoteNG with SQL DB server and am currently the only user connected, so there is no chance of interference from other users or simultaneous edits. The issue is persistent and makes the SQL feature near on unusable. 

I cannot imagine this should be a difficult fix. It would probably include functionality that allows the selected session entry to remain selected even during a DB refresh. That would probably take care of the issue.

**Comment by Totorman** [comment] 2017-09-04 07:28
Hello, is there any update correcting this (or near), that is available somewhere ?

**Comment by sparerd** [comment] 2017-10-28 14:34
The fix provided by @dekelMP will be included in the patch 9 release coming shortly.

**Closed** 2017-10-28 14:43 UTC
Labels: Bug
