### ISSUE TITLE
Latest mRemoteNG develop Build Crashes on Windows Server 2019 - Cannot find CefSharp.Core.dll

### ISSUE THREAD

**Issue by jcefoli** [mRemoteNG/mRemoteNG#1785] opened 2020-06-09 23:33 UTC
## Current Behavior
App crashes on startup (after loading graphic). I am using the portable version compiled from the latest `develop`. Additionally, the crash reporter window does not close and I need to kill the process to get rid of it

## Expected Behavior
Appication launches

```
Exception Message
"Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found."

Stack trace
   at mRemoteNG.UI.Forms.FrmMain.FrmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m) in C:\Git\MremoteNG\mRemoteNG\UI\Forms\FrmMain.cs:line 613
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Possible Solution
The previous build I have from 5/28 works. Something in the latest code caused this. It does however work on Windows 10

Is it a dll hell / binding redirect issue?

## Steps to Reproduce (for bugs)
1. Compile `develop` branch targeting Release Portable
2. Copy zip to Server 2019 instance
3. Launch exe

## Your Environment
OS: Microsoft Windows NT 10.0.17763.0 -  Windows Server 2019 (Version 1809; 17763.1217)
mRemoteNG Version: 1.77.1.24834
Edition: Portable
Cmd line args:

**Comment by farosch** [comment] 2020-06-10 07:04
Looks like your System has trouble either finding or building CefSharp.
Can you find a *CefShar.Core.dll* in you mRemote folder next to the mremoteng.exe?
Maybe something interesting in the build log?

Latest develop works just fine for me and AppVeyor doesn't seem to have any problems with it either, see.
https://ci.appveyor.com/project/mremoteng/mremoteng/builds/33413697

Link to the latest portable develop build:
https://ci.appveyor.com/api/buildjobs/b7m0v0sadc4airq3/artifacts/Release%2FmRemoteNG-Portable-1.77.1.26820.zip

**Comment by farosch** [comment] 2020-06-10 07:15
Both my own build and the one pulled from artifactory work just fine for me:
![image](https://user-images.githubusercontent.com/22905106/84238152-db89ab80-aafa-11ea-8df6-e3d12d232d9f.png)

**Comment by farosch** [comment] 2020-06-10 07:17
**EDIT:**
Only way for me to reproduce this is trying to run mRemoteNG on a 2019 Server Core Edition.
I get this error then, which seems to be the same one you have:
```
   at mRemoteNG.UI.Forms.FrmMain.FrmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by farosch** [comment] 2020-06-11 12:08
I also just noticed you are running a Server 2019 **Standard**.
All my Server 2019 systems are running Datacenter Editions, so maybe that's a bug related to the Standard Edition. I'll try to set up a VM with a Standard install to see if I can replicate this.

**Comment by farosch** [comment] 2020-06-12 20:03
Got it:
Your system is probably missing the _Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019_

**Comment by jcefoli** [comment] 2020-06-15 14:02
Why does it need Visual C++ Redistributables when this is a .NET app?

**Comment by farosch** [comment] 2020-06-15 14:17
Thats the question. Looks like the Cefsharp.core.dll uses some kind of dependencie that is not included in the newer versions of windows /.net.
I'll try to check these with [DependencyWalker](https://www.dependencywalker.com/) and maybe I can include them into the project then

**Comment by jcefoli** [comment] 2020-06-19 14:28
Looking into cefsharp a little more, it's written in C++, so it makes sense that it would need the C++ runtime. I don't love how we reference DLLs that require other frameworks. My local dev machines have all of these tools, but I found this installing on a fresh server

Eventually if this gets rewritten in .NET 5, we want it to be portable

**Comment by farosch** [comment] 2021-12-14 20:37
Closing this, as cefsharp is no longer part of mremoteng but has been replaced by webview2 instead, see #2022

**Closed by farosch** 2021-12-14 20:37 UTC
Labels: Verified, Documentation
