### ISSUE TITLE
Impossible to update

### ISSUE THREAD

**Issue by OSITEX** [mRemoteNG/mRemoteNG#1193] opened 2018-11-19 05:11 UTC
## Expected Behavior
Error create SSL/TLS

## Your Environment
* Version used:1.75.7012.16814
* Operating System and version : Windows 10.0.17134 x64

**Comment by sparerd** [comment] 2018-11-19 13:33
Duplicate of #1135 

Please see this comment: https://github.com/mRemoteNG/mRemoteNG/issues/1135#issuecomment-429641183

**Closed by sparerd** 2018-11-19 13:33 UTC
Labels: Bug, Duplicate
