### ISSUE TITLE
New items are created in non-edit mode

### ISSUE THREAD

**Issue by jschlie** [mRemoteNG/mRemoteNG#495] opened 2017-04-09 18:32 UTC
|||
|--:|---|
|Operating system | All Windows versions |
|mRemoteNG version| v1.75.7003 (Hotfix 4)|

This is highly reproducable and I'm considering this a bug as it deviates from normal expected behavior.

When creating any new item, connection or folder, after clicking new an item is created called New Folder or New Connection.  However, the new object is created as a static object, selected, but the creation of the object is finalized.  At this point the user is required to then manually go back and rename the object.

Expected behavior would be for the object to be partially created leaving the user with an editable text box in order to name the new object. This doesn't happen and is consistent across several builds now.

**Comment by sparerd** [comment] 2017-04-09 21:17
Closing as duplicate of #479. Please follow that ticket for updates

**Closed by sparerd** 2017-04-09 21:17 UTC

**Comment by jschlie** [comment] 2017-04-09 22:15
Thanks, sorry for the dup.  Not sure how I missed that.

 
 
  On Sun, Apr 9, 2017 at 16:17, David Sparer<notifications@github.com> wrote:   
Closing as duplicate of #479. Please follow that ticket for updates

**Comment by sparerd** [comment] 2017-04-09 23:31
No problem :+1:
