### ISSUE TITLE
ShortCuts

### ISSUE THREAD

**Issue by smitjainsj** [mRemoteNG/mRemoteNG#322] opened 2016-12-27 10:33 UTC
**Team, can't we have shortcuts to switch tabs and sessions in mRemoteNG.
Also, Connections is always top left, hopefully if we can change it location to any of the screen in the future releases.
There is also a issue while switching tabs in windows 10 to and fro from mRemoteNG, it doesn't work as expected and sometimes makes the user to switch to mRemote instead to some other application.**

anyways Good Work Team, 

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment] 2016-12-27 20:12
- Keyboard shortcuts were removed due to stability issues. We hope to bring
them back in a future version.

- The connections tree can be moved to where ever you would like. Just drag
it

- Does the tab switching issue always occur with SSH connections? If so,
this is a known issue due to PuTTY. See issue #181


On Dec 27, 2016 4:33 AM, "Smit Jain" <notifications@github.com> wrote:



*Team, can't we have shortcuts to switch tabs and sessions in mRemoteNG.
Also, Connections is always top left, hopefully if we can change it
location to any of the screen in the future releases. There is also a issue
while switching tabs in windows 10 to and fro from mRemoteNG, it doesn't
work as expected and sometimes makes the user to switch to mRemote instead
to some other application.*

anyways Good Work Team,

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3 |

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mRemoteNG/mRemoteNG/issues/322>, or mute the thread

**Comment by kmscode** [comment] 2017-05-24 13:35
Duplicate of #196

**Closed by kmscode** 2017-05-24 13:35 UTC
Labels: Duplicate
