### ISSUE TITLE
SQL DB Encryption??

### ISSUE THREAD

**Issue by tomerMP** [mRemoteNG/mRemoteNG#712] opened 2017-09-14 08:50 UTC
Feature request:

I can see many mentions of encryption of XML-based DB file.
However we have begun using mRemoteNG with central SQL DB for all connections and it would seem that there is no option to encrypt this DB. As a result all of our connections are now no longer encrypted leaving an uneasy feeling.

If there is not yet a feature allowing encryption for SQL based connections DB then please could this be added to following version update?

**Comment by kmscode** [comment] 2017-09-14 16:02
There's a lot of work needed to make the SQL feature reliable and secure. See #182

**Comment by vmario89** [comment] 2018-04-11 22:05
hi. i am looking forward to have encrypted SQL database too. At the moment this feature is highly unsecure. Its even more unsecure because mRemote does not ask for a startup password. Once configured using an SQL server instead of local file, another user could breach my computer extracting all stored passwords from all connections simply iterating with echo %password%

Using a local file with saved connections gives possibility for encryption + password

:-(

**Comment by sparerd** [comment] 2018-11-04 22:19
Closing as duplicate of #449

**Closed by sparerd** 2018-11-04 22:19 UTC
Labels: Duplicate, Enhancement, Medium Priority
