### ISSUE TITLE
Microsoft RDP parameter RestrictedAdmin

### ISSUE THREAD

**Issue by StephanDosenbach** [mRemoteNG/mRemoteNG#1412] opened 2019-04-17 14:00 UTC
## Expected Behavior

Microsoft offers for Windows 10 and Windows Server 2016 new RDP Parameters to have a more secure RDP Connection
https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard

## Current Behavior

Today there's only the possibility to choose if RDP should use /admin console

## Possible Solution

Maybe the same as the usage of the admin console Switch a possibility to use a restrictedadmin switch

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1709 x64

**Comment by simonai1254** [comment] 2021-12-30 00:31
This seems to be a duplicate of #1125

**Comment by Kvarkas** [comment] 2022-04-15 15:48
https://github.com/mRemoteNG/mRemoteNG/pull/2203

**Closed by Kvarkas** 2022-04-15 15:48 UTC
Labels: Enhancement
