### ISSUE TITLE
Column 'RedirectAudioCapture' does not belong to table tblCons

### ISSUE THREAD

**Issue by MelHiour** [mRemoteNG/mRemoteNG#1453] opened 2019-05-17 08:11 UTC
## Expected Behavior
mRemoteNG should connect to mysql and get connections

## Current Behavior
mRemoteNG is crashed with Column 'RedirectAudioCapture' does not belong to table tblCons

## Possible Solution
Not clear

## Steps to Reproduce (for bugs)
1. Open a connection file
2. Configure mysql db
3. File - Save Connection File
4. Close mRemoteNG
5. Open mRemote again
6. It should be failing to open SQL data
7. Open some connection file
8. Catch an exception
[bagreport.txt](https://github.com/mRemoteNG/mRemoteNG/files/3190498/bagreport.txt)
[tblCons-dump.txt](https://github.com/mRemoteNG/mRemoteNG/files/3190541/tblCons-dump.txt)

## Context
I'm trying to store my connections in mysql db

## Your Environment
* Version used: 1.77.0.41307
* Operating System and version (e.g. Windows 10 1709 x64): WinServer 2008 R2 SP1

**Comment by sparerd** [comment] 2019-05-17 12:25
Duplicate of #1436, I will be updating the documentation shortly for the new fields.

**Closed by sparerd** 2019-05-17 12:25 UTC
Labels: Duplicate
