### ISSUE TITLE
New connections open in external PUTTY

### ISSUE THREAD

**Issue by techallan** [mRemoteNG/mRemoteNG#585] opened 2017-06-14 13:37 UTC
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

New connections open in external PUTTY instead of inside mRemoteNG after update this morning. Very frustrating.

**Comment by sparerd** [comment] 2017-06-14 13:39
Closing as duplicate of #583 - we are working on this

**Closed by sparerd** 2017-06-14 13:39 UTC
Labels: Duplicate
