### ISSUE TITLE
Dissapearing Mouse symptom

### ISSUE THREAD

**Issue by pererap01** [mRemoteNG/mRemoteNG#1579] opened 2019-09-12 22:32 UTC
## Expected Behavior
when I move mouse in a VM mouse should not disappear

## Current Behavior
Mouse disappears and shows up only in garyed areas and or edges

## Possible Solution
option to change the mouse colors when using mremooteNG

## Steps to Reproduce (for bugs)

1. Launch a VM
2. open an application
3. how over application
4.

## Context
cannot work on anything

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): WIndows 2016 x64

**Comment by farosch** [comment] 2019-09-24 06:42
Can you please provide **proper** step-by-step instructions so that we can investigate this further?

This:

> 1. Launch a VM
> 2. open an application
> 3. how over application

doesn't make even a little sense to me 😕

**Comment by farosch** [comment] 2019-10-02 22:04
Closed, as OP is not responding Most likely a duplicate of #532 anyways

**Closed by farosch** 2019-10-02 22:04 UTC
Labels: Bug, Duplicate, Verified
