### ISSUE TITLE
Cannot click to Connect textbox after click to console windows

### ISSUE THREAD

**Issue by quangnhut123** [mRemoteNG/mRemoteNG#201] opened 2016-10-26 03:04 UTC
Hi there i want to raise a bug. When i open a ssh connection and click to console window. I put my mouse point back to connect textbox i cannot click here anymore or type anything. I have to do this by click on Connect: label to put cursor to this textbox again. Please fix it soon !
Thanks

**Comment by kmscode** [comment] 2016-10-26 15:05
Duplicate of #176

**Closed by kmscode** 2016-10-26 15:05 UTC
