### ISSUE TITLE
1.75 Beta 1 - Crash on start

### ISSUE THREAD

**Issue by ptitboogy** [mRemoteNG/mRemoteNG#253] opened 2016-11-17 09:40 UTC
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 beta 1  |

I cannot start the latest version at all.

Here are the 2 Windows Event log that I found : 

_Log Name:      Application
Source:        Application Error
Date:          17/11/2016 10:21:29
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:     
Description:
Faulting application name: mRemoteNG.exe, version: 1.75.6164.27544, time stamp: 0x582cdb21
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23572, time stamp: 0x57fd0379
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0x24e4
Faulting application start time: 0x01d240b3fa1d9984
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\windows\syswow64\KERNELBASE.dll
Report Id: 387829d9-aca7-11e6-bb4f-54887b99ad10
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-11-17T09:21:29.000000000Z" />
    <EventRecordID>92974</EventRecordID>
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>mRemoteNG.exe</Data>
    <Data>1.75.6164.27544</Data>
    <Data>582cdb21</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.23572</Data>
    <Data>57fd0379</Data>
    <Data>e0434352</Data>
    <Data>0000c54f</Data>
    <Data>24e4</Data>
    <Data>01d240b3fa1d9984</Data>
    <Data>C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe</Data>
    <Data>C:\windows\syswow64\KERNELBASE.dll</Data>
    <Data>387829d9-aca7-11e6-bb4f-54887b99ad10</Data>
  </EventData>
</Event>_
################################################################################
_Log Name:      Application
Source:        .NET Runtime
Date:          17/11/2016 10:21:28
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      
Description:
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at mRemoteNG.App.Logger.Initialize()
   at mRemoteNG.App.Logger..ctor()
   at mRemoteNG.App.Logger..cctor()

Exception Info: System.TypeInitializationException
   at mRemoteNG.App.Logger.get_Instance()
   at mRemoteNG.App.Startup.LogApplicationData()
   at mRemoteNG.App.Startup.LogStartupData()
   at mRemoteNG.App.Startup.InitializeProgram()
   at mRemoteNG.App.ProgramRoot.StartApplication()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-11-17T09:21:28.000000000Z" />
    <EventRecordID>92973</EventRecordID>
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at mRemoteNG.App.Logger.Initialize()
   at mRemoteNG.App.Logger..ctor()
   at mRemoteNG.App.Logger..cctor()

Exception Info: System.TypeInitializationException
   at mRemoteNG.App.Logger.get_Instance()
   at mRemoteNG.App.Startup.LogApplicationData()
   at mRemoteNG.App.Startup.LogStartupData()
   at mRemoteNG.App.Startup.InitializeProgram()
   at mRemoteNG.App.ProgramRoot.StartApplication()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

</Data>
  </EventData>
</Event>_

**Comment by sparerd** [comment] 2016-11-17 15:20
Thanks for the report - this is an odd one.

Could you provide the mRemoteng.log file as mentioned in https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by kmscode** [comment] 2016-11-17 19:40
Possible fix checked in... Though, unable to reproduce. Unlikely that the log will have been written to. However, Please send in any crash dump info as noted on the wiki.

**Comment by ptitboogy** [comment] 2016-11-17 21:50
Hi,
Thanks for your quick support but after a second re-installation it seems to work.
I have uninstalled the beta1, re-install the Alpha3 and upgrade again to Beta1.

**Comment by kmscode** [comment] 2016-11-23 16:54
Closing per previous comment.

**Closed by kmscode** 2016-11-23 16:54 UTC
Labels: Bug, High Priority, in progress
