### ISSUE TITLE
Personalize icons

### ISSUE THREAD

**Issue by fabio-oliveira-efeo** [mRemoteNG/mRemoteNG#1300] opened 2019-02-06 10:10 UTC
Possibility of customizing server icons

**Comment by end-user** [comment] 2019-02-07 13:16
possible duplicate?  https://github.com/mRemoteNG/mRemoteNG/issues/1133

**Comment by kmscode** [comment] 2019-02-07 14:03
Closing as duplicate of #1133 - please follow that issue for further updates.

**Closed by kmscode** 2019-02-07 14:03 UTC
