### ISSUE TITLE
state & position of button bar / state (visible/hidden) is not (re-)stored after restart

### ISSUE THREAD

**Issue by abma** [mRemoteNG/mRemoteNG#358] opened 2017-01-23 17:05 UTC
|||
|--:|---|
|Operating system | Windows Server 2008 R2 x64 |
|mRemoteNG version| 1.75 beta 3  |

To reproduce:
deselect view->direct-connect bar 
save config

restart mRemote:

direct-connect bar is visible again.

**Comment by kmscode** [comment] 2017-01-23 18:06
Could you please clarify? I don't have an option for direct-connect bar. Do you mean "Quick Connect Toolbar"?

Screen shot if needed.

Regards.

**Comment by abma** [comment] 2017-01-23 22:09
yes, i meant "Quick Connect Toolbar".  i translated the localized back to english and failed it seems, sorry :-|

**Comment by abma** [comment] 2017-01-23 22:10
not sure if relevant: i'm using the portable version.

**Comment by kmscode** [comment] 2019-03-10 01:50
duplicate of #264. no longer able to reproduce. closing.

**Closed by kmscode** 2019-03-10 01:50 UTC
Labels: Cannot Reproduce, Duplicate, UI/UX
