### ISSUE TITLE
RDP problem on Windows build 27729

### ISSUE THREAD

**Issue by JustBeta** [mRemoteNG/mRemoteNG#2647] opened 2024-10-23 07:11 UTC
For information,

I'm an insider, I have the latest build of Windows 11, the 27729.
mRemoteNG, no longer works properly on this version.
indeed, if you try to open 2 RDP sessions, mRemoteNG crashes.
it works very well for one RDP session, but as soon as the second one opens, it crashes.
The problem does not occur in SSH or web session.
it seems that the problem is with the event handler, but not knowing enough about the mRemoteNG code, I can't confirm.

For the moment nothing works, all versions combined, even the latest version of git.

so be patient before installing build 27729 or used in a VM.

JoBar.

**Comment by chadbrochills** [comment] 2024-10-23 13:42
This started happening to me this week as well. Really, really annoying.

I'm also running Windows 11 Insider Preview Build 27729

Event Viewer log:

Faulting application name: mRemoteNG.exe, version: 1.76.20.24669, time stamp: 0x5cb095bd
Faulting module name: mstscax.dll, version: 10.0.27729.1000, time stamp: 0xc04fb3e7
Exception code: 0xc0000409
Fault offset: 0x001a1c84
Faulting process id: 0x64FC
Faulting application start time: 0x1DB254DB374D6F5
Faulting application path: C:\Users\XXXX\Downloads\mRemoteNG-Portable-1.76.20.24669\mRemoteNG.exe
Faulting module path: C:\WINDOWS\system32\mstscax.dll
Report Id: ee74438d-790a-4763-bc0e-1a5a5683f279
Faulting package full name: 
Faulting package-relative application ID:

**Comment by simonai1254** [comment] 2024-10-23 13:57
Just for my interest: Are you able to open up two concurrent RDP sessions with the onboard utilities? 

It seems like Microsoft bricked something, the question is what and if it was done intentionally...

**Comment by JustBeta** [comment] 2024-10-23 14:54
yes, it is possible to open 2 or more RDP sessions to other computers of course.

I connect partly like this today and the other party via a VM and mRemoteNG.

JoBar.

**Comment by chadbrochills** [comment] 2024-10-23 15:39
> Just for my interest: Are you able to open up two concurrent RDP sessions with the onboard utilities?
> 
> It seems like Microsoft bricked something, the question is what and if it was done intentionally...

I'm not an mRemote power user by any means, lol, so I'm not sure what onboard utilities you mean?

**Comment by JustBeta** [comment] 2024-10-23 15:45
It seems that the problem is related to the handling of events when using mstscax.dll
to do an equivalent test, you would have to use this DLL to compare 

JoBar.

**Comment by sduquette-devolutions** [comment] 2024-10-30 23:26
Just to further confirm that the problem is on Microsoft's side, we also have users reporting similar crashes in mstscax.dll in our product (Remote Desktop Manager) with build 27729.

**Comment by JustBeta** [comment] 2024-10-31 03:49
As an insider, I had also reported the problem to Microsoft.
Thanks for the confirmation.

**Comment by VShawn** [comment] 2024-11-04 07:56
I got some user reports too: https://github.com/1Remote/1Remote/issues/740

**Comment by JustBeta** [comment] 2024-11-04 08:14
Hi everybody,

to do a test and be able to wait for the next build.
I replaced the mstscax.dll DLL with the one contained in the 24h2 version (version 10.0.26100.2161).
mRemoteNG has returned to normal operation.
I haven't noticed any failure for the moment.

JoBar.

**Comment by chadbrochills** [comment] 2024-11-04 17:11
> Hi everybody,
> 
> to do a test and be able to wait for the next build. I replaced the mstscax.dll DLL with the one contained in the 24h2 version (version 10.0.26100.2161). mRemoteNG has returned to normal operation. I haven't noticed any failure for the moment.
> 
> JoBar.

Anyway you can share that file?

**Comment by JustBeta** [comment] 2024-11-05 05:30
Hello world

Here is the file concerned.
[mstscax.zip](https://github.com/user-attachments/files/17627397/mstscax.zip)

**Comment by Kvarkas** [comment] 2024-11-05 11:16
Hi there, I am on insider windows 11 (27729.1000) dont spoted such problem but I do regural updates :)
We dont supply this file as its part of windows anyway, but just FYI a compare that version you attached and mine in a system: 
![image](https://github.com/user-attachments/assets/b886bc9d-fcba-44ae-b4c4-dde08e292ddb)

**Comment by JustBeta** [comment] 2024-11-05 11:23
Hi,
Weird, I also have this version and I also do all the updates.
And I have the problem.
So if it's not related to the DLL, it must be related to the DLL's registration or the registry keys that it uses.

JoBar.

**Comment by JustBeta** [comment] 2024-11-05 11:37
To confirm that we are talking about the same DLL, I provide my hashes

For 10.0.26100.2161 <= it's ok with this one
2dcef8bc8de358bfe4bc62a13f3e1905

For 10.0.27729.1000 <= it's nok with this one
1eb44bc996ee1fdc3d7cfeb8f08d20bd

Command used:
certutil.exe -hashfile mstscax.dll MD5

**Comment by Kvarkas** [comment] 2024-11-05 12:40
```
PS C:\Windows\System32> certutil.exe -hashfile mstscax.dll MD5
MD5 hash of mstscax.dll:
1eb44bc996ee1fdc3d7cfeb8f08d20bd
CertUtil: -hashfile command completed successfully.
```
just to be sure we are cheking in system32 folder? As I found another one in C:\Windows\SysWOW64 and its a bit different:
![image](https://github.com/user-attachments/assets/1b0a7b35-615d-4fab-8ef0-7b9491218b2b)

its also a bit smaller: 
```
PS C:\Windows\SysWOW64> certutil.exe -hashfile mstscax.dll MD5
MD5 hash of mstscax.dll:
89c6f09cc24a513f22a7087d53572699
CertUtil: -hashfile command completed successfully.
```
and I am not sure tbh whitch one its used :/

**Comment by Kvarkas** [comment] 2024-11-05 12:42
@VShawn could you please check on you end as well? I am sure its not problem with our code its something with M$ code but unsure what exactly version have issues with

**Comment by JustBeta** [comment] 2024-11-05 12:52
here is the md5 of my dll located in 'C:WindowsSysWOW64'

Microsoft Windows [version 10.0.27729.1000]
(c) Microsoft Corporation. Tous droits réservés.

C:\Windows\SysWOW64>certutil.exe -hashfile mstscax.dll MD5
Hachage MD5 de mstscax.dll :
89c6f09cc24a513f22a7087d53572699
CertUtil: -hashfile La commande s’est terminée correctement.

C:\Windows\SysWOW64>

FYI, I'm sure I'm using the DLL located in 'C:WindowsSystem32'. It's the only one I replaced to get it working properly.

**Comment by VShawn** [comment] 2024-11-06 06:09
sure 

## my Win10 22H2 

### C:\Windows\System32

file version: 10.0.19041.4780
hash: 7fc9f90f9e25e5362c4b36aeb17ae3e6

### C:\Windows\SysWOW64

file version: 10.0.19041.4780
hash: aa03c8cf0eb032dd4df3409bca736836



## Win11 23H2 22631.4317

### C:\Windows\System32


file version: 10.0.22621.4317
hash: 50c18647efac06670496999eb4c05827

### C:\Windows\SysWOW64

file version: 10.0.22621.4317
hash: 967375ddbc3b5b0f1ee4f0555187e53b

---

P.S. I dont have a Win11 insider

**Comment by JustBeta** [comment] 2024-11-06 06:37
it is then possible that the problem is with a parameter in the registry, since the problem is not related to the version of the DLL.
At least it seems to me.

**Comment by Kvarkas** [comment] 2024-11-06 11:21
something realy strange, need to investigate, will try to deploy fresh w10 and w11 to my lab to check with fresh installs if will be able to catch this

**Comment by awakecoding** [comment] 2024-11-06 21:50
It looks like this is a bug affecting build 27729 that may have been fixed in build 27744: https://blogs.windows.com/windows-insider/2024/11/06/announcing-windows-11-insider-preview-build-27744-canary-channel/

"Fixed an issue causing remote desktop connection (mstsc.exe) to crash in the previous flight."

**Comment by Kvarkas** [comment] 2024-11-07 00:29
Will see...
![image](https://github.com/user-attachments/assets/b25e8cd3-bf21-4b8e-847a-be77467f2fd5)

**Comment by JustBeta** [comment] 2024-11-07 06:05
Hi everyone,
The problem is identical on build 27744.
on opening 2 RDP sessions mRemoteNG crash.
Here is the content of the event:
Nom de l'application défaillante : mRemoteNG.exe, version : 1.77.3.1784, horodatage : 0x63cf74d2
Nom du module défaillant : mstscax.dll, version : 10.0.27744.1000, horodatage : 0x17b6c171
Exception code: 0xc0000409
Fault offset: 0x0000000000001d91
Identifiant du processus défaillant : 0x61B4
Heure de début de l'application défaillante : 0x1DB30D8D7DA7152
Chemin de l'application défaillante : C:\Program Files\mRemoteNG\mRemoteNG.exe
Chemin du module défaillant : C:\WINDOWS\system32\mstscax.dll
ID du rapport : 77617d65-5bd7-4667-a0ee-cb2dc2c06b18
Nom complet du package défaillant : 
Package défaillant – ID d'application relatif : 

However, by replacing the mstscax.dll DLL (10.0.27744.1000) with the 24H2 version DLL (10.0.26100.2161), it works normally.

JoBar.

**Comment by JustBeta** [comment] 2024-11-14 06:00
Hi everyone,
The problem is identical on build 27749.

JoBar.

**Comment by JustBeta** [comment] 2024-11-14 06:10
Microsoft's response on the Hub:
![image](https://github.com/user-attachments/assets/bade4536-fadc-4705-acc2-119ac65d2b12)

**Comment by JustBeta** [comment] 2024-11-21 05:38
Hi everyone,

For information, it's ok on build 27754.
Microsoft fixed the issue

JoBar.

**Comment by Kvarkas** [comment] 2024-11-21 12:03
Thanks for update!

**Closed as completed by Kvarkas** 2024-11-21 12:03 UTC
Labels: Cannot Fix, RDP, Third party, Windows, 1.77.3
