### ISSUE TITLE
Update PuttyNG because very old 0.71.0.1

### ISSUE THREAD

**Issue by Neustradamus** [mRemoteNG/mRemoteNG#2028] opened 2021-08-21 17:52 UTC
The last "mRemoteNG.24062021NB.rar" has PuttyNG 0.71.0.1.

Can you update, currently it is 0.76.

**Comment by farosch** [comment] 2021-08-22 16:59
Closing this as a duplicate of #2012.
Please follow this issue for status updates.
The PuTTY version you are using is v0.71 because of the long time there has not been any release. (See #2023)

**Closed as completed by farosch** 2021-08-22 16:59 UTC

**Comment by Neustradamus** [comment] 2021-08-22 17:19
@farosch: PuTTY 0.71 (released 2019-03-16): 
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

More 2 years...
A lot of CVEs...

**Comment by Neustradamus** [comment] 2023-08-17 00:54
Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2271
- https://github.com/mRemoteNG/mRemoteNG/issues/2441
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2458
- https://github.com/mRemoteNG/mRemoteNG/issues/2474

**Comment by Neustradamus** [comment] 2023-10-16 20:58
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment] 2023-10-16 21:03
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
