### ISSUE TITLE
MRemote unstable keep crashing 

### ISSUE THREAD

**Issue by amousa1968** [mRemoteNG/mRemoteNG#1138] opened 2018-10-11 00:32 UTC
Windows 7 Enterprise, with sp 1
Log Name:      Application
Source:        Application Error
Date:          10/10/2018 2:01:09 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      HPSAZ75FUJ36.dev1.honeywell.com
Description:
Faulting application name: mRemoteNG.exe, version: 1.76.10.42392, time stamp: 0x5bba97b2
Faulting module name: ntdll.dll, version: 6.1.7601.23915, time stamp: 0x59b94a16
Exception code: 0xc0000005
Fault offset: 0x0002e49b
Faulting process id: 0x1bf4
Faulting application start time: 0x01d460bea5f47248
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\Windows\SysWOW64\ntdll.dll
Report Id: 9c0cbeee-cccf-11e8-a965-005056a21a83
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-10-10T21:01:09.000000000Z" />
    <EventRecordID>382594</EventRecordID>
    <Channel>Application</Channel>
    <Computer>HPSAZ75FUJ36.dev1.honeywell.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>mRemoteNG.exe</Data>
    <Data>1.76.10.42392</Data>
    <Data>5bba97b2</Data>
    <Data>ntdll.dll</Data>
    <Data>6.1.7601.23915</Data>
    <Data>59b94a16</Data>
    <Data>c0000005</Data>
    <Data>0002e49b</Data>
    <Data>1bf4</Data>
    <Data>01d460bea5f47248</Data>
    <Data>C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe</Data>
    <Data>C:\Windows\SysWOW64\ntdll.dll</Data>
    <Data>9c0cbeee-cccf-11e8-a965-005056a21a83</Data>
  </EventData>
</Event>
 
 
 
 
 
Regards,
Ayman Mousa

**Comment by amousa1968** [comment] 2018-10-12 18:08
Hello,  any update on what I should do to fix the issue?

**Comment by sparerd** [comment] 2018-10-12 20:01
Are you able to consistently cause the crash? What sort of things are you doing in mRemoteNG when the crashes occur?

**Comment by amousa1968** [comment] 2018-10-12 21:30
Yes keeps crashing and I have to restart every few hours.   

Thanks 
Ayman Mousa

**Comment by amousa1968** [comment] 2018-10-20 06:42
Hi @sparerd 
Yes still keep crashing.  Nothing I'm doing than open and use it to rdp, or ssh. After few hours it just crashes  and closes the program.

**Comment by amousa1968** [comment] 2018-10-20 06:51
![image](https://user-images.githubusercontent.com/22202476/47252433-de053200-d3f9-11e8-9670-087fb1ab14ad.png)

**Comment by amousa1968** [comment] 2018-10-20 06:55
the version on the left side from good working mremote on windows 7 enterprise edition with sp 1, and the one to the right side same version but noticed ntdll.dll older version. could this helps?

**Comment by sparerd** [comment] 2018-10-20 13:57
Does the crash provide you a stack trace?

**Comment by amousa1968** [comment] 2018-10-20 20:00
Hi David
I will upload the log file to the ticket.  

Thanks 
Ayman Mousa

**Comment by kmscode** [comment] 2018-10-21 20:57
All exceptions in the log are from September and are likely from a corrupt confCons.xml:

```
2018-09-25 21:27:16,460 [1] ERROR - Load From XML failed!
Unexpected end of file while parsing Name has occurred. Line 389, position 579.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.LoadXmlConnectionData(String connections) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 99
   at mRemoteNG.Config.Serializers.Xml.XmlConnectionsDeserializer.Deserialize(String xml, Boolean import) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\Xml\XmlConnectionsDeserializer.cs:line 49
```

Can you check your event log for the app crash? This usually has the stack trace in in that will look a little bit like the one above.

The problem is highly unlikely to be in "ntdll.dll" as that's a system library which just happens to be the last thing done when the crash occurred (the top of the stack - the problem is usually a bit lower in the stack).

**Comment by amousa1968** [comment] 2018-10-23 05:33
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/2504623/mRemoteNG.log)

**Comment by amousa1968** [comment] 2018-10-26 17:30
Hi @sparerd 
Did you get a chance to view the last attache trace log and crash details?

**Comment by sparerd** [comment] 2018-10-27 21:34
@amousa1968 Can you check your Windows Event Viewer for any related events that occur just before an mRemoteNG crash? The `Application` log is the most likely to have something, however the `System` log may also have details that could be relevant.

**Comment by amousa1968** [comment] 2018-10-30 23:12
Hi @sparerd 
![image](https://user-images.githubusercontent.com/22202476/47756261-9e8edf00-dc5e-11e8-901e-a7835d643a6c.png)

**Comment by sparerd** [comment] 2018-11-01 12:56
I'm not sure what could be causing this issue. The logs don't provide us much context on what is going on, and ntdll is such a core library that anything could have called into it.

@kmscode Any ideas?

**Comment by sparerd** [comment] 2018-11-01 13:19
@amousa1968 Are there any .dmp files for mRemoteNG in `%LOCALAPPDATA%\CrashDumps`?

If so, please email the latest one to support@mremoteng.org

**Comment by farosch** [comment] 2019-10-03 23:28
@amousa1968 Does this problem still occur for you or has it been fixed in the meantime?

**Comment by amousa1968** [comment] 2019-10-04 01:14
Yes.

**Comment by R3dst4r** [comment] 2020-01-23 13:07
Hi,

after updating .NET framework from 4.0 also to 4.8, I am facing the a comparable behaviour. Only difference for me is, that my application crashes on startup after setting up the update-settings.  This issue occurs on current stable and in develop-branch when I was trying to test and fix MySQL-configuration by following issue 1604 (https://github.com/mRemoteNG/mRemoteNG/issues/1604).


Here's one of my dumpfiles:
```
[<userdir>\AppData\Local\CrashDumps\mRemoteNG.exe.14256.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Version 16299 MP (8 procs) Free x86 compatible
Product: WinNt, suite: SingleUserTS
16299.637.x86fre.rs3_release_svc.180808-1748
Machine Name:
Debug session time: Wed Jan 22 11:28:00.000 2020 (UTC + 1:00)
System Uptime: not available
Process Uptime: 0 days 0:00:03.000
................................................................
...
Loading unloaded module list
...
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(37b0.3728): CLR exception - code e0434352 (first/second chance not available)
For analysis of this file, run !analyze -v
eax=00000000 ebx=00000000 ecx=00000005 edx=00000000 esi=00000003 edi=00000003
eip=7709fbdc esp=00efdbe4 ebp=00efdd74 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000206
ntdll!NtWaitForMultipleObjects+0xc:
7709fbdc c21400          ret     14h
```

**Comment by R3dst4r** [comment] 2020-02-06 08:50
For me, I was able to fix the issue:

My first assumption towards .NET framework seems to be wrong. 

I guess the application is checking for **updates** which is **blocked** by our organization's security components. When it fails to contact the updateserver the application crashes.

For us it helped changing the value `<setting name="CheckForUpdatesOnStartup">True</setting>` in file "**mRemoteNG.settings**" to `<setting name="CheckForUpdatesOnStartup">False</setting>`. Now the application launches as usual.


@amousa1968 Maybe this suits your infrastructure?

**Comment by farosch** [comment] 2021-12-14 20:05
Closing as stale and Win7 not being supported any more.

**Closed by farosch** 2021-12-14 20:05 UTC
Labels: Cannot Reproduce
