### ISSUE TITLE
Putty connection

### ISSUE THREAD

**Issue by morphos88** [mRemoteNG/mRemoteNG#459] opened 2017-03-17 07:42 UTC
When i connect to ssh server display in mRemoteNG do not use all of the screen.

To use the entire screen I have to shrink the window and then enlarge it for all connections

|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 Hotfix 1  |

**Comment by kmscode** [comment] 2017-03-17 18:10
Duplicate of #297

**Closed by kmscode** 2017-03-17 18:10 UTC
Labels: Duplicate
