### ISSUE TITLE
Icon followed by connection name instead of icon of play and pause

### ISSUE THREAD

**Issue by Tacioandrade** [mRemoteNG/mRemoteNG#391] opened 2017-02-06 08:49 UTC
Good evening, I would like to ask that if possible add in the options a way that the icon selected for the connection is not only in the tab, but also next to the connection, so that it facilitates the identification of which protocol or which service that connection will give access.

I know it is not a preferred feature for developers, but for me as a user it would help a lot. =)

**Comment by kmscode** [comment] 2017-02-09 15:36
Duplicate of #326 

Please follow that issue for future updates.

**Closed by kmscode** 2017-02-09 15:36 UTC
Labels: Duplicate, Feature Request, UI/UX
