### ISSUE TITLE
Request allow hide menu bar 

### ISSUE THREAD

**Issue by vupv** [mRemoteNG/mRemoteNG#855] opened 2017-12-31 13:43 UTC
Dear 
Pls allow  menu hide bar 

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by sparerd** [comment] 2018-01-29 23:12
Duplicate of #666. Please follow that issue for updates

**Closed by sparerd** 2018-01-29 23:12 UTC
Labels: Duplicate
