### ISSUE TITLE
MremoteNG 1.77.2 About - Changelog - Unhandled exections Error

### ISSUE THREAD

**Issue by DanWorkAcc** [mRemoteNG/mRemoteNG#2230] opened 2022-05-23 10:35 UTC
## Expected Behavior
About - Changelog - Shows current change log

## Current Behavior
An error occurred trying to start process 'https://github.com/mRemoteNG/mRemoteNG/blob/develop/CHANGELOG.md' with working directory 'C:\Program Files\mRemoteNG'. The system cannot find the file specified.

## Steps to Reproduce (for bugs)
1. Help - > About -> Changelog
2. Error

## Context
No big affect just noted issue

## Your Environment
Windows 10 64Bit

Also tried clicking the Report Bug button on the Unhandled Exception Window. This seemingly did nothing ?

**Comment by simonai1254** [comment] 2022-05-23 20:04
Hi

Thanks for the report, even though it looks like it's a duplicate of #2117 (and #2216). This issue should be fixed with 1.77.3 when it's released. 

Regards

**Comment by Kvarkas** [comment] 2022-05-23 20:39
yes, its happened as branch naming has been change, perhaps will add temporary such back to avoid this error

**Closed as completed by Kvarkas** 2022-05-23 20:39 UTC
