### ISSUE TITLE
x64 builds are missing

### ISSUE THREAD

**Issue by Neustradamus** [mRemoteNG/mRemoteNG#2029] opened 2021-08-21 17:56 UTC
Currently there are only x86 builds:
- https://mremoteng.org/download

It is possible to enter now in the "future" with x64 builds too?

Note: The first Windows x64 really used was Windows XP.

**Comment by farosch** [comment] 2021-08-22 16:54
Closed as a duplicate of #915 
Please follow this thread for status updates.
We will begin to release 64bit builds in the very near future! Stay tuned.

**Closed as completed by farosch** 2021-08-22 16:54 UTC
