### ISSUE TITLE
Where is Clipboard Option ?

### ISSUE THREAD

**Issue by Totorman** [mRemoteNG/mRemoteNG#882] opened 2018-02-08 21:46 UTC
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.76.0.36676  |

Hi, i dont remember if it was ever here, but i noticed last days that on some rdp connections i didnt have the copy/paste working. So i checked the rds server options, and all was enabled.

So i checked on connections options in mRemoteNG and on herited things, and i never found the clipboard enable/disable option in the parameters of the connection.

Is it me ? or is it really missing ?
I think it should be in the "Redirect" options.

**Comment by sparerd** [comment] 2018-02-08 22:08
I don't think we have an option to turn it on/off. Sometimes rdpclip.exe on the remote server has issues and needs to be restarted, so that would be something to check.

**Comment by Totorman** [comment] 2018-02-08 22:12
Yes you're right about rdpclip.

I was thinking about this option : 
![image](https://user-images.githubusercontent.com/2000612/36001094-7749a5be-0d25-11e8-96ca-086eb712fb4a.png)

**Comment by sparerd** [comment] 2018-04-18 12:40
Closing as duplicate of #416, but is also implemented in PR #951

Follow both of those for updates

**Closed by sparerd** 2018-04-18 12:40 UTC
Labels: Duplicate
