### ISSUE TITLE
Ability to view RDP connections side by side

### ISSUE THREAD

**Issue by fabio-oliveira-efeo** [mRemoteNG/mRemoteNG#1301] opened 2019-02-06 10:16 UTC
Ability to view RDP connections side by side similar to the Remote Desktop Connection Manager.

**Comment by aplocher** [comment] 2019-02-06 13:13
May be a duplicate of my suggestion #1094

**Comment by kmscode** [comment] 2019-02-07 14:00
Closing as duplicate of #1094 

This will be included in 1.77 - see #1094 for details.

**Closed** 2019-02-07 14:00 UTC
Labels: Duplicate, Enhancement
