### ISSUE TITLE
focus on quick connection panel

### ISSUE THREAD

**Issue by deaDleSs-balLoon** [mRemoteNG/mRemoteNG#471] opened 2017-03-24 07:39 UTC
I have a bug during last half of year or something. 

My typical use of mRemoteNG is such: I enter a host name in a quick connection panel, then I work in a newly opened tab, then I set focus with mouse to the text field on a quick connection panel and I enter an another host name and then I open an another tab etc.
So here is the bug: after opening new tab (it is ssh-session for me in most cases) and doing something in it, I click in quick connection panel text field and begin to type. But focus doesn't switch to quick connection panel, it remains in my tab, so I type in ssh session. To get focus moved to the quick panel I need to click on another tab title or on a word "Connection" in the quick panel and then again on the text field. After that I can type into it.
I had this bug on Windows 7 x64, then I upgraded to Win10. I installed several versions of mRemoteNG. I removed every file that I considered related to mRemoteNG, I reinstalled, I tried every setting. No luck. 
And it is the same on my home PC and at work.

What am I doing wrong? For now I use mRemote3G, it does not have this bug, but it crashes from time to time and is not developped anymore...

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7002.26449  |

**Comment by kmscode** [comment] 2017-03-24 19:05
Duplicate of #176 

Please follow that issue for further updates.

**Closed by kmscode** 2017-03-24 19:05 UTC
Labels: Duplicate
