### ISSUE TITLE
mRemoteNG v1.75 & v1.76 Alpha 5 sometimes Unexpected Crashes on New RDP Connections

### ISSUE THREAD

**Issue by IvanYC** [mRemoteNG/mRemoteNG#930] opened 2018-03-30 01:15 UTC
## Expected Behavior
mRemoteNG v1.75 & v1.76 Alpha 5 sometimes Unexpected Crashes on New RDP Connections

## Current Behavior
mRemoteNG v1.75 & v1.76 Alpha 5 sometimes Unexpected Crashes on New RDP Connections

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Sometimes Unexpected Crashes on New RDP Connections.

## Context
Failed Application Name: mRemoteNG.exe, Version: 1.76.3.32991, Timestamp: 0x5aa9bc20
Failure of the module name: Windows.UI.XamlHost.dll, version: 10.0.16299.15, timestamp: 0x133cf20e
Exception status code: 0xc0000409
Error displacement: 0x00005929
Failed Handler Identification Number: 0x2134
Failed application start time: 0x01d3c4c33d718393
Failed application path: C:\Data\Tools\mRemoteNG\mRemoteNG.exe
Failed module path: C:\Windows\System32\Windows.UI.XamlHost.dll
Report identification number: 693ca16e-48b2-46de-9bb3-699a699132e1
Failed suite full name:
Failed suite-related application identifiers:

## Your Environment
* Version used: Both of mRemoteNG v1.75 & v1.76 Alpha 5 
* Operating System and version Windows 10 1709 x64

**Comment by tarund** [comment] 2018-04-19 12:05
I've experienced this as well. Files attached.

**Application Error entry:**
Faulting application name: mRemoteNG.exe, version: 1.75.7012.16814, time stamp: 0x5a21814f
Faulting module name: Windows.UI.XamlHost.dll, version: 10.0.16299.15, time stamp: 0x133cf20e
Exception code: 0xc0000409
Fault offset: 0x00005929
Faulting process id: 0x235c
Faulting application start time: 0x01d3d1074b574727
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\Windows\System32\Windows.UI.XamlHost.dll
Report Id: 5b3c9b0e-ef43-4afc-b0ab-1fea563723fd
Faulting package full name: 
Faulting package-relative application ID: 

**Windows Error Reporting:**
Fault bucket 1195841323122461092, type 5
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: mRemoteNG.exe
P2: 1.75.7012.16814
P3: 5a21814f
P4: Windows.UI.XamlHost.dll
P5: 10.0.16299.15
P6: 133cf20e
P7: 00005929
P8: c0000409
P9: 00000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER27A5.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3294.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER32A2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER32D1.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_mRemoteNG.exe_29922ac83c9a954e45be9cd7292a6686fcfb5872_5d561956_005e3726

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5b3c9b0e-ef43-4afc-b0ab-1fea563723fd
Report Status: 268435456
Hashed bucket: 83440f071f50767e80987b58f87289a4


[AppCrash_mRemoteNG.zip](https://github.com/mRemoteNG/mRemoteNG/files/1928005/AppCrash_mRemoteNG.zip)

**Comment by sparerd** [comment] 2018-04-19 12:43
@tarund which version of Windows are you running?

**Comment by tarund** [comment] 2018-04-19 12:50
Windows 10, 1709 Build 16299.371 with all of the latest patches and drivers installed.

**Comment by janis-veinbergs** [comment] 2018-04-25 12:54
I'm getting the same crash. I was connected to RDP session using fullscreen and when trying to break out of fullscreen with CTRL + ALT + PageBreak. However I cannot reproduce it. When it works, it just tries to resize (resolution) my RDP session and immediatelly asks password once again.

Windows 10 Enterprise 1709 x64 Build 16299.371
mRemoteNG slightly different version  1.76.3.32942
Same exact offset for C:\Windows\System32\Windows.UI.XamlHost.dll

Details:
```
Faulting application name: mRemoteNG.exe, version: 1.76.3.32942, time stamp: 0x5aa9bbbf
Faulting module name: Windows.UI.XamlHost.dll, version: 10.0.16299.15, time stamp: 0x133cf20e
Exception code: 0xc0000409
Fault offset: 0x00005929
Faulting process id: 0x195c
Faulting application start time: 0x01d3daf3ce1f8ffe
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\Windows\System32\Windows.UI.XamlHost.dll
Report Id: f1417f9b-9a47-4900-99fe-311aaf4edb36
Faulting package full name: 
Faulting package-relative application ID: 
```
Don't have any dump files.

**Comment by janis-veinbergs** [comment] 2018-05-02 09:04
I have acquired 2 dump files on these crashes that occurred today and on 27.04. If someone wants to lead me how to get additional info, you are welcome. However I would rather not share the dump file itself as it could contain sensitive information.

Sorry, I don't know the relevant bits someone might be interested in, but i'll paste some.

```
Thread 378 - System ID 12576
Entry point | SHCore!_WrapperThreadProc
-- | --
Create time | 27.04.2018 15:01:58
Time spent in user mode | 0 Days 00:00:00.015
Time spent in kernel mode | 0 Days 00:00:00.000

 
--
Windows_UI_XamlHost!wil::details::ReportFailure+c6
Windows_UI_XamlHost!wil::details::ReportFailure_Hr+21
Windows_UI_XamlHost!wil::details::in1diag3::_FailFast_Hr+19
Windows_UI_XamlHost!XAMLHostWindowImpl::Start+2a0
Windows_UI_XamlHost!Microsoft::WRL::SimpleActivationFactory<XAMLHostWindowImpl,0>::ActivateInstance+143
Windows_UI_XamlHost!ASTAThreadHost::ASTAThreadHostStartThreadProc+4f
Windows_UI_XamlHost!ASTAThreadHost::s_ASTAThreadHostStartThreadProc+41
SHCore!_WrapperThreadProc+aa
kernel32!BaseThreadInitThunk+24
ntdll!__RtlUserThreadStart+2f
ntdll!_RtlUserThreadStart+1b
```

```
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(5258.3120): Security check failure or stack buffer overrun - code c0000409 (first/second chance not available)
eax=00000001 ebx=6cf0b700 ecx=00000007 edx=00790968 esi=00000003 edi=00000000
eip=6cf05929 esp=2e7ae7b0 ebp=2e7afc20 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
Windows_UI_XamlHost!wil::details::ReportFailure+0xc6:
6cf05929 cd29            int     29h

```

**Comment by hohokus** [comment] 2018-07-11 21:50
same issue for me.  mRemote 1.75.7012.16846 on windows 10 enterprise 1709 (10.0.16299, 16299.15).  used DebugDiag, points to the same Windows.UI.XamlHost.dll.

occurs randomly, cannot reproduce, but does seem to happen when opening a new RDP connection.

[mRemoteNG.exe.12412_CrashHangAnalysis.zip](https://github.com/mRemoteNG/mRemoteNG/files/2186312/mRemoteNG.exe.12412_CrashHangAnalysis.zip)

**Comment by hohokus** [comment] 2018-07-11 22:02
https://github.com/mRemoteNG/mRemoteNG/issues/853 appears to be the same crash.

**Comment by g3m1n1-usa** [comment] 2018-09-06 21:05
This same crash happens to me about once a day, sometimes more. I will usually have one to three, sometimes five to eight connections active and the crash happens when I double-click a Connection entry to open a new connection.

Running mRemoteNG v1.76.8.17254 and Windows 10 Enterprise v1803 OS build 17134.228.

Faulting application name: mRemoteNG.exe, version: 1.76.8.17254, time stamp: 0x5b81772e
Faulting module name: Windows.UI.XamlHost.dll, version: 10.0.17134.191, time stamp: 0x5451dff6
Exception code: 0xc0000409
Fault offset: 0x000058cf
Faulting process id: 0x1708
Faulting application start time: 0x01d4455ba64c22cd
Faulting application path: C:\Users\Bret Hicks\Work\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\Windows\System32\Windows.UI.XamlHost.dll
Report Id: 172beb0b-1c52-41fe-be2d-41108d84dd33
Faulting package full name: 
Faulting package-relative application ID:

**Comment by sparerd** [comment] 2018-09-30 14:56
I'm going to close this as a duplicate of #853 so we can have a single place for troubleshooting this crash. Please follow that issue for updates

**Closed by sparerd** 2018-09-30 14:56 UTC
Labels: Bug, Duplicate
