### ISSUE TITLE
nightly Build suggests Update to Stable Version what would be a downgrade

### ISSUE THREAD

**Issue by enrixxel** [mRemoteNG/mRemoteNG#2432] opened 2023-05-04 05:50 UTC
## Expected Behavior
Nightly Build Version suggest Update to new nightly build.

## Current Behavior
![image](https://user-images.githubusercontent.com/59911891/236121200-63669c03-1153-4a3c-a962-216a0c00250c.png)
It suggest a "downgrade" but calls it upgrade. When i start it, it will fail with the error "a newer version is allready installed."

## Possible Solution
make a setting to change the update path

## Steps to Reproduce (for bugs)
1.install the nightly build
2. start the programm
3. the "Update avivable" page will open automatically 

## Your Environment
Windows 11 x64 22H2 Build 22621 (German)
mRemoteNG Version 1.77.3 Nightly Build 1784

**Comment by simonai1254** [comment] 2023-05-04 11:06
Thanks for reporting this, even though this issue is a duplicate of #1853.

**Closed as completed** 2023-05-05 15:48 UTC
