### ISSUE TITLE
Putty connection names encoding

### ISSUE THREAD

**Issue by jelinj8** [mRemoteNG/mRemoteNG#968] opened 2018-04-26 10:56 UTC
PuTTY connection created with Putty named "Pyšely", "ostrá"... produce unknown characters in connection list

## Expected Behavior
original characters expected

## Current Behavior
question marks in place of accented characters

## possible workaround
+ an option to set codepage for setting from registry?

## Your Environment
* Version used: 1.75.7012.16846
* Operating System and version Windows 10 1709 x64, Czech (probably win-1250 in registry)

**Comment by LIyoai** [comment] 2018-04-27 12:51
Is it related to https://github.com/mRemoteNG/mRemoteNG/issues/800?
This is fixed in 1.76 Alpha2. Maybe worth a try.

**Comment by kmscode** [comment] 2018-07-29 14:06
closing as duplicate of #800

**Closed by kmscode** 2018-07-29 14:06 UTC
Labels: Duplicate
