### ISSUE TITLE
Cannot Change Password for Encryption / Possible Connection File Corruption?

### ISSUE THREAD

**Issue by rgibsonohmh** [mRemoteNG/mRemoteNG#380] opened 2017-01-30 21:04 UTC
|Operating system | Windows 8.1 x64 |
|mRemoteNG version| 1.74.6023.15437  |

Recently, I was working with a tree of connections which had been saved in the new version of mRemoteNG (I had been using the old VB version).  At one point, my system crashed.  When I restarted, I launched mRemoteNG to have a password prompt displayed.  I had not set an encryption password on the connection file.

I then moved the old connection file out of the way and started a new one.  From here, I continued to save the file to disk regularly.  Again, I get a system crash, and when I restart and relaunch mRemote, I get the same password prompt.

I am concerned about the possibility of corruption of the file, as I had saved changes to my connections hours prior to the system reboot.  By having a mechanism for confirming the password associated with a connection file, I hope to rule out password issues and determine whether or not it is a file corruption issue.

**Comment by kmscode** [comment] 2017-01-30 21:22
Duplicate of #340 

Yes it is currently possible for the file to not be saved properly and/or be corrupted in a system (or even process) crash scenario. 

I've scheduled #340 for the release after next - 1.76 - (since the next release - 1.75 - is feature complete and currently in release candidate stage).

**Comment by kmscode** [comment] 2017-01-30 21:22
@rgibsonohmh Feel free to upvote the other issue to be notified of any future comments/status on it.

**Closed by kmscode** 2017-01-30 21:22 UTC
Labels: Duplicate
