### ISSUE TITLE
Connection list gets blank after opening directory with lot of connections

### ISSUE THREAD

**Issue by qmpeltaty** [mRemoteNG/mRemoteNG#771] opened 2017-11-03 10:48 UTC
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010.21169  |

I have two directories in my connection tree with at least 20-30 connections inside and also some subdirectories. When i click to expand it's fine. When i click on "-" to roll it back,  all connections are gone. I have to restart mremote to get connection list again.

**Comment by sparerd** [comment] 2017-11-03 17:45
I believe this is a duplicate of #763. A fix for this will be released in the next few days. You can also try https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011.r1 now if you want

**Closed** 2017-11-07 22:39 UTC
Labels: Bug, Duplicate
