### ISSUE TITLE
Crash when close many session in the same tab

### ISSUE THREAD

**Issue by alpa80** [mRemoteNG/mRemoteNG#1617] opened 2019-10-08 14:42 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment] 2019-10-09 21:59
Duplicate of #1286

**Closed by farosch** 2019-10-09 21:59 UTC
