### ISSUE TITLE
[FR][Working Directory] Specifiy a working directory without needing an external app

### ISSUE THREAD

**Issue by Juntrimp** [mRemoteNG/mRemoteNG#1027] opened 2018-07-18 15:11 UTC
## Current Behavior
The Working Directory may be populated with arbitrary data, however the Filename is mandatory and must be a valid path to an executable.

## Possible Solution
Allow a working directory to be specified without mandating an external tool. Similar to how Remote Desktop Connection Manager permits this.

![2018-07-18_105758](https://user-images.githubusercontent.com/27321038/42890469-ee2004c6-8a7a-11e8-84e4-c9c34a85bcf8.png)

## Context
The Skytap hosting service supports RDP connections to cloud-hosted VMs, but all connections are to skytap.com hostname (e.g., smart-uswest.skytap.com). They have an encrypted blob of metadata specified in the Working Directory, which includes the actual host that you're connecting to as well as authentication details.

**Comment by sparerd** [comment] 2018-07-18 17:53
Although this is a slightly different use case, this appears to be a duplicate of #327. That "working dir" field corresponds to the `shell working directory:s:` RDP parameter.

I am going to close this request as a duplicate. Please follow #327 for further updates

**Closed by sparerd** 2018-07-18 17:53 UTC
Labels: Duplicate, Enhancement
