### ISSUE TITLE
Autosave configuration on change

### ISSUE THREAD

**Issue by erpico** [mRemoteNG/mRemoteNG#490] opened 2017-04-06 15:42 UTC
Please add option to save configuration on changes.
I forgot to press Ctrl+S after every change and miss configuration changes on crashes or APP\PC restart.

**Comment by kmscode** [comment] 2017-04-06 15:59
Duplicate of #340 - Please upvote/follow that issue for further updates.

**Closed by kmscode** 2017-04-06 15:59 UTC
Labels: Duplicate
