### ISSUE TITLE
Terminal text left margin is past the terminal area

### ISSUE THREAD

**Issue by otiecoyote** [mRemoteNG/mRemoteNG#1172] opened 2018-11-01 19:02 UTC
## Expected Behavior

Expecting to see the full first character of a line. Edited the putty options to no avail
## Current Behavior

A pixel or two  of the first character in a line gets cut off.
## Possible Solution

The setting within: Putty Options -> Window -> Appearance -> Adjust Window Border -> Set gap between text and window edge: could possibly be used to allow an adjustment
## Steps to Reproduce (for bugs)

1.open an existing or new saved session. 
2.
3.
4.

## Context

Very minor, but the issue becomes distracting.
## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Happened when I upgraded mRemoteNG to Version 1.76.11.40527
Windows 7 SP1 x64

**Comment by sparerd** [comment] 2018-11-05 17:53
So far I haven't been able to replicate this issue. Still looking into it.

**Comment by sparerd** [comment] 2018-11-06 14:47
@otiecoyote Are there any other details you can provide about your putty/mremoteng setup? I have not been able to replicate the display issue you've described using the following settings:

- Win7 SP1 x86
- mRemoteNG (portable): 1.76.11.40592
- mRemoteNG (installed): 1.76.11.40527
- PuTTYNG (default, no changes to default session configuration)
- Themes disabled/enabled

**Comment by otiecoyote** [comment] 2018-11-15 01:58
Here are the reg settings for the session Im using.. It's been copied with minor changes for other sessions, but only the colors were changed.. The issue happened on this and all other copied settings.
In HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\ : 

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\Default%20Settings]
"Present"=dword:00000001
"HostName"=""
"LogFileName"="putty.log"
"LogType"=dword:00000000
"LogFileClash"=dword:ffffffff
"LogFlush"=dword:00000001
"SSHLogOmitPasswords"=dword:00000001
"SSHLogOmitData"=dword:00000000
"Protocol"="ssh"
"PortNumber"=dword:00000016
"CloseOnExit"=dword:00000001
"WarnOnClose"=dword:00000001
"PingInterval"=dword:00000004
"PingIntervalSecs"=dword:00000000
"TCPNoDelay"=dword:00000001
"TCPKeepalives"=dword:00000000
"TerminalType"="xterm"
"TerminalSpeed"="38400,38400"
"TerminalModes"="CS7=A,CS8=A,DISCARD=A,DSUSP=A,ECHO=A,ECHOCTL=A,ECHOE=A,ECHOK=A,ECHOKE=A,ECHONL=A,EOF=A,EOL=A,EOL2=A,ERASE=A,FLUSH=A,ICANON=A,ICRNL=A,IEXTEN=A,IGNCR=A,IGNPAR=A,IMAXBEL=A,INLCR=A,INPCK=A,INTR=A,ISIG=A,ISTRIP=A,IUCLC=A,IUTF8=A,IXANY=A,IXOFF=A,IXON=A,KILL=A,LNEXT=A,NOFLSH=A,OCRNL=A,OLCUC=A,ONLCR=A,ONLRET=A,ONOCR=A,OPOST=A,PARENB=A,PARMRK=A,PARODD=A,PENDIN=A,QUIT=A,REPRINT=A,START=A,STATUS=A,STOP=A,SUSP=A,SWTCH=A,TOSTOP=A,WERASE=A,XCASE=A"
"AddressFamily"=dword:00000000
"ProxyExcludeList"=""
"ProxyDNS"=dword:00000001
"ProxyLocalhost"=dword:00000000
"ProxyMethod"=dword:00000000
"ProxyHost"="proxy"
"ProxyPort"=dword:00000050
"ProxyUsername"=""
"ProxyPassword"=""
"ProxyTelnetCommand"="connect %host %port\\n"
"Environment"=""
"UserName"=""
"UserNameFromEnvironment"=dword:00000000
"LocalUserName"=""
"NoPTY"=dword:00000000
"Compression"=dword:00000000
"TryAgent"=dword:00000001
"AgentFwd"=dword:00000000
"GssapiFwd"=dword:00000000
"ChangeUsername"=dword:00000000
"Cipher"="aes,chacha20,blowfish,3des,WARN,arcfour,des"
"KEX"="ecdh,dh-gex-sha1,dh-group14-sha1,rsa,dh-group1-sha1,WARN"
"RekeyTime"=dword:0000003c
"RekeyBytes"="1G"
"SshNoAuth"=dword:00000000
"SshBanner"=dword:00000001
"AuthTIS"=dword:00000000
"AuthKI"=dword:00000001
"AuthGSSAPI"=dword:00000001
"GSSLibs"="gssapi32,sspi,custom"
"GSSCustom"=""
"SshNoShell"=dword:00000000
"SshProt"=dword:00000003
"LogHost"=""
"SSH2DES"=dword:00000000
"PublicKeyFile"=""
"RemoteCommand"=""
"RFCEnviron"=dword:00000000
"PassiveTelnet"=dword:00000000
"BackspaceIsDelete"=dword:00000000
"RXVTHomeEnd"=dword:00000000
"LinuxFunctionKeys"=dword:00000000
"NoApplicationKeys"=dword:00000000
"NoApplicationCursors"=dword:00000000
"NoMouseReporting"=dword:00000000
"NoRemoteResize"=dword:00000000
"NoAltScreen"=dword:00000000
"NoRemoteWinTitle"=dword:00000000
"RemoteQTitleAction"=dword:00000001
"NoDBackspace"=dword:00000000
"NoRemoteCharset"=dword:00000000
"ApplicationCursorKeys"=dword:00000000
"ApplicationKeypad"=dword:00000000
"NetHackKeypad"=dword:00000000
"AltF4"=dword:00000001
"AltSpace"=dword:00000000
"AltOnly"=dword:00000000
"ComposeKey"=dword:00000000
"CtrlAltKeys"=dword:00000001
"TelnetKey"=dword:00000000
"TelnetRet"=dword:00000001
"LocalEcho"=dword:00000002
"LocalEdit"=dword:00000002
"Answerback"="PuTTY"
"AlwaysOnTop"=dword:00000000
"FullScreenOnAltEnter"=dword:00000000
"HideMousePtr"=dword:00000000
"SunkenEdge"=dword:00000000
"WindowBorder"=dword:00000005
"CurType"=dword:00000000
"BlinkCur"=dword:00000000
"Beep"=dword:00000001
"BeepInd"=dword:00000000
"BellWaveFile"=""
"BellOverload"=dword:00000001
"BellOverloadN"=dword:00000005
"BellOverloadT"=dword:000007d0
"BellOverloadS"=dword:00001388
"ScrollbackLines"=dword:01312d00
"DECOriginMode"=dword:00000000
"AutoWrapMode"=dword:00000001
"LFImpliesCR"=dword:00000000
"CRImpliesLF"=dword:00000000
"DisableArabicShaping"=dword:00000000
"DisableBidi"=dword:00000000
"WinNameAlways"=dword:00000001
"WinTitle"=""
"TermWidth"=dword:00000050
"TermHeight"=dword:00000018
"Font"="Courier New"
"FontIsBold"=dword:00000000
"FontCharSet"=dword:00000000
"FontHeight"=dword:0000000a
"FontQuality"=dword:00000000
"FontVTMode"=dword:00000004
"UseSystemColours"=dword:00000000
"TryPalette"=dword:00000000
"ANSIColour"=dword:00000001
"Xterm256Colour"=dword:00000001
"BoldAsColour"=dword:00000000
"Colour0"="0,0,0"
"Colour1"="128,128,128"
"Colour2"="255,255,255"
"Colour3"="192,192,192"
"Colour4"="0,0,0"
"Colour5"="92,92,92"
"Colour6"="0,0,0"
"Colour7"="85,85,85"
"Colour8"="187,0,0"
"Colour9"="255,85,85"
"Colour10"="0,187,0"
"Colour11"="85,255,85"
"Colour12"="187,187,0"
"Colour13"="255,255,85"
"Colour14"="0,0,187"
"Colour15"="85,85,255"
"Colour16"="187,0,187"
"Colour17"="255,85,255"
"Colour18"="0,187,187"
"Colour19"="85,255,255"
"Colour20"="187,187,187"
"Colour21"="255,255,255"
"RawCNP"=dword:00000000
"PasteRTF"=dword:00000000
"MouseIsXterm"=dword:00000000
"RectSelect"=dword:00000000
"MouseOverride"=dword:00000001
"Wordness0"="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
"Wordness32"="0,1,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1"
"Wordness64"="1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,2"
"Wordness96"="1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1"
"Wordness128"="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"
"Wordness160"="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"
"Wordness192"="2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2"
"Wordness224"="2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2"
"LineCodePage"=""
"CJKAmbigWide"=dword:00000000
"UTF8Override"=dword:00000001
"Printer"=""
"CapsLockCyr"=dword:00000000
"ScrollBar"=dword:00000001
"ScrollBarFullScreen"=dword:00000000
"ScrollOnKey"=dword:00000000
"ScrollOnDisp"=dword:00000001
"EraseToScrollback"=dword:00000001
"LockSize"=dword:00000000
"BCE"=dword:00000001
"BlinkText"=dword:00000000
"X11Forward"=dword:00000000
"X11Display"=""
"X11AuthType"=dword:00000001
"X11AuthFile"=""
"LocalPortAcceptAll"=dword:00000000
"RemotePortAcceptAll"=dword:00000000
"PortForwardings"=""
"BugIgnore1"=dword:00000000
"BugPlainPW1"=dword:00000000
"BugRSA1"=dword:00000000
"BugIgnore2"=dword:00000000
"BugHMAC2"=dword:00000000
"BugDeriveKey2"=dword:00000000
"BugRSAPad2"=dword:00000000
"BugPKSessID2"=dword:00000000
"BugRekey2"=dword:00000000
"BugMaxPkt2"=dword:00000000
"BugWinadj"=dword:00000000
"StampUtmp"=dword:00000001
"LoginShell"=dword:00000001
"ScrollbarOnLeft"=dword:00000000
"BoldFont"=""
"BoldFontIsBold"=dword:00000000
"BoldFontCharSet"=dword:00000000
"BoldFontHeight"=dword:00000000
"WideFont"=""
"WideFontIsBold"=dword:00000000
"WideFontCharSet"=dword:00000000
"WideFontHeight"=dword:00000000
"WideBoldFont"=""
"WideBoldFontIsBold"=dword:00000000
"WideBoldFontCharSet"=dword:00000000
"WideBoldFontHeight"=dword:00000000
"ShadowBold"=dword:00000000
"ShadowBoldOffset"=dword:00000001
"SerialLine"="COM1"
"SerialSpeed"=dword:00002580
"SerialDataBits"=dword:00000008
"SerialStopHalfbits"=dword:00000002
"SerialParity"=dword:00000000
"SerialFlowControl"=dword:00000001
"WindowClass"=""
"BugOldGex2"=dword:00000000
"BugChanReq"=dword:00000000
"ConnectionSharing"=dword:00000000
"ConnectionSharingUpstream"=dword:00000001
"ConnectionSharingDownstream"=dword:00000001
"SSHManualHostKeys"=""
"ProxyLogToTerm"=dword:00000001
"HostKey"="ed25519,ecdsa,rsa,dsa,WARN"
"NoRemoteClearScroll"=dword:00000000

![2018-11-14 20_53_56-mremoteng - confcons xml - linux - fedu 3](https://user-images.githubusercontent.com/44681808/48524851-f2e5b180-e84f-11e8-80ef-58158cef27db.png)

**Comment by stufently** [comment] 2018-11-18 06:14
I have same issue in latest release in windows 10

**Comment by stufently** [comment] 2018-11-18 06:24
Same problem in both version Stable v1.76.11 and Prerelease v1.76.12

**Comment by stufently** [comment] 2018-11-18 06:26
![2018-11-18_13-26-00](https://user-images.githubusercontent.com/1324096/48669354-88758f80-eb35-11e8-9609-b971eae24ba5.png)

**Comment by DBonfini** [comment] 2018-12-06 06:55
Hello,

I have the same issue on Windows Server 2008 R2.
I usually use a JP keyboard layout I have just noticed that the problem is not present every time I run it with the ENG layout (in my case UK).
I hope this helps.

**Comment by stufently** [comment] 2018-12-06 07:54
> Hello,
> 
> I have the same issue on Windows Server 2008 R2.
> I usually use a JP keyboard layout I have just noticed that the problem is not present every time I run it with the ENG layout (in my case UK).
> I hope this helps.
> 
> [EDIT]
> Just noticed that it doesn't matter with which keyboard layout you start mRemoteNG, **but with which one you open the connection**.

Big thnx, its really help use ENG keyboad

**Comment by DBonfini** [comment] 2018-12-07 02:41
@kmscode 
Thank you for your suggestion.

In my case:
![mremoteng_putty_issue](https://user-images.githubusercontent.com/45649674/49624488-f9adb180-fa14-11e8-8a70-9b732e732ebc.png)

**Comment by kmscode** [comment] 2019-01-24 02:19
I believe this this may have been fixed with #1265 when PuTTYNG only (other putty builds are not expected to integrate as cleanly).

Feel free to test/validate with the build from appveyor (note that these builds are currently UNSIGNED binaries) - I would recommend testing the portable release unzipped into a different folder as to not impact your main installation or standard portable location:

https://ci.appveyor.com/api/buildjobs/nhd146cxy44y2x5x/artifacts/Release%2FmRemoteNG-Portable-1.77.0.3887.zip

**Comment by xiaoguazh** [comment] 2019-01-24 02:55
@kmscode

Yes, this is now fixed in v1.77, thanks so much !! :-)

I just did a test, see screenshot:

![image](https://user-images.githubusercontent.com/19484664/51651350-7f39f080-1fc6-11e9-8b9e-c824afdde2dd.png)

**Closed** 2019-01-24 13:51 UTC
Labels: Bug, in progress
