### ISSUE TITLE
Issue with returning to a minimized full-screen RDP (after resizing)

### ISSUE THREAD

**Issue by Shaamaan** [mRemoteNG/mRemoteNG#365] opened 2017-01-25 10:52 UTC
I suspect this is a bug, so I'll file it as such.

OS: Windows 10 Ent 1607
mRemoteNG version: 1.74.6023.15437

I prefer my RDP connections to use full-screen whenever possible. If I connect and ONLY minimize the connection, then everything works fine - mRemoteNG opens the full-screen connection in a separate Windows "window", which gets minimized into the Windows taskbar.

However, if I exit the fullscreen mode (use the resize button rather than the minimize button from the connection window), then the connection gets placed inside the mRemoteNG panel. So far, so good. HOWEVER, if I go back to fullscreen from here and THEN minimize, there is no Windows taskbar "window" to speak of. Returning back to the full-screen connection becomes a chore, as I need to shuffle back and forth between the full-screen settings in mRemoteNG on the connections tab.

Also, it would be awesome if I could just have a connection ALWAYS be a separate "window" (this last bit might be a request, so feel free to ignore it, but it's somewhat tied to the above issue).

EDIT: NVM, it seems like this is a duplicate of an existing bug: https://github.com/mRemoteNG/mRemoteNG/issues/178

**Comment by jcefoli** [comment] 2017-01-25 15:16
Yes. I use fullscreen a lot as well and this is irritating. You found it, same as #178

**Comment by kmscode** [comment] 2017-01-25 15:56
Closing as duplicate of #178 

@Shaamaan please upvote #178 to be notified of future status updates from there.

**Closed by kmscode** 2017-01-25 15:56 UTC
Labels: Duplicate

**Comment by Shaamaan** [comment] 2017-01-26 10:27
kmscode, stupid question, but... how do I upvote issues? O_o

**Comment by kmscode** [comment] 2017-01-26 14:17
Go to #178 and add your reaction to the original comment in the issue:
![image](https://cloud.githubusercontent.com/assets/16654335/22334289/301c0d6e-e3a8-11e6-8500-f4d33173cd17.png)
