### ISSUE TITLE
Can you support VNC4 or more?

### ISSUE THREAD

**Issue by wpf973** [mRemoteNG/mRemoteNG#1280] opened 2019-01-16 02:59 UTC
Can you support VNC4 or more?

VNC 3.3 3.7 3.8 is not available

**Comment by wpf973** [comment] 2019-01-21 13:02
help

**Comment by sparerd** [comment] 2019-01-21 13:31
The only way to allow mRemoteNG to support VNC4+ is to setup VNC viewer as an external app and set your connection to use the `Int App` protocol and select the VNC external tool. The downside of this is that you cannot pass the `Password` property directly to the VNC connection (the [vnc viewer parameter list](https://www.realvnc.com/en/connect/docs/man/vncviewer.html) only specifies the `Username` property).

More details on creating external tools [here](https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools).

More details on our support for RFB protocol versions 4+ [here](https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#vnc-connections-fail-with-the-error-the-server-is-using-an-unsupported-version-of-the-rfb-protocol-the-server-is-using-version-41-but-only-version-3x-is-supported-).

Closing this as a duplicate of #494

**Closed by sparerd** 2019-01-21 13:31 UTC
Labels: Duplicate, Enhancement
