### ISSUE TITLE
ERROR- Couldn't save connections file! Decryption failed. {0}

### ISSUE THREAD

**Issue by peanek** [mRemoteNG/mRemoteNG#758] opened 2017-10-30 10:41 UTC
Concerns : 
```
OS ver : Windows Server 2008R2 
mRemoteNG ver : 1.75.7010.21169
```

Happy after seeing that this bug has been fixed ( #529  ), I've started to installing today newest version of mRemoteNG, unfortunately I have this kind of issue below : 

![2017-10-30 11_16_22-mremoteng - sql server](https://user-images.githubusercontent.com/28780396/32165845-63fee2d2-bd64-11e7-84a9-4d1c0a755fbf.png)

The mRemoteNG.log doesn't seem to handle any additional info :
```
2017-10-30 11:18:44,657 [1] INFO - mRemoteNG 1.75.7010.21169 starting.
2017-10-30 11:18:44,657 [1] INFO - Command Line: System.String[]
2017-10-30 11:18:46,841 [1] INFO - Microsoft Windows Server 2008 R2 Standard Service Pack 1 64-bit
2017-10-30 11:18:46,841 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2017-10-30 11:18:46,841 [1] INFO - System Culture: en-US/English (United States)
2017-10-30 11:18:46,841 [1] INFO - Checking FIPS Policy...
2017-10-30 11:18:46,841 [1] INFO - Checking Lenovo AutoScroll Utility...
2017-10-30 11:18:47,590 [1] INFO - Loading External Apps from: C:\Users\ced6adm\AppData\Roaming\mRemoteNG\extApps.xml
2017-10-30 11:18:48,526 [1] WARN - PuttySessions.Watcher.StartWatching() failed.
Not found 
2017-10-30 11:18:48,526 [1] WARN - XmingPortablePuttySessions.Watcher.StartWatching() failed.
The directory name sessions is invalid.
2017-10-30 11:18:48,667 [1] ERROR- GetUpdateInfoCompleted() failed.
The request was aborted: Could not create SSL/TLS secure channel.
2017-10-30 11:18:51,787 [11] ERROR- Couldn't save connections file!
Decryption failed. {0}
2017-10-30 11:18:56,560 [13] ERROR- Couldn't save connections file!
Decryption failed. {0}
```

On my last installation ( 1.75.7008.17907 ) everything worked like a charm. 

Second issue I've noticed so far ( dunno if I can paste it here in other issue :) ). When I use option **"Collapse all folders"** list - this happens.

![2017-10-30 11_16_50-mremoteng - sql server](https://user-images.githubusercontent.com/28780396/32166261-8c996d6a-bd65-11e7-8f29-4bf8c3203597.png)

Restart of mRemoteNG is needed in this case. 

PS. Where Can I find version 7009 to check if the same happens ?

**Comment by AlexBarnas** [comment] 2017-11-03 09:11
Hi peanek,
I have the same problem, With both  v1.75.7010 and PreRelease 1.75.7011.
Did you find the old version yet?

Thanks,
Alex

**Comment by AlexBarnas** [comment] 2017-11-03 09:17
FYI:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8

**Comment by peanek** [comment] 2017-11-03 09:36
Hello, 

All releases are available on : [https://github.com/mRemoteNG/mRemoteNG/releases/](url)

But I haven't tested 1.75.7009 till now...

Anyone know if there was some change in authentication type to SQL in version > 1.75.7008 of mRemote ? 

I forgot to mention, my SQL ver is : Microsoft SQL Server 2014 - 12.0.2000.8 (x64) 
Nothing has changed from the beginning of using mRemote ( more than few versions till now)

**Comment by peanek** [comment] 2017-11-03 10:00
So , 1.75.7009.27822 portable is the same. Something has been changed in SQL authentication after this update ?

![2017-11-03 10_56_13-new 1 - notepad administrator](https://user-images.githubusercontent.com/28780396/32368488-278ab5e0-c086-11e7-9d17-72e99835591b.png)

**Comment by AlexBarnas** [comment] 2017-11-03 11:23
Maybe.
Im using Microsoft SQL Server 2014 - 12.0.5207.0 (x64)

**Comment by EffEss** [comment] 2017-11-03 18:02
Same "Couldn't save connections file! Decryption failed. {0}" error message on SQL Server 2016 (SP1) 13.0.4001.0 (x64) after updating to 7010 build.

**Comment by sparerd** [comment] 2017-11-03 20:08
I've found where the issue was and have fixed it. A fix will be released with 1.75.7011 in the next day or so

**Comment by tomerMP** [comment] 2017-11-07 07:35
I had the same issue. Found this thread, downloaded and installed 1.75.7011, and the issue is no longer...
Thanks for the quick fix!!

**Comment by TechKno** [comment] 2017-11-07 10:07
I'm running version 1.75.7011.26523 and I still have the "Couldn't save connection file! Decryption Failed. {0} error message when trying to make changes.

**Comment by peanek** [comment] 2017-11-07 10:19
> I'm running version 1.75.7011.26523 and I still have the "Couldn't save connection file! Decryption Failed. {0} error message when trying to make changes.

Guys, **sparerd** wrote that he found bug in encryption options few posts ago and will release fix in updated 1.75.7011 in days. So - be patient.

**Comment by sparerd** [comment] 2017-11-08 02:35
v1.75.7011 has been released.
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011

You may need to delete your user.config file if you are still seeing decryption failures

**Closed by sparerd** 2017-11-08 02:35 UTC
Labels: Bug

**Comment by micheleietri** [comment] 2018-11-09 08:02
same error on 1.76.11.40527 win10 x64 1803. I was importing an xml from my old pc (it's a password protected one)
