### ISSUE TITLE
mRemoteNG application error

### ISSUE THREAD

**Issue by akchitty143** [mRemoteNG/mRemoteNG#1695] opened 2020-02-18 21:40 UTC
Application Error

After installation application does not open

verified Event Viewer and here's what I have

Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.17134.1184, time stamp: 0xda43ec6b
Exception code: 0xe0434352
Fault offset: 0x00114622
Faulting process id: 0x2790
Faulting application start time: 0x01d5e6a27ba8d41a
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a889eafd-6811-484e-abc9-b6584e2c5795
Faulting package full name: 
Faulting package-relative application ID: 

please help....Thank you very much

**Comment by mattjereb** [comment] 2020-02-20 00:54
Having same issue. I believe it is after the Windows .NET Framework updates. Tried to delete the xml config however issue persists. Additional error:

Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

**Comment by dmombo** [comment] 2020-02-23 20:56
I have the same problem.  Application won't start as of about 2 weeks ago.

**Comment by alexanderkay** [comment] 2020-10-14 00:51
I have the same issue:

Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.19041.546, time stamp: 0x2931f7ae
Exception code: 0xe0434352
Fault offset: 0x00129ab2
Faulting process id: 0x9820
Faulting application start time: 0x01d6a1c396ba2d88
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fd40b3ad-d2b6-47d4-8d83-6d20459e6529
Faulting package full name: 
Faulting package-relative application ID: 

Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at mRemoteNG.Settings.get_SingleInstance()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

**Comment by peterthomastlc** [comment] 2021-04-19 05:30
FYI: This was happening to me too.
I downloaded a zip of Prerelease v1.77.0 from the website, copied the confCons.xml from my existing %AppData%\mRemoteNG folder, and it works OK. Looks like v1.77.0 should be made into a stable release?

**Comment by Benzidrine** [comment] 2021-07-08 00:14
Same issue here. I'm looking for an alternative to the mRemoteNG now. 

Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0xcbf6f7d1
Exception code: 0xe0434352
Fault offset: 0x0012a6f2
Faulting process id: 0x357c
Faulting application start time: 0x01d7738dbcff2edd
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2ff57ee5-3776-46da-bf23-f185faaba4f9
Faulting package full name: 
Faulting package-relative application ID:

**Comment by farosch** [comment] 2021-12-14 19:41
We will have to wait for a new release for this.
The issue is already resolved in current develop branch.

**Closed by farosch** 2021-12-14 19:41 UTC
Labels: High Priority, Need 2 check
