### ISSUE TITLE
Crashes when connecting since updating to Windows 10 Enterprise 1903 x64 [Version 10.0.18362.175]

### ISSUE THREAD

**Issue by hingston** [mRemoteNG/mRemoteNG#1487] opened 2019-06-12 03:08 UTC
## Expected Behavior

Works on the latest Windows 10

## Current Behavior

Doesn't work since updating to Windows 10 Enterprise 1903 x64 [Version 10.0.18362.175]. The program crashes with no error displayed whenever you try to connect.

## Steps to Reproduce (for bugs)

1. Right click on a saved connection
2. Click Connect

Says "Connecting..." then a black screen flashes and the program crashes.

## Context

I need to remote into many servers so being able to save the connection information is very useful. I can now no longer connect at all.

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version: Windows 10 Enterprise 1903 x64 [Version 10.0.18362.175]

**Comment by hingston** [comment] 2019-06-12 03:26
#1343 seems related

**Comment by hingston** [comment] 2019-06-12 03:28
Event Viewer:

```
Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.18362.145, time stamp: 0xf5733ace
Exception code: 0xe06d7363
Fault offset: 0x001133d2
Faulting process ID: 0x3e18
Faulting application start time: 0x01d520bf28466176
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 9d07ccbf-47e2-41a6-a3cd-ccf8efceb794
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code e06d7363, exception address 762F33D2
```

**Comment by hingston** [comment] 2019-06-14 00:37
I notice when I disconnect my Lenovo 40A8 dock RDP connections work again. I am using the [latest drivers from Lenovo](https://pcsupport.lenovo.com/au/en/products/accessory/docks/thinkpad-usb-3-0-ultra-dock/40a8/downloads). Would this be a Lenovo issue or a mRemoteNG issue?

**Comment by sparerd** [comment] 2019-06-14 13:00
As you've discovered, we've had a few reports of issues with Win10 1903. It's interesting that we have several reports of this occurring specifically with laptop docks. I'm assuming the monitor connected via the dock is a different screen resolution than your laptop, is that correct? Is your laptop typically open or closed when on the dock? I'm wondering if this is related to mixed desktop resolutions or specifically to the dock. 

You can also try our v1.77 prerelease (backup your connections first, just to be safe) and see if that helps. We added additional support for HiDPI which may also help with mixed DPI environments.

**Comment by Scene-n-Heard** [comment] 2019-06-17 10:53
I think I have discovered the cause of the crashing. When using pre-release 1.77 which initially fixed the crashes, I noticed that clipboard redirect was not enabled by default. After turning it on I instantly experienced the crash when trying to RDP.

Turning off the clipboard redirect fixes the crashing.

**Comment by Titus-s** [comment] 2019-06-17 11:07
I can confirm that mRemoteNG 1.77 crash often when I've try to copy something from remote computer. It happen exacty after i use Ctrl+C. Clipboard redirect was enabled.

**Comment by sparerd** [comment] 2019-06-17 16:08
Interesting, good find @Scene-n-Heard.

@hingston Can you try the [mRemoteNG v1.77.0 prerelease](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.77.0) and see if the crashes still occur? Ensure that `Redirect Clipboard` is disabled for the connection, though it should be by default.

**Comment by sparerd** [comment] 2019-06-17 16:35
@hingston @Scene-n-Heard @Titus-s Do any of you have the clipboard history feature enabled in Windows? https://allthings.how/enable-clipboard-copy-history-windows-10/

**Comment by Titus-s** [comment] 2019-06-17 17:20
I forgot to mention that I work on Windows 7. As far as i remember when sharing clipboard was disabled crashes didn't appear so often. Disable it is not a good idea for me cause I often copy files and text between my computer and remote.

**Comment by Scene-n-Heard** [comment] 2019-06-18 10:47
@sparerd Clipboard history is turned off for me. I was using 1.77.0 when I discovered the issue, because turning on clipboard redirect on within 1.77.0 also caused the RDP connection to CTD.

As with @Titus-s I heavily uses the clipboard redirect function to transfer files between RDP seesions. It may also be worth noting that Drive redirect didn't work with 1.77.0, so I was unable to utilise that as a workaround when I needed to carry out a file transfer.

**Comment by hingston** [comment] 2019-06-19 00:17
@sparerd all 3 of my screens (1 laptop, 2 monitors) are 1920 x 1080 60Hz.

My laptop is open on the dock and all 3 screens are separate desktops (none mirrored).

I don't have clipboard history enabled.

If I unplug my dock, RDP, then reconnect my dock everything works as before.

**Comment by hingston** [comment] 2019-07-10 00:14
This is still an issue even after the July Windows 10 update. Is there any progress on identifying what is causing this?

**Comment by farosch** [comment] 2019-07-13 16:53
@hingston I think you already identified the problem: It's your dock.
Have you checked if there are any newer drivers available by now or maybe if there's a possibility to update the docks firmware?
The Lenovo 40A8 is known for it's bugs, as it is causing a lot of problems with VMware Horizon and Windows Updates in general.
Unfortunately I think there's not much we can do about this. Imho that's a problem that Lenovo will have to fix.

**Comment by arampon** [comment] 2019-08-06 19:52
@farosch : not the dock, Windows. That was the only variable and confirmed+fixed by OS vendor in 20H1.

Microsoft approved fix for multi-GPU machines for deployment to Windows 10 v1903 (19H1).
It is currently tracking to be an optional update starting rolling out on Tuesday 27th August (overall OS patch, not just that) and then pushed to all machines as part of the Tuesday 10th September cumulative patch and newer.

Optional updates are manually installed by going to Settings > Updates & Security > Windows Update, and clicking on "Check for updates".
There is no change to the dock driver you are currently using.

This #1487 is a duplicate of #1343

**Comment by Scene-n-Heard** [comment] 2019-08-30 07:58
It appears now that the clipboard redirect function no longer crashes 1.77.0, which means either a recent Windows update or Dell driver update has resolved the issue.

**Closed** 2019-08-30 12:20 UTC
Labels: Support Request, Vendor/Upstream Issue
