### ISSUE TITLE
[Feature Request] SSH - Copy all to clipboard

### ISSUE THREAD

**Issue by BloodyIron** [mRemoteNG/mRemoteNG#1199] opened 2018-11-30 02:43 UTC
For SSH I really would like it if I could right click on the tab for the server and, similar to PuTTY, "Copy all to clipboard".

This is particularly useful for getting lists of updates that are available when updating servers.

Please? :)

**Comment by kmscode** [comment] 2018-12-10 22:20
Off the top of my head, you can Ctrl+ right click inside the SSH session itself to get the copy all menu. But this would be convenient to have on the connection tab.

**Comment by kmscode** [comment] 2018-12-10 22:35
Closing as duplicate of #1189

**Closed by kmscode** 2018-12-10 22:35 UTC
Labels: Duplicate, Enhancement
