### ISSUE TITLE
RDP connection drops when moving the mREmoteNG window

### ISSUE THREAD

**Issue by lox33** [mRemoteNG/mRemoteNG#2595] opened 2024-05-23 14:51 UTC
RDP connection drops when moving the mREmoteNG window

Moving the mREmoteNG window while connected to a host will cause the RDP connection to the host to be lost.

**Comment by pepsican2** [comment] 2024-05-27 07:54
To elaborate. It happens when either you move the window or you resize the window of mRemote. It only disconnects. It does not log you off from the server, so whatever is running there, continues. This bug has a very high annoyance factor.

**Comment by simonai1254** [comment] 2024-05-27 16:51
Hi 

This issue is directly related to #2054 with the root cause documented in https://github.com/mRemoteNG/mRemoteNG/issues/2361#issuecomment-1448514909 (Reconnect when Resizing, Resizing when restoring down and restoring up). 
You can get rid of this behavior by specifying a display resolution until this behavior is fixed in the future.

Regards
Simon

**Comment by Kvarkas** [comment] 2024-06-26 10:30
Its limitation from Windows, that they seems already fixed in .net 8 but migration to it from .net 6 will be happening after this version release.

**Closed as completed by Kvarkas** 2024-06-26 10:30 UTC
Labels: TechnicalDebt, Third party, Windows, 1.77.3
