### ISSUE TITLE
New connections with incorrect panel (v1.77)

### ISSUE THREAD

**Issue by WiXZlo** [mRemoteNG/mRemoteNG#1441] opened 2019-05-07 10:27 UTC
Hello.
I have a trouble with panels in new version.
## Expected Behavior
New connection opens in different panel that I configured:
* Connection "Home" - panel "Home";
* Connection "Work" - panel "Work".

## Current Behavior
Connections ignore configured panel and create in current panel.

## Steps to Reproduce (for bugs)
1. Open mRemoteNG (no panels);
2. Connect to home router (in settings panel "Home");
3. Panel "Home" created, connection established;
4. Connect to work switch (in settings panel "Work");
5. Panel "Work" didn't create, connection opened in current panel "Home"

## Your Environment
* Version: 1.77.0.41252
* OS Windows 10 1809 x64:

**Comment by sparerd** [comment] 2019-05-07 21:37
I believe this is a duplicate of #1425 and will be fixed in the next alpha release

**Closed by sparerd** 2019-05-07 21:37 UTC
Labels: Bug, Duplicate

**Comment by mKlus** [comment] 2019-07-03 22:49
Hi @sparerd, I've installed develop version from appveyor as per below link but still see this issue.

https://ci.appveyor.com/project/mremoteng/mremoteng/branch/develop/job/8ppt661h0lbm1gpf/artifacts
