### ISSUE TITLE
MSI of Version 1.76 requires KB2574819 (not designed for my Win7 client)

### ISSUE THREAD

**Issue by DelPantalone** [mRemoteNG/mRemoteNG#1488] opened 2019-06-12 14:40 UTC
## Current Behavior

KB2574819 is required. When trying to install KB2574819, the update tells me it is not suiteable for my client.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Unable to install the MSI for v176

## Your Environment

* Version used: 
v1.76
* Operating System and version (e.g. Windows 10 1709 x64):
Win7 Enterprise Service pack 1 Build17110

**Comment by sparerd** [comment] 2019-06-12 14:49
As a workaround, set the `IGNOREPREREQUISITES` flag of the installer as described here: https://mremoteng.readthedocs.io/en/latest/installation/install.html#extend-installer-properties

This will be fixed as a part of #826 (currently being worked on).

**Comment by farosch** [comment] 2019-09-01 10:12
Closed, as duplicate of #1029

**Closed by farosch** 2019-09-01 10:12 UTC
Labels: Installer
