### ISSUE TITLE
REQUEST: VNC - new feature - full screen support

### ISSUE THREAD

**Issue by zenkovac** [mRemoteNG/mRemoteNG#2146] opened 2022-01-28 15:09 UTC
Hi, the VNC protocol doesnt have an option for full screen, the should be a button to enable full screen connection to VNC.

**Comment by LIyoai** [comment] 2022-01-29 09:07
#1679

**Comment by farosch** [comment] 2022-02-02 23:12
Duplicate of #1679

**Closed as completed by farosch** 2022-02-02 23:12 UTC
