### ISSUE TITLE
[REQUEST] AudioCaptureRedirectionMode property 

### ISSUE THREAD

**Issue by Shamatix** [mRemoteNG/mRemoteNG#403] opened 2017-02-15 07:07 UTC
It would be nice if https://msdn.microsoft.com/en-us/library/ee338627.aspx this could be implemented so we can use our microphones on our RDPs :) 

Would mean a lot.

**Comment by kmscode** [comment] 2017-02-22 14:29
Duplicate of #383

**Closed by kmscode** 2017-02-22 14:29 UTC
Labels: Duplicate, Feature Request
