### ISSUE TITLE
Display resolution issue 

### ISSUE THREAD

**Issue by Macc77** [mRemoteNG/mRemoteNG#736] opened 2017-10-10 06:23 UTC
Dear,

I got a bug with mRemote on Linux : 

It display the half of the command lines... I have to reduce the window and then make it full again to have full command lines.

Sorry for my english. 

Best regards

**Comment by kmscode** [comment] 2019-03-10 19:34
Seems like a duplicate of #297. Likely related to TeamViewer. This was not reproducible by the dev team (even with TeamViewer).

**Closed by kmscode** 2019-03-10 19:34 UTC
Labels: Cannot Reproduce
