### ISSUE TITLE
Connection Tree OnClick NullReference

### ISSUE THREAD

**Issue by KOTRET** [mRemoteNG/mRemoteNG#428] opened 2017-03-03 08:13 UTC
OS: Windows 7 Professional (6.1, Build 7601, SP1)
mRemoteNG: 1.75.6269.29909

when having `<system.windows.forms jitDebugging="false" />` or this key is missing and clicking in the white space below the connections, an error is raised:
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei mRemoteNG.UI.Controls.ConnectionTree.OnMouse_SingleClick(Object sender, MouseEventArgs mouseEventArgs)
   bei System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   bei System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

When the key for `jitDebugging` is set to `true` , the error does not occur.

```
loaded assemblies:
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
mRemoteNG
    Assembly-Version: 1.75.6269.29909.
    Win32-Version: 1.75.6269.29909.
    CodeBase: file:///D:/Programme/mRemoteNG/mRemoteNG.exe.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
mRemoteNG.resources
    Assembly-Version: 1.75.6269.29909.
    Win32-Version: 1.75.6269.29909.
    CodeBase: file:///D:/Programme/mRemoteNG/de/mRemoteNG.resources.DLL.
----------------------------------------
BouncyCastle.Crypto
    Assembly-Version: 1.8.1.0.
    Win32-Version: 1.8.15362.1.
    CodeBase: file:///D:/Programme/mRemoteNG/BouncyCastle.Crypto.DLL.
----------------------------------------
log4net
    Assembly-Version: 1.2.15.0.
    Win32-Version: 1.2.15.0.
    CodeBase: file:///D:/Programme/mRemoteNG/log4net.DLL.
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly-Version: 2.9.0.0.
    Win32-Version: 2.9.0.0.
    CodeBase: file:///D:/Programme/mRemoteNG/WeifenLuo.WinFormsUI.Docking.DLL.
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light
    Assembly-Version: 2.9.0.0.
    Win32-Version: 2.9.0.0.
    CodeBase: file:///D:/Programme/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light.DLL.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1055.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
MagicLibrary
    Assembly-Version: 1.7.4.0.
    Win32-Version: 1.7.4.0.
    CodeBase: file:///D:/Programme/mRemoteNG/MagicLibrary.DLL.
----------------------------------------
WindowsBase
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll.
----------------------------------------
ObjectListView
    Assembly-Version: 2.9.1.1072.
    Win32-Version: 2.9.1.0.
    CodeBase: file:///D:/Programme/mRemoteNG/ObjectListView.DLL.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
System.Management
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1087.0 built by: NETFXREL4STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1055.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1055.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
```

**Comment by sparerd** [comment] 2017-03-03 14:55
Closing as duplicate of #422 

A fix will be released in the next few days

**Closed by sparerd** 2017-03-03 14:55 UTC
