### ISSUE TITLE
Feature Request: Connection Thumbnails

### ISSUE THREAD

**Issue by HolyOne** [mRemoteNG/mRemoteNG#873] opened 2018-01-29 20:25 UTC
I find Remote desktop connection managers thumbnail veiw quite useful.
I think remoteng should have a thumbnail view, which displays thumbnails of active connections under active group.

Bonus points: thumbnails can be resized with a trackbar or something

**Comment by sparerd** [comment] 2018-01-29 22:40
Duplicate of #574. Please follow that issue for any updates

**Closed by sparerd** 2018-01-29 22:40 UTC
Labels: Duplicate
